### ISSUE TITLE
Stuck in arrow selection mode

### ISSUE THREAD

**Issue by FeedMeOreos** [Cockatrice/Cockatrice#5091] opened 2024-08-03 15:51 UTC
**System Information:**
Client Version: 2.9.0 (2023-09-14)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: en_US
Install Mode: Standard

_______________________________________________________________________________________

When playing on my laptop and using Ctrl+A to create arrows using the trackpad, MANY arrows are created. I am able to select one target with the arrow but all the other ones remain. Clicking on the background destroys them one by one but it takes a while and it keeps generating more even without triggering the arrow.

Nothing lets me escape the "arrow-selection" mode other than closing cockatrice and re-opening it.

This is what it looks like from my end.

![image](https://github.com/user-attachments/assets/7a9a3407-76c9-4b54-83dc-6ef220b81f11)

Looking at the debug log it seems like it generates an arrow per tick while I'm holding Ctrl+A.
![image](https://github.com/user-attachments/assets/2b9c6e72-48a1-4824-8196-3c91e50c48ee)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Enter arrow-creation mode (Ctrl+A)
 - Click card the arrow will originate from
 - Watch Arrow Fireworks Unfold

**Comment by ebbit1q** [comment] 2024-08-03 21:07
this is a duplicate of https://github.com/Cockatrice/Cockatrice/issues/4329 please add a comment to an existing issue before creating a new one

**Closed by ebbit1q** 2024-08-03 21:07 UTC
Labels: Bug
