### ISSUE TITLE
Suggestion:new mulligan rule

### ISSUE THREAD

**Issue by i-c-a-t** [Cockatrice/Cockatrice#3787] opened 2019-07-17 14:32 UTC
With the new mulligan rule plz shuffle all cards back and licensing 7 every time。

**Comment by ctrlaltca** [comment] 2019-07-17 14:35
Duplicate of #3749, fixed in #3773

**Closed by ctrlaltca** 2019-07-17 14:35 UTC

**Comment by tooomm** [comment] 2019-07-17 15:12
@i-c-a-t make sure to use the newest beta to use this feature!
