### ISSUE TITLE
High CPU Usage In Chat Tab

### ISSUE THREAD

**Issue by MustyMustelidae** [Cockatrice/Cockatrice#774] opened 2015-02-21 17:51 UTC
Previous to updating to the latest weekly (I hadn't updated for quite some time before that) Cockatrice didn't use too much CPU. Now I'm getting extreme spikes, especially on the main tab:

![Graph of CPU Usage for cockatrice process](https://cloud.githubusercontent.com/assets/6193755/6315113/8aa0a006-b9c5-11e4-9948-8a6141ca2b25.png)

In that graph I have one game open. at 12:02:05, I switch to the main tab. As you can see, while in the game tab, there are no spikes. The moment I switch to the main tab, the CPU utilization increases dramatically. I'm having trouble reproducing this consistently.

In this specific instance, I tried clearing the chat, with no result, but turning off "Show Unavailable Games" seemed to cause a sudden drop. Yet re-enabling "Show Unavailable Games" didn't cause a spike ~~(so that might be a red herring)~~

While typing this up I tried enabling  "Show Unavailable Games" again. There was no spike. But the moment I tried scrolling there was a sharp increase in CPU usage, and there was no drop until I switched tabs (switching back still resumed the increase in CPU usage). I've annotated a graph:

![Second Graph of cockatrice CPU usage](https://cloud.githubusercontent.com/assets/6193755/6315160/3a673d32-b9c7-11e4-8e79-653edff53e15.png)

MassCraziness was unable to reproduce this spike, however I hadn't had made the connection to scrolling through the game list at that time. I was under the impression having other tabs open was what causing it, but it was simply a red herring. To have another tab, you usually scroll through the game list, then join a game. Since the CPU usage doesn't spike while in another tab, it would become spike would become apparent upon switching back to the main tab, after having added a new tab.

I'm also not sure that "Show Unavailable Games" is the actual cause vs the simple increase in the number of games. I had "Game Created" sorting enabled too. Further discerning of which specific factor could be the cause will take more time. I'm on Windows 8.1 with build edd3b75 and all graphs are monitoring the CPU usage of Cockatrice's process only (not the whole system).

**Comment by MassCraziness** [comment] 2015-02-21 18:04
In the same build, on the same OS (Windows 8.1), having 2 PM windows open and a game lobby open, showing all unavailable games and scrolling through the list at different speeds, I am still unable to reproduce this problem. My CPU usage doesn't even break 30% for Cockatrice.

**Comment by ZeldaZach** [comment] 2015-02-21 18:21
Maybe having the service constantly check for cards, user mentions, and links on every message is causing this?

**Comment by woogerboy21** [comment] 2015-02-21 18:27
What is our system specs (including type of video card and memory)?






From: MustyMustelidae
Sent: ‎Saturday‎, ‎February‎ ‎21‎, ‎2015 ‎12‎:‎51‎ ‎PM
To: Daenyth/Cockatrice





Previous to updating to the latest weekly (I hadn't updated for quite some time before that) Cockatrice didn't use too much CPU. Now I'm getting extreme spikes, especially on the main tab:

 Graph of CPU Usage for cockatrice process 

In that graph I have one game open. at 12:02:05, I switch to the main tab. As you can see, while in the game tab, there are no spikes. The moment I switch to the main tab, the CPU utilization increases dramatically. I'm having trouble reproducing this consistently.

In this specific instance, I tried clearing the chat, with no result, but turning off "Show Unavailable Games" seemed to cause a sudden drop. Yet re-enabling "Show Unavailable Games" didn't cause a spike (so that might be a red herring)

While typing this up I tried enabling "Show Unavailable Games" again. There was no spike. But the moment I tried scrolling there was a sharp increase in CPU usage, and there was no drop until I switched tabs (switching back still resumed the increase in CPU usage). I've annotated a graph:

 Second Graph of cockatrice CPU usage 

MassCraziness was unable to reproduce this spike, however I hadn't had made the connection to scrolling through the game list at that time. I was under the impression having other tabs open was what causing it, but it was simply a red herring. To have another tab, you usually scroll through the game list, then join a game. Since the CPU usage doesn't spike while in another tab, it would become spike would become apparent upon switching back to the main tab, after having added a new tab.

I'm also not sure that "Show Unavailable Games" is the actual cause vs the simple increase in the number of games. I had "Game Created" sorting enabled too. Further discerning of which specific factor could be the cause will take more time. I'm on Windows 8.1 with build edd3b75 and all graphs are monitoring the CPU usage of Cockatrice's process only (not the whole system).

**Comment by MassCraziness** [comment] 2015-02-21 18:29
After talking this over with @MustyMustelidae and setting up a better logging process, I notice switching to the main tab causes a spike (roughly to 30%). Scrolling through the game list with no filters at rapid speed spikes it up more. Setting it to show all unavailable games causes it to spike to incredibly. Staying in main chat tab with no filters results in the CPU going up and down, spiking up to 20-30% at most. Setting it to show unavailable games causes the max spike to increase, but not by much. When chat activity occurs it goes up more (as expected).

In the end, it doesn't seem to be terribly consuming in the long run, and isn't really an issue unless you're deliberately trying to eat all of your CPU.

**Comment by woogerboy21** [comment] 2015-02-21 18:43
My initial guess on this is the calculations done for PR #758 .  I haven't looked at the code but depending on how @poixen implemented working with a negative value could induce higher cpu loads for those calculations and if there are multiples that occur that the client has to maintain it could be causing the higher load seen.

**Comment by MassCraziness** [comment] 2015-02-21 18:47
@woogerboy21 Also, that it now automatically re-sorts could be causing a slightly higher load as it constantly resorts the game list. Could be. I don't really know for certain.

**Comment by MustyMustelidae** [comment] 2015-02-21 18:47
The CPU is an i7 4712HQ, GPU is a Quadro K1100M, 16GB ram. 

I was just telling @MassCraziness, after comparing this to an older build, I don't think it's too big of an issue. The older build is a lot better about handling the large list, but when I turn off all filters it starts to act similarly to the new build with only one of the flters off. It's probably an unavoidable side-effect of the new sorting options. 

I do think that maybe a closer look can be taken at if there are any simple optimizations that might have been missed in recent changes since the apparent changes to the game listings (there may be back-end ones I can't see) between the builds I'm comparing (a31c15c and edd3b75) don't seem like they should be *too* demanding. 

The main ones I see are a change in how the Game Created sorting works and small visual changes so, maybe there's a call being made that should be cached or memoized. 

But to sum all that up again, I don't think it's a *huge* issue, I probably wouldn't have noticed the change in performance if I wasn't using power management savings features when I first installed the new weekly.

**Comment by Daenyth** [comment] 2015-02-21 20:23
I'm not sure what might do it...
```
master!Cockatrice/build> shortlog --no-merges  --since=2015-02-14
Fabio Bas (7):
      Fix #745
      When compiling with qt5, require at least version 5.0.3
      Attempt to get travis compile using qt5.2
      Even make is too old.. 2.8.9 is required, this repo offers 2.8.11
      Added qt5multimedia
      linux+clang+qt5 works now, disable allow_failures
      Fix oracle progressbar; fix #764

Jeffrey Oliver (2):
      Add full and short name for card color filters.
      Use qstring replace.     Iterate through the filter to see if everything matches the card.

Matt Lowe (4):
      Updated to 48x48
      Fixed 5+ hour issue for new games
      Updated image
      Updated player fighting svg
```

**Comment by ZeldaZach** [comment] 2015-04-10 21:16
I'm starting to feel the effects of this as my chat is lagging whenever I open it / change to it

**Comment by ctrlaltca** [comment] 2015-04-16 10:29
Closing since the proposed fix got merged

**Closed by ctrlaltca** 2015-04-16 10:29 UTC
Labels: Cleanup, Cockatrice, Servatrice
