### ISSUE TITLE
Segmentation fault on Arch Linux, gdb trace and more info inside

### ISSUE THREAD

**Issue by CanadianBakn** [Cockatrice/Cockatrice#1139] opened 2015-06-14 23:24 UTC
I am getting a segmentation fault after Cockatrice has been open for some time. It runs and everything seems to work, but will crash after a seemingly random time interval (my best guess is a memory leak?).

All my cards appear normally, with text, and images, and I seem to be able to play fine before the crash, so I doubt anything is misconfigured but that's a possibility.

I got a bit of info from gdb: 

http://pastie.org/10202981

**Comment by Daenyth** [comment] 2015-06-15 00:03
Maybe related to #1105 ? What commit version are you running?

**Comment by ctrlaltca** [comment] 2015-06-15 07:40
From the attachment it seems that cockatrice crashed as the result of receiving a server shutdown message. We recently fixed the really similar issue #1105, so i suppose this is a dupe.
Can you tell us the cockatrice version you're running?

**Comment by ctrlaltca** [comment] 2015-06-22 16:26
closing as a dupe of #1105, please reopen if you have more feedback.

**Closed by ctrlaltca** 2015-06-22 16:26 UTC
Labels: Cockatrice, Crash, Linux
