### ISSUE TITLE
Issue with Reveal/Unreveal top card and shuffling.

### ISSUE THREAD

**Issue by Insertcleverphrasehere** [Cockatrice/Cockatrice#3719] opened 2019-05-11 22:12 UTC
When using the "Always reveal top card" function (Ctrl N). if you unreveal the top card it remains revealed (this is fine, as this is known game information and I imagine it is intended functionality). 

However, if the player then shuffles their deck, the top of their deck will remain with the image of the 'revealed card', even though it is not really there and is just a ghost (from testing, the deck IS properly shuffled). 

Fix: If "Always reveal top card" is OFF, but there is a card revealed as a carry over from when it was previously on, make this card 'unreveal' whenever the deck is shuffled. Alternatively, if "Always reveal top card" is turned OFF, flip the top card back face down (this is a paper play simulator, and it is somewhat awkward that the top card can't be turned back face down if revealed by mistake etc, and I expect that players can just play like they normally do in paper magic).

**Comment by ebbit1q** [comment] 2019-05-11 22:39
I'm in favor of fix 2

**Comment by tooomm** [comment] 2019-05-12 08:00
Linking https://github.com/Cockatrice/Cockatrice/issues/1486

**Comment by ZeldaZach** [comment] 2020-09-28 19:22
Dupe of #1486 as tom stated

**Closed by ZeldaZach** 2020-09-28 19:22 UTC
