### ISSUE TITLE
Tapping cards to the left side

### ISSUE THREAD

**Issue by jonathanpauluze** [Cockatrice/Cockatrice#4981] opened 2024-01-10 18:27 UTC
**Similar Requests**

**Description of New Feature**
An option in context menu for tapping cards to the left side.

**Additional Context**
I play a game called Marvel Battle Scenes (only available in Brazil), in this game we need to be able to tap the card for both sides. There's a mechanic to "capacitate" a character card and there's 3 levels:
- 0 (tapping to the right side →)
- 1 (putting the card in normal play position)
- 2 (tapping to the left side ←)
![bs_capacitacao](https://github.com/Cockatrice/Cockatrice/assets/26353495/7d49a004-c1fd-4a79-949a-88458f8d48a2)

After some research I couldn't find how to tap the card to the left side. Is there any possibility of this feature being added in future?

**Comment by ebbit1q** [comment] 2024-01-16 18:18
I propose to merge this ticket into https://github.com/Cockatrice/Cockatrice/issues/3094

**Comment by ZeldaZach** [comment] 2024-01-17 05:32
Closing as dupe of #3094

**Closed by ZeldaZach** 2024-01-17 05:32 UTC
Labels: Feature Request
