### ISSUE TITLE
Check for Updates + Open Oracle from Cockatrice

### ISSUE THREAD

**Issue by Zeofar** [Cockatrice/Cockatrice#210] opened 2014-07-14 17:19 UTC
Several points: there are _literally_ hundreds of people that ask for help updating the card database every time a new set is released; being able to access an update utility directly from the relevant program just makes sense; with improved oracle speed and search functionality, the benefits of not downloading every card set have dropped to zilch.

Proposal:
- [x] Add link to Oracle in Cockatrice's main dropdown menu (Restart Cockatrice on Oracle quit if db was modified)
- [ ] Add "Check for Updates" to dropdown, which checks if all set names from mtgjson are present in user's db
- [ ] Include setting to opt into checking for updates every time Cockatrice starts
- [ ] Include moderator-editable message with manual update check (e.g. "Set X will be available for download when mtgjson updates", "Download the new version of Cockatrice here...")

Having a button to click for instant reassurance would do a lot to reduce endless requests for help updating and make it easier to tell people how to update. And, yes, the server message exists, but people rarely pay attention to it.

**Comment by ctrlaltca** [comment] 2015-06-03 21:07
Implemented first point in #1039

**Comment by Daenyth** [comment] 2016-01-01 16:12
Ref #1727 #1607

**Comment by tooomm** [comment] 2017-05-09 10:36
Linking https://github.com/Cockatrice/Cockatrice/issues/2416

**Comment by tooomm** [comment] 2017-12-13 19:40
>Include setting to opt into checking for updates every time Cockatrice starts

That should be covered in https://github.com/Cockatrice/Cockatrice/issues/2924!

**Comment by ctrlaltca** [comment] 2020-03-29 16:08
Closing this issue since the remaining points are basically a duplicate of #2924 and #3647

**Closed by ctrlaltca** 2020-03-29 16:08 UTC
Labels: App - Cockatrice, App - Oracle
