### ISSUE TITLE
Token Creation Issues in Local Play

### ISSUE THREAD

**Issue by DrWormDDS** [Cockatrice/Cockatrice#4978] opened 2024-01-06 17:52 UTC
**System Information:**
Client Version: 2.9.0 (2023-09-14)
Client Operating System: macOS 14.1
Build Architecture: 64-bit
Qt Version: 6.5.1
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "VelvetMarble"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Unable to load qt translation "qt_" at "/Applications/cockatrice.app/Contents/Resources/translations"
Unable to load "cockatrice" translation "cockatrice_" at "/Applications/cockatrice.app/Contents/MacOS/../Resources/translations"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_529561"
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/Users/liamvelasquez/Library/Application Support/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/Users/liamvelasquez/Library/Application Support/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 28351 Sets = 733 "1964ms"
[CockatriceXml4Parser] Trying to parse:  "/Users/liamvelasquez/Library/Application Support/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/Users/liamvelasquez/Library/Application Support/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 29126 Sets = 733 "42ms"
[CardDatabase] loadCardDatabase(): Path = "/Users/liamvelasquez/Library/Application Support/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 29126 Sets = 733 "0ms"
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

When I start a local game and create a token either my client crashes or the token menu closes with nothing happening. A few times it has worked fine, but most of the time I have an issue. I tried to see if there was a pattern to the crashes by having cards in hand/on the battlefield or having no cards out at all but it happens regardless of the scenario in the game and regardless of deck.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Start a local game
 - Set it to 1 player
 - Load a 100 card singleton deck
 - Unlock sideboard
 - Right click and select create a token
 - Select a token
 - Crash/menu closes

**Comment by ebbit1q** [comment] 2024-01-16 18:23
I'm unable to reproduce your issue but I'm not sure if I'm following your steps correctly, you don't seem to be doing anything specific that would be different from normal use that would cause a crash, you are saying your client just has a bug randomly when you open the dialog?

**Comment by ebbit1q** [comment] 2024-03-27 13:51
I'll be closing this issue for now, if the issue still persists please reopen the issue.

**Closed by ebbit1q** 2024-03-27 13:51 UTC
Labels: Bug
