### ISSUE TITLE
OSX: Keybinds disabled after sideboard

### ISSUE THREAD

**Issue by francisalbar** [Cockatrice/Cockatrice#2490] opened 2017-03-17 16:41 UTC
<b>OS:</b>
*macOS Sierra 10.12.4 Beta (16E183b)*

<b>Cockatrice version:</b>
*Version 6e723b2 (2017-03-14)*

___
<br>

After sideboarding, keybinds (such as life total cmd+L or mulligan cmd+M) no longer work. Can get around issue by moving to another cockatrice tab, then going back to game tab.

**Comment by Daenyth** [comment] 2017-03-18 00:15
I wonder if something in the tab is stealing focus and eating the keybinds. Maybe the chat window. I think we had an issue with that before.

**Comment by ZeldaZach** [comment] 2017-03-18 06:22
I'm OS 10.12.3 and I don't have this issue... this is weird

**Comment by ZeldaZach** [comment] 2017-03-18 09:39
Change of plans, upon playing I've noticed this too. Weird bug

**Comment by serrano65** [comment] 2017-03-24 17:12
Hi! I am new at Cockatrice and I have the same issue. Have you solve it? 

Thank you :)

**Comment by Daenyth** [comment] 2017-03-24 19:18
It's not fixed yet - we've been focusing on some crash bugs with the new release.

**Comment by Daenyth** [comment] 2017-04-21 12:05
Let's consider re-testing this with #2583 reverted and try to pinpoint the exact spot so we can make a surgical fix, given that 2583 has had unexpected negative impact on other functions.

Really if anyone heroic wants to take a swing at refactoring the game tab from scratch you'd be a hero too, and probably improve this as well as many things.

**Comment by ctrlaltca** [comment] 2017-04-21 15:53
#2583 reverted in #2619, this is good to be triaged again

**Comment by tooomm** [comment] 2017-04-21 15:58
#2619 also reverted #2604 ^^

**Comment by ctrlaltca** [comment] 2017-04-24 20:19
The last good version is "All Hallow's Eve, Revision 2", the first broken is "Thopter Pie Network".
Trying to bisect the bug lead to nowhere, as the problem seems related to the switch from Qt 5.7 to 5.8.
I've just configured travis in order to build using Qt 5.7, so that we can test if it resolves the issue for the moment.

**Comment by ctrlaltca** [comment] 2017-04-25 09:25
The issue is currently fixed for me in the prerelease https://github.com/Cockatrice/Cockatrice/releases/tag/2017-04-25-Development-2.3.17-beta002 , it would be nice if someone could confirm

**Comment by ctrlaltca** [comment] 2017-04-25 15:17
Closing, see #2647

**Closed by ctrlaltca** 2017-04-25 15:17 UTC
Labels: App - Cockatrice, Defect - Basic, OS - macOS
