### ISSUE TITLE
Chat box in game keeps losing focus

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1612] opened 2015-09-30 21:07 UTC
It's very annoying to have to keep clicking on the chat box whenever you need to type something in a game. The chat box should just always be focused so it is easy to start typing.

**Comment by Nightfirecat** [comment] 2015-09-30 21:35
Duplicate of #1529.

**Closed** 2015-10-01 00:22 UTC

**Comment by Psithief** [comment] 2015-10-01 04:02
Hmm, funny how we didn't do anything about this. Opened #1615.
