### ISSUE TITLE
Secret Voting Feature Request

### ISSUE THREAD

**Issue by orionSquared** [Cockatrice/Cockatrice#4994] opened 2024-01-25 20:18 UTC
**Similar Requests**
None that I could find

**Description of New Feature**
To handle cards like Wheel of Misinformation/Prisoner's Dilemma, I think cockatrice needs a way to handle secret voting. I don't 100% know the best way to handle this as I'm sure there are many avenues that could be taken to achieve this, but I did have an idea that I thought could work.

When creating a token, give us the ability to create the token face down. Creating tokens is a simple way that we relay all kinds of information to the table and it's a sure-fire way that we can "lock in" a vote without the ability for someone to cheat. So when playing the Wheel of Misinformation, the players would all create a token face down with the chosen number and once all players have created their token, everyone can flip them face-up.

Ideally the game log would only show "(user) has created a token face-down" or something like that, so it doesn't display the name of the token to the chat like it does when you create them face-up. Then when the token is turned face-up, the game log can display the token and the text on the token then.

**Additional Context**
I know the current advice on cockatrice is just to not play these cards, but it just seems a bit unfair to ask people not to play a set of cards just because the platform can't currently support them. And for many, we use cockatrice to test out new deck ideas and deck updates before we go and buy the cards for our paper decks, so not being able to test a card can be frustrating to people.

Thank you for all the time and hard work you spend on this project. It's a fantastic platform that many use to play MtG online and I love it.

**Comment by ebbit1q** [comment] 2024-01-26 13:12
duplicate of https://github.com/Cockatrice/Cockatrice/issues/3278

**Closed by ebbit1q** 2024-01-26 13:12 UTC
Labels: Feature Request
