### ISSUE TITLE
Can we draw from the bottom of the deck?

### ISSUE THREAD

**Issue by properpronoun** [Cockatrice/Cockatrice#4833] opened 2023-07-29 18:51 UTC
**Similar Requests**

**Description of New Feature**
With the addition of River Song, can we please draw from the bottom, or have the same functions that we have for drawing normally like (move x cards to hand, move x cards to graveyard, etc). I would like to not let everyone see what I draw as I have to move it to the graveyard now

**Additional Context**

**Comment by SlightlyCircuitous** [comment] 2023-08-01 16:53
This is already mostly implemented, depending on what client you are using. 

In the main client (Cockatrice 2.8.0), you can hold ctrl and drag a card from the library into your hand to draw from the bottom. You can bind the other options you wanted to shortcuts under `Settings > Shortcuts` to be able to do things like draw x or move x to graveyard. 

In the beta client (Cockatrice 2.8.1-beta2 and higher), there is an option in the context menu for the deck (right click / two-finger click) that lets you manipulate the bottom card(s) however you want. 

However, I say 'mostly implemented' because, as far as I can tell, all of those options reveal the name of the card in the chat log. For a card like River Song, that would need to be changed.

**Comment by tooomm** [comment] 2023-08-05 11:04
> drawing any number of cards from the bottom reveals the name of the card in the chat log

That sounds like a bug, doesn't it?
Moving a unknown, hidden card between zones should not reveal it I guess. :) Is that filed already?

**Comment by SlightlyCircuitous** [comment] 2023-08-05 16:00
It doesn't look like it is filed already. I can file it as I have already looked into what might be the cause a little.

**Comment by SlightlyCircuitous** [comment] 2023-08-05 16:24
Bug filed: https://github.com/Cockatrice/Cockatrice/issues/4834

**Comment by tooomm** [comment] 2023-08-06 21:34
I'm closing this as it's already possible in recent beta versions.
Please try them @properpronoun. But keep the current limitation in mind and consider to follow the other bug ticket.

Feel free to comment here on the topic, or open any other problems you find in new issues.

**Closed** 2023-08-06 21:34 UTC
Labels: Feature Request
