### ISSUE TITLE
drag & drop grid placement reliabilitity

### ISSUE THREAD

**Issue by mcandre** [Cockatrice/Cockatrice#4817] opened 2023-06-21 00:24 UTC
**System Information:**

Client Version: 2.8.0 (2021-01-26)
PictureLoader: [card:  "Honor of the Pure"  set:  "MD1" ]: Trying to load picture
PictureLoader: [card:  "Honor of the Pure"  set:  "MD1" ]: Picture found on disk.
PictureLoader: [card:  "Oblivion Ring"  set:  "MM2" ]: Trying to load picture
PictureLoader: [card:  "Oblivion Ring"  set:  "MM2" ]: Picture found on disk.
PictureLoader: [card:  "Gather the Townsfolk"  set:  "DKA" ]: Trying to load picture
PictureLoader: [card:  "Gather the Townsfolk"  set:  "DKA" ]: Picture found on disk.
PictureLoader: [card:  "Spare from Evil"  set:  "ISD" ]: Trying to load picture
PictureLoader: [card:  "Spare from Evil"  set:  "ISD" ]: Picture found on disk.
addCounter: "Player 1" 0 "life"
addCounter: "Player 1" 1 "w"
addCounter: "Player 1" 2 "u"
addCounter: "Player 1" 3 "b"
addCounter: "Player 1" 4 "r"
addCounter: "Player 1" 5 "g"
addCounter: "Player 1" 6 "x"
addCounter: "Player 1" 7 "storm"
PictureLoader: [card:  "Lightning Strike"  set:  "SLD" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Lightning Strike"  set:  "SLD" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Lightning Strike"  set:  "SLD" ]: Trying to load picture
PictureLoader: [card:  "Elemental Token"  set:  "NEC" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Elemental Token"  set:  "NEC" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Elemental Token"  set:  "NEC" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Eidolon of the Great Revel"  set:  "SLD" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Eidolon of the Great Revel"  set:  "SLD" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Soul-Scar Mage"  set:  "SLD" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Soul-Scar Mage"  set:  "SLD" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Play with Fire"  set:  "DBL" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Play with Fire"  set:  "DBL" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Kessig Flamebreather"  set:  "DBL" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Kessig Flamebreather"  set:  "DBL" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
addCounter: "Player 2" 0 "life"
addCounter: "Player 2" 1 "w"
PictureLoader: [card:  "Lightning Strike"  set:  "SLD" ]: Picture found on disk.
PictureLoader: [card:  "Blazing Crescendo"  set:  "ONE" ]: Trying to load picture
addCounter: "Player 2" 2 "u"
addCounter: "Player 2" 3 "b"
addCounter: "Player 2" 4 "r"
addCounter: "Player 2" 5 "g"
addCounter: "Player 2" 6 "x"
addCounter: "Player 2" 7 "storm"
addCounter: "Player 1" 0 "life"
addCounter: "Player 1" 1 "w"
addCounter: "Player 1" 2 "u"
addCounter: "Player 1" 3 "b"
addCounter: "Player 1" 4 "r"
addCounter: "Player 1" 5 "g"
addCounter: "Player 1" 6 "x"
PictureLoader: [card:  "Blazing Crescendo"  set:  "ONE" ]: Picture found on disk.
PictureLoader: [card:  "Young Pyromancer"  set:  "2X2" ]: Trying to load picture
addCounter: "Player 1" 7 "storm"
addCounter: "Player 2" 0 "life"
addCounter: "Player 2" 1 "w"
addCounter: "Player 2" 2 "u"
addCounter: "Player 2" 3 "b"
addCounter: "Player 2" 4 "r"
addCounter: "Player 2" 5 "g"
addCounter: "Player 2" 6 "x"
addCounter: "Player 2" 7 "storm"
PictureLoader: [card:  "Young Pyromancer"  set:  "2X2" ]: Picture found on disk.
PictureLoader: [card:  "March of Reckless Joy"  set:  "NEO" ]: Trying to load picture
PictureLoader: [card:  "March of Reckless Joy"  set:  "NEO" ]: Picture found on disk.
PictureLoader: [card:  "Shock"  set:  "BBD" ]: Trying to load picture
PictureLoader: cache fail for "_trice_card_back_96136"
PictureLoader: [card:  "Shock"  set:  "BBD" ]: Picture found on disk.
PictureLoader: [card:  "Elemental Token"  set:  "NEC" ]: Trying to load picture
PictureLoader: [card:  "Elemental Token"  set:  "NEC" ]: Picture found on disk.
PictureLoader: [card:  "Stoke the Flames"  set:  "MOM" ]: Trying to load picture
PictureLoader: [card:  "Stoke the Flames"  set:  "MOM" ]: Picture found on disk.
PictureLoader: [card:  "Mountain"  set:  "IKO" ]: Trying to load picture
PictureLoader: [card:  "Mountain"  set:  "IKO" ]: Picture found on disk.
PictureLoader: [card:  "Eidolon of the Great Revel"  set:  "SLD" ]: Trying to load picture
PictureLoader: [card:  "Eidolon of the Great Revel"  set:  "SLD" ]: Picture found on disk.
PictureLoader: [card:  "Sentinel Totem"  set:  "XLN" ]: Trying to load picture
PictureLoader: [card:  "Sentinel Totem"  set:  "XLN" ]: Picture found on disk.
PictureLoader: [card:  "Barrage of Expendables"  set:  "JMP" ]: Trying to load picture
PictureLoader: [card:  "Barrage of Expendables"  set:  "JMP" ]: Picture found on disk.
PictureLoader: [card:  "Spikefield Hazard"  set:  "ZNR" ]: Trying to load picture
PictureLoader: [card:  "Spikefield Hazard"  set:  "ZNR" ]: Picture found on disk.
PictureLoader: [card:  "Soul-Scar Mage"  set:  "SLD" ]: Trying to load picture
PictureLoader: [card:  "Soul-Scar Mage"  set:  "SLD" ]: Picture found on disk.
PictureLoader: [card:  "Play with Fire"  set:  "DBL" ]: Trying to load picture
PictureLoader: [card:  "Play with Fire"  set:  "DBL" ]: Picture found on disk.
PictureLoader: [card:  "Roiling Vortex"  set:  "ZNR" ]: Trying to load picture
PictureLoader: [card:  "Roiling Vortex"  set:  "ZNR" ]: Picture found on disk.
PictureLoader: [card:  "Hazoret the Fervent"  set:  "AKH" ]: Trying to load picture
PictureLoader: [card:  "Hazoret the Fervent"  set:  "AKH" ]: Picture found on disk.
PictureLoader: [card:  "Wrangle"  set:  "AER" ]: Trying to load picture
PictureLoader: [card:  "Wrangle"  set:  "AER" ]: Picture found on disk.
PictureLoader: [card:  "Bomat Courier"  set:  "KLD" ]: Trying to load picture
PictureLoader: [card:  "Bomat Courier"  set:  "KLD" ]: Picture found on disk.
PictureLoader: [card:  "Kessig Flamebreather"  set:  "DBL" ]: Trying to load picture
PictureLoader: [card:  "Kessig Flamebreather"  set:  "DBL" ]: Picture found on disk.
PictureLoader: [card:  "Increasing Devotion"  set:  "DKA" ]: Trying to load picture
PictureLoader: [card:  "Increasing Devotion"  set:  "DKA" ]: Picture found on disk.
CardDragItem: coordinate overflow: x = -4.73632 , y = 33.9232
CardDragItem: coordinate overflow: x = -0.186948 , y = 21.6857
PictureLoader: cache fail for "_trice_card_back_276194"
PictureLoader: [card:  "Human Token"  set:  "DKA" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Human Token"  set:  "DKA" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Human Token"  set:  "DKA" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Human Token"  set:  "DKA" ]: Trying to load picture
PictureLoader: [card:  "Human Token"  set:  "DKA" ]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_280280"
CardDragItem: coordinate overflow: x = -3.28256 , y = 72.156
CardDragItem: coordinate overflow: x = -25.2625 , y = 48.8448
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 2 cols= 2
reorganizeCards: rows= 2 cols= 2
ZoneViewZone destructor
CardZone destructor:  "rfg"
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 2 cols= 2
reorganizeCards: rows= 2 cols= 2
ZoneViewZone destructor
CardZone destructor:  "rfg"
PictureLoader: cache fail for "_trice_card_back_106150"
CardDragItem: coordinate overflow: x = -34.0815 , y = 43.7328
CardDragItem: coordinate overflow: x = 93.1685 , y = 30.2716
CardDragItem: coordinate overflow: x = 81.1728 , y = 43.0337

_______________________________________________________________________________________

I want to organize my board by dragging permanents into neat groups, but Cockatrice unfortunately has confusing drag & drop behavior. The grid often forces permanents far to the left of where I want to drop them, or else far to the right. The drag & drop grid can be too sticky in terms of forcing groupings of 3 cards, when I merely want to position a permanent next to another group of 1-3 permanent bundles.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Drag and drop some tokens around, such as 1/1 red Elementals.

I'm using macOS, in case that matters.

**Comment by ebbit1q** [comment] 2023-06-21 19:38
sounds like a duplicate of https://github.com/Cockatrice/Cockatrice/issues/4235
does the issue happen in online play?

**Comment by mcandre** [comment] 2023-08-08 03:13
Yes, I also experience #4235, but I consider that a separate issue.

The drag & drop grid feels generally slippery. The location that cards snap to while still holding down the mouse cursor, is *not* the same location that they end up after releasing the mouse.

**Comment by ebbit1q** [comment] 2023-08-08 11:27
I'm not sure I understand your issue then, can you give me more detailed reproduction steps?

have you tried if the beta release solves your issue?

**Comment by mcandre** [comment] 2023-10-22 23:50
Cockatrice is extremely inconsistent about the final landing place of any and all cards and tokens dragged and dropped during games. I don't know how else to say it. It's like if dragging desktop items onto the Trash Can resulted in the items randomly deciding to land next to the Trash Can, but if you try to drag an item next to the Trash Can, then it often ends up inside the Trash Can.

**Comment by ebbit1q** [comment] 2023-10-24 12:38
I understand that's annoying but I can't reproduce your problem on my own machine, I'm not sure how I can work on fixing your issue if I can't determine what causes it.

in the mean time we have released cockatrice 2.9.0, please check if installing the new version resolves your issue.

**Comment by Elarnon** [comment] 2023-12-13 22:39
I am not sure what the original problem being referred to is here, but there is a bug where the `CardDragItem` does not have the right logic for the "modulo 3" piles and hence places cards incorrectly with group selections. For instance here is a group selection before dropping it (bottom cards are actual cards, top cards are "phantom" `DragItems` which could maybe use a bit less opacity):

![Screenshot from 2023-12-13 23-18-11](https://github.com/Cockatrice/Cockatrice/assets/146210/f34154a8-809e-41b1-972b-be6a4ec9999d)

And here is what happens when I drop it (the only difference between the two pictures is that I released the mouse):

![Screenshot from 2023-12-13 23-18-16](https://github.com/Cockatrice/Cockatrice/assets/146210/85c2370e-14e6-4890-9b3c-302d6b2ae9c2)

I wrote a fix for this last year but it was part of a larger patch to migrate the card dragging to the `QDrag` system (it had other problems due living outside the `QGraphics` canvas and I ultimately abandoned it) and is not directly applicable, but I will try to see if I can write a patch to port the relevant changes to the current implementation.

Actually, the fix I had makes the `CardDragItem`s properly show where the cards will end up, but there is another behavior that might be useful which is to move a set of cards while preserving their relative positions (if the space on the board allows). I'd say this would be a separate feature.

IIRC that code also fixed some issues with the way single-card drops are handled (see below -- not sure how it makes sense to place the Elves on top of the Harbinger when the mouse cursor is that far). 
![image](https://github.com/Cockatrice/Cockatrice/assets/146210/1ed169a8-ee87-49c4-9c27-8d8921d5c568)

**Comment by Elarnon** [comment] 2023-12-16 12:51
@mcandre Would you mind checking that #4963 fixes the issues you had with grid placement? You can find a development build at the [bottom of this page](https://github.com/Cockatrice/Cockatrice/actions/runs/7231349349?pr=4963#artifacts) that you should be able to use for testing.

**Closed** 2024-01-01 21:51 UTC
Labels: Bug
