### ISSUE TITLE
Running oracle from inside cockatrice enters first-setup mode

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3264] opened 2018-05-27 13:00 UTC
<b>System Information:</b>
  
Client Version: 2.5.2-custom(494dfc2) (2018-05-25)
Client Operating System: Arch Linux
Build Architecture: 64-bit
Qt Version: 5.11.0
System Locale: en_US
  
__________________________________________________________________________________________

  

  
Attempting to update the card database from inside trice will update the database successfully, but then immediately enter first-setup mode.
If you click yes when prompted to edit set preference, you are presented with a blank set editor, even though cards are still visible in the deck editor behind it.
Hitting ok in the set editor closes the dialog, and then the "updated card database" message appears.
Attempting to manage sets from this point on will again open an empty set editor.

Client log
```
Client Version: 2.5.2-custom(494dfc2) (2018-05-25)
Client Operating System: Arch Linux
Build Architecture: 64-bit
Qt Version: 5.11.0
Empty filename passed to function
Empty filename passed to function
Empty filename passed to function
Theme changed: "Default"
SoundEngine: enabling sound
Sound theme changed: "Default"
SoundEngine: enabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "/home/arch/.local/share/Cockatrice/Cockatrice/cards.xml"
main(): ui.show() finished
cache fail for "_trice_card_back_244260"
Spoiler Service Online
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 14478 Sets= 224
[CockatriceXml3Parser] Trying to parse:  "/home/arch/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 14804 Sets= 224
[CockatriceXml3Parser] Trying to parse:  "/home/arch/.local/share/Cockatrice/Cockatrice/spoiler.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 14929 Sets= 224
[CockatriceXml3Parser] Trying to parse:  "/home/arch/.local/share/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 14932 Sets= 224
CardDatabase::loadCardDatabases success
Data Hash = "\xE2\xC3""E\xF6\x1A\x12\x9D\xA6rB\xFB\x1A\\\"\xE5""7"
File Hash = "\xE2\xC3""E\xF6\x1A\x12\x9D\xA6rB\xFB\x1A\\\"\xE5""7"
Spoilers Up to Date
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "/home/arch/.local/share/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 0 Sets= 0
[CockatriceXml3Parser] Trying to parse:  "/home/arch/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 0 Sets= 0
[CockatriceXml3Parser] Trying to parse:  "/home/arch/.local/share/Cockatrice/Cockatrice/spoiler.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 0 Sets= 0
[CockatriceXml3Parser] Trying to parse:  "/home/arch/.local/share/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 0 Sets= 0
CardDatabase::loadCardDatabases success
```

**Comment by skwerlman** [comment] 2018-05-28 17:50
This also happens on launch if there are new spoilers

**Comment by tooomm** [comment] 2018-05-29 06:56
I can reproduce that on recent builds.
Not happening with 2.5.1 release!

**Comment by tooomm** [comment] 2018-06-17 07:39
@Vafthrudnir The merging of #3283 as a fix of this and another issue didn't close both automatically.
https://help.github.com/articles/closing-issues-using-keywords/#closing-multiple-issues
Looks like you have to repeat the keywords for each issue.

**Closed by tooomm** 2018-06-17 07:39 UTC
Labels: App - Cockatrice, Defect - Regression
