### ISSUE TITLE
missing graphics and unable to load from default deck directory in the ubuntu version

### ISSUE THREAD

**Issue by onecouplequestioned** [Cockatrice/Cockatrice#1941] opened 2016-04-13 20:17 UTC
<b>OS:</b>
Linux Mint 17.3 Rosa 64-bit with the XFCE environment

<b>Cockatrice version:</b>
Version 768a1c5 (2016-04-12)

---

<br>
I realize I'm using the .deb package from the Woogerworks site and not using Ubuntu proper, so maybe that's part of my issue. But for some reason I can't load decks from the normal default deck directory. However, I am able to save my decks to a different directory, such as Documents, and I can load them from there without any problems. Also, graphics are missing from the game UI, like the left side phase buttons. Maybe that's just the stage of development of the ubuntu version? You guys are amazing.

**Comment by Daenyth** [comment] 2016-04-13 20:22
Weird. Can you try compiling it yourself? I valve there are mine instructions on the wiki

**Comment by tooomm** [comment] 2016-04-13 20:25
Do you run Ubuntu or Mint?!

**Comment by onecouplequestioned** [comment] 2016-04-13 21:10
Daenyth, I'll go ahead and try that and see what happens. 

tooomm, I'm using the latest version of Mint, which is Ubuntu and Debian-based.

**Comment by onecouplequestioned** [comment] 2016-04-14 03:25
I tried compiling from source, and it basically gave me the same issue in terms of graphics. I seemed to "solve" the deck directory thing by just changing the default deck directory in the settings.

**Comment by ctrlaltca** [comment] 2016-04-14 06:52
> Also, graphics are missing from the game UI, like the left side phase buttons.

Can you check if your distro provides a separate package for Qt's Svg loading library? Missing that library could be a cause for missing some UI images.
I've found out https://community.linuxmint.com/software/view/libqt5svg5 that seems a good candidate, but i'm not sure about how packages works on Mint and what Qt version you have installed.

**Comment by onecouplequestioned** [comment] 2016-04-14 15:31
ctrlaltca, installing libq5svg5 worked! Thanks  so much!

**Comment by ctrlaltca** [comment] 2016-04-14 17:21
The problem is that out deb package doesn't declare its dependency on the qt-svg library:
```
 Package: cockatrice
 Version: 0.0.1~git20160412.768a1c5
 Section: games
 Priority: optional
 Architecture: amd64
 Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libprotobuf8, libqt5core5a (>= 5.2.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5multimedia5 (>= 5.2.0), libqt5network5 (>= 5.0.2), libqt5printsupport5 (>= 5.0.2), libqt5sql5 (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libstdc++6 (>= 4.4.0), zlib1g (>= 1:1.1.4), libqt5multimedia5-plugins
 Homepage: http://github.com/Cockatrice/Cockatrice
 Installed-Size: 16110
 Maintainer: Gavin Bisesi <Daenyth+github@gmail.com>
 Description: Cockatrice
```

**Comment by onecouplequestioned** [comment] 2016-04-14 20:50
All right. Is there a way to include the lib5svg5 with the normal .deb package? I don't know a whole lot about this stuff.

**Comment by ctrlaltca** [comment] 2016-04-15 15:57
In #1948 i've added libq5svg5 ad a dependency for the cockatrice package, so that the package manager can sort this out automatically for the user.

**Comment by ctrlaltca** [comment] 2016-04-15 16:44
Reopening since there's still an issue left here:

> But for some reason I can't load decks from the normal default deck directory.
> However, I am able to save my decks to a different directory, such as Documents, and I can load them from there without any problems

**Comment by ctrlaltca** [comment] 2016-04-15 16:48
@onecouplequestioned can you follow these instructions:
 * open cockatrice's settings and check what path is defined for the "decks directory"
 * ensure that directory exists (attention: it could be inside a "hidden" directory like /home/user/.local/)
 * check with a text editor if you can edit (open, save) an existing file in that directory and if you can create a new file in that directory

**Comment by tooomm** [comment] 2016-04-15 19:24
Could you uninstall Cockatrice and the libq5svg5 package?
And see what happens if you try to install the new Ubuntu build now... https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/0.0.1~git20160415.11dfee4/view#files/Ubuntu/trusty?

**Comment by onecouplequestioned** [comment] 2016-04-16 01:39
Sorry for the late reply. I uninstalled the old version of Cockatrice and libqt5svg5 and reinstalled Cockatrice and the graphics were working! However, after switching to the default hidden directory it had the same issue as before. So, it seems that it is saving files to it, but the files aren't displaying when I try to save or load them within Cockatrice.. I was able to create and edit files within that folder.

**Comment by onecouplequestioned** [comment] 2016-04-16 01:44
Oddly enough, using a non-hidden folder works for displaying deck files, as I said.

**Comment by ctrlaltca** [comment] 2016-04-17 13:59
> /home/kaww/.local/share/Cockatrice/Cockatrice/decks/

The folder is the default used by Cockatrice, so there's nothing strage in it

> So, it seems that it is saving files to it, but the files aren't displaying when I try to save or load them within Cockatrice

I had half an idea that it could be XFCE trying to "protect" the user from loading files from hidden folders, but i just tested XFCE 4.12 (on slackware-current, sorry, i had no Mint machines available), and it seems to work.

**Comment by onecouplequestioned** [comment] 2016-04-17 15:00
That is odd. At first I thought maybe it was because it was right protected or something, but that's clearly not the case. Hrm.

**Comment by Daenyth** [comment] 2016-06-08 15:53
Are you still having this issue?

**Comment by ctrlaltca** [comment] 2020-03-26 18:51
Closing this issue. Fell free to reopen it if the problem still persists.

**Closed by ctrlaltca** 2020-03-26 18:51 UTC
Labels: OS - Linux, Troubleshooting
