### ISSUE TITLE
pretty print land tapping in log

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2620] opened 2017-04-21 17:40 UTC
When a player marks several cards and taps them at once it looks like this:
>x taps Forest.
x taps Mountain.
x taps Plains.
x taps Mountain.
x taps Mountain.
x plays Heaven // Earth from their hand.

It would be way more cleaner to have it like that:
> x taps Mountain (3)
x taps Plains
x taps Forest

or even:
> x taps 3 Mountain, 1 Forest and 1 Plains

Especially since in many cases it'll be just two colors in limited for example.

<br>
It gets even more confusing when several things happen at the same time or people use mana artifacts or ramp creatures for mana as well and they all tap at the same time:

> x taps Forest.
x taps Naga Vitalist.
x taps Forest.
x taps Mountain.

So the idea would be to basicly group actions which happen simultaneously.
Maybe there are other use cases which could benefit as well, like attacking with several creatures... like many tokens or two times the same creature. Or just to have the simultaneous attack as one line/event in the log.

**Comment by ZeldaZach** [comment] 2017-04-21 19:28
I believe it's handled in a for loop right now, so we can simple tag them together and make it say "X taps card1, card2, card3...". I'll check this out when I get a chance.

**Comment by Daenyth** [comment] 2017-04-21 20:07
This is tricky. Messages come in the log in response to events from the
server, not commands from the client. The events come one card at a time.
You'd need to do some kind of buffering and waiting to bundle items

**Comment by tooomm** [comment] 2017-04-21 20:15
Like waiting 0.5s to see if more (uniform?) events with the same time stamp are coming in?

**Comment by Daenyth** [comment] 2017-04-21 23:15
Yes, but that's a really long time to wait. >0.1seconds is generally perceptible by humans. Probably you'd want to wait maybe 50 milliseconds (0.05s) maximum to do the bundling.

**Comment by Daenyth** [comment] 2017-04-21 23:15
Potentially better would be to just remember the last message you printed and be able to modify it for every incoming message

**Comment by Nightfirecat** [comment] 2017-04-21 23:23
I assume since simultaneous events are sent at the same time by the server that it's reasonably unlikely for the client to receive them with a large gap. If that's the case, a 50ms delay would be plenty.

**Comment by ZeldaZach** [comment] 2020-09-28 20:29
Dupe of #3404 (Yes, i know this is older but that has more info)

**Closed by ZeldaZach** 2020-09-28 20:29 UTC
Labels: App - Cockatrice, Suggestion
