### ISSUE TITLE
Keyboard shortcuts not working after first game

### ISSUE THREAD

**Issue by ahaberski** [Cockatrice/Cockatrice#3477] opened 2018-12-22 00:20 UTC
<b>OS:</b>MacOS 10.14.2 Mojave
Client Version: 2.6.2 (2018-12-20)
Client Operating System: macOS 10.14
Build Architecture: 64-bit
Qt Version: 5.9.3

__________________________________________________________________________________________

Strange problem where keyboard shortcuts stop working if you concede a game and start new one. They will work again if you click outside of the Cockatrice window and back into it. This problem only appeared after upgrading to the latest version.

**Comment by ZeldaZach** [comment] 2018-12-22 00:33
Spreads to all OS. Focus is lost on the program. Need to investigate

**Comment by timlem** [comment] 2019-01-13 04:56
Yes seems to be a focus issue. I can always do one hotkey at beginning of the game and then I can't.

**Comment by tooomm** [comment] 2019-01-13 12:04
Works for me... this is not an issue on Windows, shortcuts keep working after conceding a game.

Client Version: 2.6.2 (2018-12-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: de_DE

What system do you use @timlem?

**Comment by timlem** [comment] 2019-01-14 00:01
Mac OS Mojave 10.14.1 (18B75) @tooomm I have another friend on mac where the hotkeys aren't working. It's like it loses focus on the app or something and I can't do anything to get it back. However the f2 works for concede

**Comment by ZeldaZach** [comment] 2019-01-14 03:04
I'm gonna throw up a beta-release with the fix

**Comment by timlem** [comment] 2019-01-14 14:44
Sweet! Where can I find Beta releases?

**Comment by ZeldaZach** [comment] 2019-01-14 14:45
https://github.com/Cockatrice/Cockatrice/releases/tag/2019-01-13-Development-2.6.2-beta

**Comment by tooomm** [comment] 2019-01-14 16:44
Which pr did fix this?

**Comment by ctrlaltca** [comment] 2019-01-14 16:45
@tooomm on macOS: https://github.com/Cockatrice/Cockatrice/pull/3491

**Comment by tooomm** [comment] 2019-01-14 19:09
Ahh. So this is a duplicate of https://github.com/Cockatrice/Cockatrice/issues/3482 actually! :)

**Comment by tooomm** [comment] 2019-01-21 20:31
Try our newest beta release @ahaberski:
https://github.com/Cockatrice/Cockatrice/releases/tag/2019-01-19-Development-2.6.3-beta.2

And let us know if it works for you!

**Comment by timlem** [comment] 2019-01-21 22:20
Working great! Thanks so much!

**Comment by tooomm** [comment] 2019-01-21 22:32
Awesome, enjoy!
And thanks for reporting in the first place ;)

**Closed by tooomm** 2019-01-21 22:32 UTC
Labels: App - Cockatrice, OS - macOS

**Comment by timlem** [comment] 2019-01-23 17:42
@tooomm - so hotkeys are working and it's awesome! Making my experience so much better. However with the beta I am unable to right click and drag arrows and also cards that get flipped/transformed into another creature are not showing the new creature but the same creature. Should I submit this as a new issue?

**Comment by tooomm** [comment] 2019-01-23 23:03
Can you please file a new issue for that?
Which version was working before? @timlem

**Comment by Legim** [comment] 2019-03-03 16:28
The link for the beta release returns a 404, could you please post a new one?

I'm also having the same issue that @timlem 's friend reported. After updating Cockatrice to 2.6.2, hotkeys stopped working quite often, even when staying in Cockatrice the whole time (aka not alt tabbing = losing focus)

**Comment by tooomm** [comment] 2019-03-04 08:44
Use the updater in the client @Legim 

v2.7.0 is released and out of beta

**Comment by Legim** [comment] 2019-03-04 11:27
Thanks, working perfectly now. :)
