### ISSUE TITLE
Release Deployment Issues

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2685] opened 2017-05-05 18:48 UTC
So when deploying a full release, a few issues come up.

1) The entire body of the release is replaced with "Dev build" and we lose what was there (i kept a backup of it as i knew this was an issue, so i just re-pasted after it was done)
2) The name of the release gets changed to the name of the tag at some point, which causes the file names to be incorrect

The upload order was as follows, with the file names:
- Cockatrice-Trials_of_the_Gods-2.3.17-x86_64_qt5.exe
- Cockatrice-2.3.17.deb
- Cockatrice-20170505Release3217-2.3.17-x86_qt5.exe
- Cockatrice-2.3.17.dmg

We need to figure out how to prevent this from happening and adding the correct name of the release to the files. 

In other news, the in client updater works for both channels, so no issues there 👍

**Comment by Daenyth** [comment] 2017-05-05 21:25
Pretty sure the "Dev build" thing is by appveyor

**Comment by ZeldaZach** [comment] 2017-06-03 17:44
@Daenyth Probably, but can you or @ctrlaltca look into this in the near future?

**Comment by tooomm** [comment] 2018-01-30 22:32
Duplicate of https://github.com/Cockatrice/Cockatrice/issues/2921, solved in https://github.com/Cockatrice/Cockatrice/pull/2976

**Closed by tooomm** 2018-01-30 22:32 UTC
Labels: Cleanup, Defect - Basic
