### ISSUE TITLE
Change number of players in a game on the fly from within game lobby

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4303] opened 2021-04-07 03:49 UTC
We have a multiplayer group.  People come and go.  If we had four players one game, then one leaves, it'd be nice not to have to all get into a new room.  Instead somehow the game owner could edit the lobby and then start the next game with three.

**Comment by ebbit1q** [comment] 2021-04-07 11:35
duplicate of https://github.com/Cockatrice/Cockatrice/issues/434

**Closed by ebbit1q** 2021-04-07 11:35 UTC
Labels: Feature Request
