### ISSUE TITLE
Error in message log

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1083] opened 2015-05-18 17:10 UTC
Few players have mentioned the following:
- top card of deck is revealed.
- diabolic tutor is used
- stop revealing top card
- search for card and move to hand
- log will say "player moved x to hand" where x was the top card revealed.

**Comment by ZeldaZach** [comment] 2020-11-03 21:29
Dupe of #3276, #1983

**Closed by ZeldaZach** 2020-11-03 21:29 UTC
Labels: App - Cockatrice, Defect - Game Rules Compliance
