### ISSUE TITLE
Improve desktop notifications for privacy

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1401] opened 2015-08-22 05:49 UTC
Some of us do not have privacy when we are on here. We may have a buddy or co-worker walk by and then we get a i little box on the bottom of our screen because some troll called us out in pm " You suck you douche bag"  now not only do we have to deal with that moron but our co-worker, buddy, Boss even thins we are goofing off (we are but still) and are a dick online. I think we should have the option for a tone (sound) to play when we are mentioned in the main chat and maybe even a different one for when we are P.med.  If not permanent have a box in settings that says "Please check one"   Tone for mention or the old "Zedladzack mentioned you" . Then have another option for the Pms.

**Comment by ZeldaZach** [comment] 2015-08-22 05:55
I'm going to try and interpret the wall:

- You'd like customizable sounds to be played when you
 * Receive a mention
 * Receive a PM
- Have the ability to turn off desktop notifications
 * Because you're getting yelled at by a boss because you're messing around while you should be working

(This would be configurable to be on/off based on a setting preference)

_____

Responding to this, I'd be fine with extending the sound engine into the notification alert tabs, maybe have default sounds for "Private Message", "Mention", and "Staff Alert".

Other opinions on this are greatly appreciated.

**Comment by poixen** [comment] 2015-08-22 06:01
I already created an issue about this. It said that you should not see the content of the message in the popup.

**Comment by radioactivehazards** [comment] 2015-08-22 06:01
yes, you told me to post here Zach so I did. I personally am not getting yelled at but I can imagine others may, i had a friend walk i and had to explain to him why i was being yelled at.

**Comment by tooomm** [comment] 2015-08-22 09:22
Someone please change the title of this issue.
<br>

---
I'm sure Zach was just kidding... ;)

**Comment by Daenyth** [comment] 2015-08-22 10:37
This is a dupe of #1403 and #1273 respectively.

**Closed by Daenyth** 2015-08-22 10:37 UTC
