### ISSUE TITLE
in game bug

### ISSUE THREAD

**Issue by LestatTheDarkPrince** [Cockatrice/Cockatrice#1363] opened 2015-08-11 03:38 UTC
i do not have the ability or the know how to post a screen shot on this so ill describe best I can.  Is there a way to fix the play field in game?   what i mean is you are only allow to have 3 cards on top of each other at a time....you can "attach" infinite numbers but i want to know is there a way we can kill the 3 cards on top of each limit?

**Comment by Nightfirecat** [comment] 2015-08-11 05:42
Are you saying that there only being able to be 3 cards stacked upon each other is a bug?
It's expected behavior. Is there a good reason it should change?

**Comment by LestatTheDarkPrince** [comment] 2015-08-11 06:51
well, this may be just me then but when i build new decks it often helps to be able to lay out all the cards and sort them into CMC and curve values. I also use a 1 player game when i draft to lay my library so i have a full view of all my outs. I also use the M.L service and they have a very crappy sealed deck builder and having the ability to lay out all my cards really helps.

**Comment by Daenyth** [comment] 2015-08-11 10:15
I don't see this changing any time soon.

**Comment by ZeldaZach** [comment] 2015-08-11 14:40
This isn't a bug and it seems fine to me... Dae sees the same thing I do, so I'ma close this for now

**Closed by ZeldaZach** 2015-08-11 14:40 UTC

**Comment by LestatTheDarkPrince** [comment] 2015-08-11 15:14
just continue to fix/ confuse the deck editor menu which really seems pointless.......when offered a building suggestion...dismiss that.  Just saying it seems like every time i update i see things that make Zero sense why they would be changed. i figure maybe ill add to the pointless changes. if you cannot fix this then maybe offer a better building system.

**Comment by ZeldaZach** [comment] 2015-08-11 15:16
If you really think it's that big of an issue, you're free to open a PR and we will gladly review it

**Comment by tooomm** [comment] 2015-08-11 15:26
Would it help if it's 4 instead of 3? Because mostly it's a maximum of 4 copies of one card in the deck.
This would mess around with the layout of lands, too. Don't know if it would be any better overall.

**Comment by LestatTheDarkPrince** [comment] 2015-08-11 15:54
pr? is there really so many steps in addressing things? we had a woogerworks forum, that died and became this git-hub thing.  I say thing because its just a mess. Changing it to 4 would be cool. Also i do know why but i have never been able to us the "different colored" arrows... is something wrong with them?  can we make those easier to use? About the deck editor. How about this...this is a proposal here.  Have another option under deck builder *Layout* where it would take you to a table that had Unlimited ability to view cards. This tool would vastly improve mana bases, help players color sort and understand their decks better.

**Comment by ZeldaZach** [comment] 2015-08-11 15:57
> Also i do know why but i have never been able to us the "different colored" arrows... is something wrong with them? can we make those easier to use?

When drawing your arrow, hold the following key(s) to make the different colors:

+ Shift &rarr; Green
+ Alt &rarr; Blue
+ Control/Command &rarr; Yellow

____

> About the deck editor. How about this...this is a proposal here. Have another option under deck builder Layout where it would take you to a table that had Unlimited ability to view cards.

What do you mean by this exactly? Also, this seems to be another issue, so if you'd like to open another ticket on it please feel free to.

**Comment by woogerboy21** [comment] 2015-08-11 15:58
@LestatTheDarkPrince I think your confused on how things operate.  Github is a source code repository.  Woogerworks is a site that operates a server.  They are mutually exclusive.

**Comment by tooomm** [comment] 2015-08-11 16:06
>About the deck editor. How about this...this is a proposal here. Have another option under deck builder Layout where it would take you to a table that had Unlimited ability to view cards. **This tool would vastly improve mana bases, help players color sort and understand their decks better.** 

Have you tried using the included analyze deck option which gives you some statistics?
I like using it for that particular thing, but sure it's different than you might be used to from offline play and laying out cards there.
But hey, it's not bad for that reason and offers more information btw. ;)

`Deck editor` --> `Analyze deck on deckstats.net`

**Comment by LestatTheDarkPrince** [comment] 2015-08-11 16:08
@ZeldaZach the layout is the original post that started this topic... I have noticed many changes to the "deck editor" section recently.....most of which make zero sense are i see as useless.  but i think if we had a way to change the layout to a "table" builder instead of a "list" builder it would make for better players.  Maybe we could have an option, even in the "settings area" that allowed us to have a in my eyes "More interactive deck builder" this builder would allow us to build our deck sby laying cards out over a table (like the game area) This feature would basically make the library of cards you library nd when you move cards to the deck (main area of table) it would calculate stuff like mana curve, creature to spell ratio. land ratio even.    Tom, i have seen no analyze deck option.  Maybe its just me but i find that when i lay out a deck instead of list it out i understand what the deck can do better and it helps me become a better pilot of it.  I do this often with all my constructed deck on here including edh.

**Comment by tooomm** [comment] 2015-08-11 16:12
>Tom, i have seen no analyze deck option.

![analyze](https://cloud.githubusercontent.com/assets/9874850/9202892/4d3f4328-4054-11e5-8757-c8dc7a02a6a2.png)

**Comment by LestatTheDarkPrince** [comment] 2015-08-11 16:15
can we make one that works offline........i rarely build decks online as thats just not a ability i have.  like to sit at home and relax while i deck build. Also yes there is a deck analyzer there it not even close to what i was suggesting. they do their layout in the same "lists" form

**Comment by tooomm** [comment] 2015-08-11 16:42
My intention was not to give you an adequate possibility to what you suggested. Just pointing out what you don't know about the client yet...

<br>
I kinda like your idea, but
- 1. It should be in its own issue
- 2. It sounds very complex and is more like a deck builder and analyzer application, than a feature for a card game playing client. I just use Cockatrice for playing and copy lists in here or make small modifications at most, serious building is done with real cards or at other online services.<br>
Always good to have good stuff packed together, though -  if reasonable.
