### ISSUE TITLE
Conceding in a local game can make other players unable to concede.

### ISSUE THREAD

**Issue by Hystings** [Cockatrice/Cockatrice#4683] opened 2022-10-10 00:04 UTC
**System Information:**

Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
_______________________________________________________________________________________

In a 3 player or more local/goldfish game, you can concede on player 1 to remove player 1 from the game.
After doing this, attempting to concede on any other player gives this message.
![image](https://user-images.githubusercontent.com/18449232/194785528-61a7ad20-5fbb-4f47-8247-4efc66d56cd6.png)
In addition, clicking Yes here does absolutely nothing.

_______________________________________________________________________________________

**Steps to reproduce:**
start 3 player local game
load 3 decks, any deck to start the game
concede (f2) on player 1
attempt to concede on either player 2 or 3

**Comment by ebbit1q** [comment] 2022-10-10 01:09
it seems like player 1 contains some of the controlling parts that become inactive once it is deleted, deleting player 2 has no effect on either player 1 or 3, but deleting player 1 causes conceding to become impossible no matter the player count

**Comment by ebbit1q** [comment] 2022-10-14 19:28
closing as duplicate of https://github.com/Cockatrice/Cockatrice/issues/4399

**Closed by ebbit1q** 2022-10-14 19:28 UTC
Labels: App - Cockatrice, Defect - Game Rules Compliance, Bug, Medium Priority
