### ISSUE TITLE
Permanents that enter tapped doesn't enter tapped anymore

### ISSUE THREAD

**Issue by xChikyx** [Cockatrice/Cockatrice#5150] opened 2024-10-27 01:55 UTC
Permanents used to enter tapped if they normally enter tapped (a guildgate for example) But now they don't.

**Comment by tooomm** [comment] 2024-10-27 14:52
Thanks for coming here and making us aware. That's not much information to work with though. The bug template is there for a reason 😃

Which version of Cockatrice are you running?
Which OS are you running?
It helps to see some logs.

Also, when did it work last time?
What did (you) change since? Did you update your PC, Cockatrice version or card database in between?

**Comment by xChikyx** [comment] 2024-10-27 18:56
I was going to copy the info, but it read like just the info of an ungoing solo game I was "playing", so I didn't paste it here... 

I updated to the lastest version, but the problem still persists, and talking with some people online they said they have the same issue. 

As for when.... Can't really tell, but it's been months, It just stopped working from one day to the other, probably after a new set was introduced, but I can't tell which...

Running windows 10, 64x

On another  topic, thanks for fixing the placement of tokens... The only issue missing to check is if playing solo with mutiple decks still gets the player 1 quit/lose and then others can do it as well... But I'll open a new issue if it does...

**Comment by xChikyx** [comment] 2024-10-27 21:03
Client Version: 2.9.0 (2023-09-14)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.2
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "None "
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Unable to load qt translation "qt_" at "C:/Program Files/Cockatrice/Resources/translations"
Unable to load "cockatrice" translation "cockatrice_" at "C:/Program Files/Cockatrice/translations"
main(): starting main program
In C:/Program Files/Cockatrice/plugins/imageformats/qicns.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/plugins/imageformats/qtga.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/plugins/imageformats/qtiff.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/plugins/imageformats/qwbmp.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/plugins/imageformats/qwebp.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/Plugins/imageformats/qicns.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/Plugins/imageformats/qtga.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/Plugins/imageformats/qtiff.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/Plugins/imageformats/qwbmp.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
In C:/Program Files/Cockatrice/Plugins/imageformats/qwebp.dll:
  Plugin uses incompatible Qt library (5.12.0) [release]
main(): MainWindow constructor finished
PictureLoader: cache fail for "_trice_card_back_4951332"
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
PictureLoader: cache fail for "_trice_card_back_4951328"
Spoiler Service Online
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
Data Hash = "\x94\x88\xFB\xF7""a/w%\xFF\xE1\xE9\xE9""8\xD3\xC1""2"
File Hash = "\x94\x88\xFB\xF7""a/w%\xFF\xE1\xE9\xE9""8\xD3\xC1""2"
Spoilers Up to Date
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 30839 Sets = 776 "1630ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 31721 Sets = 776 "45ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 31722 Sets = 779 "5ms"
Loading Custom Set 0 ( "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Chiky/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 31722 Sets = 779 "6ms"
CardDatabase::loadCardDatabases success

**Comment by ebbit1q** [comment] 2024-10-27 21:29
duplicate of #5093 please check old tickets first before opening new ones

**Closed by ebbit1q** 2024-10-27 21:29 UTC
Labels: Bug
