### ISSUE TITLE
'Hidden Agenda' Conspiracy cards

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2142] opened 2016-08-23 22:32 UTC
The Conspiracy sets have a card type Conspiracy, and a subset of those cards have the mechanic 'Hidden Agenda'.

Hidden Agenda states: "Start the game with this conspiracy face down in the command zone and secretly name a card. You may turn this conspiracy face up any time and reveal the chosen name."

Players would need a way to carry hidden information that is immutable and can be revealed.  Face-down object that has its information stored and it's noted in log if it changes or is just unchangeable without destroying/recreating the object.

There are also other possible uses for this face-down-information card.  There's a game mode called Kingdom which distributes basic lands which only the owning player should ever able to see, but certain actions in Cockatrice can interfere with this.

Also could allow for functionality in non-mtg games.

**Comment by Jinxstands4Jinx** [comment] 2016-08-24 17:23
Kingdoms can put load their deck with sideboard open and switch the deck into the board and the 6 lands into the main...shuffle up then deal them out while hilding shift. This keeps them face down and no one knows what is what until they peek. Once done. the host can open Sideboard and move their entire deck to the table (while holding Shift) and it will go face down and No one will see those cards. Then move the cards to the library..shuffle up and Game on!  For conspiracy I am not sure the issue is that big of a concern as I doubt people care enough.

**Comment by skwerlman** [comment] 2016-08-24 18:38
The issue is not about hiding cards, but rather a place to keep secret, unchangeable text (such as the card name you secretly chose)

**Comment by Daenyth** [comment] 2016-08-25 14:47
I believe I saw someone suggest we approach this by adding the ability to create a token face-down with text on it, and then when it's flipped face up, the text can be revealed to all players. I think that's a solid approach, and is very general and would apply to other things (goblin game etc)

**Comment by Daenyth** [comment] 2016-08-25 14:49
I think the next step on this is for someone to check the server/client code related to that and see if it would be possible without changing the protocol. 

If we can't do this without a protocol change that puts us in an awkward position. We have to choose between either another forced update (which users *despise* or allowing that there will be games on the server that some users cannot see all actions for.

**Comment by ZeldaZach** [comment] 2016-08-29 03:57
This seems like a brutal thing. We managed to avoid it for the initial run of Conspiracy... If we can't do this easily, I'm fine with the "trust" factor that my opponent won't be a douche and change around his text to try and win a random game. In tournaments, they can PC a judge or something to validate? Hidden text would be great and I'll see  what I can find about it.

**Comment by ZeldaZach** [comment] 2020-10-06 22:36
Dupe of #3278 (We're working backwards, so that's our tracking ticket now)

**Closed by ZeldaZach** 2020-10-06 22:36 UTC
Labels: Suggestion
