### ISSUE TITLE
Mana cost filter no longer working correctly

### ISSUE THREAD

**Issue by pilgrimsleet** [Cockatrice/Cockatrice#3318] opened 2018-07-09 14:10 UTC
<b>System Information:</b>
  

  

Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
__________________________________________________________________________________________
When filtering by mana cost, the filter is now "greedy."  For instance, if I filter by "Mana Cost AND G" it now shows cards that cost G, 1G, 1GG, 2G, etc.

**Comment by ZeldaZach** [comment] 2018-07-09 22:00
I find that to be correct... what should it be instead?

**Comment by Daenyth** [comment] 2018-07-09 22:12
It should be `=` since we have no `contains` operator

**Comment by ZeldaZach** [comment] 2020-09-28 20:49
Dupe of #3730

**Closed by ZeldaZach** 2020-09-28 20:49 UTC
Labels: App - Cockatrice, Defect - Regression
