### ISSUE TITLE
Why Cant I Save My Decks Without Cockatrice Crashing???

### ISSUE THREAD

**Issue by deatheater900** [Cockatrice/Cockatrice#2143] opened 2016-08-24 07:24 UTC
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

___
<br>

*Explain your Issue/Request/Suggestion in detail here!*

**Comment by ctrlaltca** [comment] 2016-08-24 07:29
Fill the fields with the information required and explain your problem in detail, so that we can understand what's going on and assist you in fixing the problem.

**Comment by ZeldaZach** [comment] 2016-08-29 04:04
@Daenyth I'm closing this b/c the user has failed to update and it's not helpful in anyway. I didn't find this an issue on mac or windows at the time with current version.

**Closed by ZeldaZach** 2016-08-29 04:04 UTC
Labels: Troubleshooting

**Comment by Daenyth** [comment] 2016-08-29 13:40
Fair enough; @deatheater900 please reopen this issue with additional information if it's still a problem for you. As it stands we can't reproduce this and we don't have enough information to make any changes.
