### ISSUE TITLE
Image download fallback ignores lower-priority sets

### ISSUE THREAD

**Issue by alvaro-cuesta** [Cockatrice/Cockatrice#1554] opened 2015-09-22 16:10 UTC
When cards are missing multiverseid in the topmost set, the rest of the sets for that card are ignored, triggering a download and storing the fallback image in the topmost set folder.

E.g.: *Vengevine* is currently downloaded to `/pWCQ/Vengevine.jpg` even though `/ROE/Vengevine.jpg` is present. Even worse, the downloaded image is actually the one from ROE, so the image is classified under the wrong set folder.

I think this issue is what triggers #1543 as @Daenyth commented there. #1545 suggests disabling promo sets but IMHO it's just a hack while this would fix the real issue.

**Build:** Windows 7 x64 ead6ab3

**How I think it should work:**

- Try the topmost set.
- If missing, try the next set (and so on, until an image is found or all sets are consumed).
- If none of the sets have an image available, only then try the fallback URL. Store the fallback image **in its own folder** (perhaps `/pics/downloadedPics/FALLBACK/`).

It's important that fallback images be stored separately so they're classified under their real set code (or actually, no set code) in case the real cards are ever available.

**Comment by Daenyth** [comment] 2015-09-22 17:19
Correct behavior:

Try most preferred set HQ, then LQ, then next set HQ, LQ, and so on. The first correctly found image should be saved in the set folder for the set it was downloaded from.

**Comment by ZeldaZach** [comment] 2015-10-01 18:16
Dupe of #1545

**Closed by ZeldaZach** 2015-10-01 18:16 UTC
Labels: App - Cockatrice, Defect - Basic
