### ISSUE TITLE
[WARNING] Entire filesystem can be deleted by local reply "delete" button

### ISSUE THREAD

**Issue by Kazor259** [Cockatrice/Cockatrice#2852] opened 2017-09-16 15:09 UTC
<b>OS:</b>
macOS 10.12.5(16f73)
<b>Cockatrice version:</b>
version 2.3.17(2017-05-05)
__________

when i went to download a replay of EDH match it said it couldn't download so i thought there were something wrong on my replay files so i decided to try to delete what ever on it long and behold it and it started to delete stuff of the replay file after about a minute of waiting i decided to force close it to stop it from deleting whatever was on my replay file but when i check my desktop to reopen cockatrice all of folder were gone deleted wiped from my hard drive i tried to restart my computer thinking it a bug but no i have about 5 time restarting my computer but no everything was gone so dear to the at cockatrice please help me .

**Comment by Daenyth** [comment] 2017-09-16 20:21
I'm really unsure of a could cause this. Especially on osx, your user account would not have permission to delete system files, so that sounds very strange. Do you mean that it deleted your user files? It might be possible but I've never heard of that happening to anyone, and as far as I'm aware that code has not changed in several years. We'll have to look into the code and see how anything like that could be possible.

Can you be more specific about exactly which buttons you hit in the UI? I'm having a hard time understanding exactly what you did.

If the application did delete your files, I'm very sorry about that. If that's the case I'm afraid it's unlikely to be reversible. 

Are you able to open system applications? Which files exactly are missing from what locations? You say everything but if it was everything your computer wouldn't start, and as I mentioned, your user account wouldn't have permissions to delete the system files

**Comment by Kazor259** [comment] 2017-09-16 20:29
basically everything on my desktop it all gone 
i press the red X

**Comment by Daenyth** [comment] 2017-09-17 01:46
The red x on the left side of the replays tab?

Hmm..

```
void TabReplays::actDeleteLocalReplay()
{
    QModelIndex curLeft = localDirView->selectionModel()->currentIndex();
    if (QMessageBox::warning(this, tr("Delete local file"), tr("Are you sure you want to delete \"%1\"?").arg(localDirModel->fileName(curLeft)), QMessageBox::Yes | QMessageBox::No) != QMessageBox::Yes)
        return;
    
    localDirModel->remove(curLeft);
}
```

According to http://doc.qt.io/qt-5/qfilesystemmodel.html#remove it should just remove the one file from the left side that you had selected. I don't understand how it could delete everything.

I don't know what's going on here.

**Comment by tooomm** [comment] 2017-09-17 10:12
That sounds highly unlikely...

But yes, I have also a tough time following and understand what you actually did exactly.

**Comment by ctrlaltca** [comment] 2017-09-22 15:45
Closing. Please reopen if you have more information on the issue (and punctuation)

**Comment by ValerioBellaveglia** [comment] 2020-11-12 20:55
This just happened to me too. I had just downloaded the app, went in the "deck storage" section. Under "local file system" box there are a few buttons. Having no deck on my pc (i never created one, it was just a fresh app installation) i clicked on the red arrow to delete i don't know what. I don't know why my insane mind made me do that cause it had no point, but on the "Delete local file" alert i agreed to the "Are you sure you want to delete ""?" message. I'd like to underline the fact that it's asking me wether to delete an empty string file, so only god knows (i don't think devs do atm) what algorithm the deleting process followed. I only can imagine it deleted something like "the first file of every folder" or something like that, since the index of the file was 0/empty/whatever. By now, i am writing from a pc containing 10% of the content. My manjaro partition is destroyed, i have no documents, no config files. Everything is empty and gone but a bunch of useless leftovers. I think many files from the OS installation are gone as well cause i remember my Manjaro OS installation not being so primitive. I am attaching a screenshot just to let you see and have an idea of the impact of the issue.

I am hoping this is fixed right away so nobody falls for this biblically huge bug. I am forced to format my partition and start over installing the OS from zero, cause that would actually mean recovering 30% of the OS: yes, right now formatting and reinstalling means recovering, not deleting.

Shame on me for the dumb mistake of trying to delete something that was not there, but so much more shame on the devs for not finding (or let's say not really trying to find?) a bug that was already issued more than 3 years ago.

I have no words left.

![Istantanea_2020-11-12_21-49-08](https://user-images.githubusercontent.com/42283211/98995124-2e93de80-2531-11eb-893e-97ec4eca0460.png)

**Comment by ebbit1q** [comment] 2020-11-12 21:59
Our sincere apologies, as a developer you can never prevent all bugs from reaching your users. Thank you for bringing this issue back to our attention. We hope you can recover as many files as possible (one recommendation I'd give is the program ext4magic) or from backups you might have.

**Comment by ctrlaltca** [comment] 2020-11-13 07:30
As long as cockatrice offers the ability to delete a folder, somebody will be able to wipe his data by using it.
We could check if the folder is not empty, "/" or "c:\", but just choosing any directory like "c:\windows" or "/usr" will lead to the same result.
We could try to limit the chosen folder to be inside the cockatrice profile directory to limit the damage, but this will break the current ability to store different decks/games in an user-chosen path, and still can be troublesome for cockatrice data.
Or we could just remove the delete function, and discard the problem.

@ValerioBellaveglia mi spiace molto per i tuoi file, I hope you have a recent backup.
Tbh, I'm unsure how the entire filesystem can be deleted by cokatrice, unless it's running as root (because you were not running cockatrice as root, right?). I guess configs being deleted from the user directory is what caused most of the problems.

**Comment by Daenyth** [comment] 2020-11-13 15:15
It seems reasonable to not allow deleting folders. Cockatrice doesn't need to be a file manager

**Comment by Daenyth** [comment] 2020-11-13 15:16
I'd go as far as also allowing users to delete only file types (or extensions, on windows) that cockatrice is aware of

**Comment by ebbit1q** [comment] 2020-11-13 16:15
reproduced, as I expected it deletes a user's home contents but nothing more

**Closed** 2020-11-13 19:55 UTC
Labels: App - Cockatrice, Bug, Defect - Basic, High Priority, OS - Linux, OS - macOS

**Comment by catthou** [comment] 2021-01-02 07:26
cockatrive.github.io is still recommending people download a version that can delete their entire home folder. Same with the 'releases' on the side bar.

**Comment by tooomm** [comment] 2021-01-02 13:11
@catthou that is correct. There has been no official stable release of a version with this fix included yet.
That's why this thread is still pinned at the top of the issue list for people to find it more easily.

You have to use the most recent [beta release](https://github.com/Cockatrice/Cockatrice#download-) in order to not run into this issue.

But the new version will probably be released soon. Our webpage will then link to that version as well of course.

**Comment by MotherofRuins** [comment] 2021-01-25 00:00
Users drop random stuff all over their filesystems over time.  They download to the wrong folder, or have a hand spam using Windows Explorer.  The Undo in explorer is hard to find if you don't know about it.  Is it possible people accidentally dropped some kind of softlinks, or hardlinks, or shortcuts in the saved game folders and then the program followed those links?

**Comment by ebbit1q** [comment] 2021-01-25 01:52
no, this is a different problem caused by the default location being the home folder, resulting in the default location being deleted whenever "nothing" is deleted. this problem has now been resolved since https://github.com/Cockatrice/Cockatrice/commit/68074b0f74dd672097c76cf2e4dbd312634b2a01 which still is not included in a mainline release.
