### ISSUE TITLE
Add more filters for game list in rooms

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2431] opened 2017-03-01 21:18 UTC
Currently you can filter rooms by everything except Age and Spectator Rights. It'd be nice if those were available too.  
I've never once filtered rooms by creator name, description or player count, nor will I ever need to, but I'd love it if I could filter out games that don't allow spectators (especially when looking for rooms to spectate) and games where the host is presumably afk (~30+min).  Other people might want to filter out games where specs can see hands in fear of cheating or filter by time even more restrictively to only see fresh rooms. 
To throw in a suggestion of specific implementation:  
Spec Rights:  4 tickboxes (show "specs banned" games / show "specs allowed" games / show "specs can chat" games / show "specs can see everything" games).  
Age: same as the current player count filter, just for time in minutes in place of headcount.

**Comment by tooomm** [comment] 2017-03-01 23:17
linking https://github.com/Cockatrice/Cockatrice/issues/388

**Comment by knitknit** [comment] 2020-10-01 00:49
Age filtering will be added in #4092 . Is there any appetite for spectator-based filtering? If so, are the 4 options

> Spec Rights: 4 tickboxes (show "specs banned" games / show "specs allowed" games / show "specs can chat" games / show "specs can see everything" games).

the ones we want to move forward with? If so I can take a look.

**Comment by ebbit1q** [comment] 2020-10-01 12:35
this sounds more like a combobox than a series of checkboxes

**Comment by knitknit** [comment] 2020-10-03 22:54
Fair enough! I'm happy to tinker, feel free to assign to me.

**Comment by tooomm** [comment] 2020-10-06 15:02
As https://github.com/Cockatrice/Cockatrice/issues/2642 got closed as a dupe of this, I want to mention that it has some additional filter ideas/requests in addition to the spectator filters asked for here.

Maybe they are still useful.

**Comment by knitknit** [comment] 2020-10-07 00:06
Thanks! So it seems like the main takeaway from #2642 is to consider breaking up "available" as:

```
not full games --> "Show games with places left"
full games --> "Show full games"
with pw --> "Show games with password protection"
buddy only --> "Show buddy only games"
allow spec --> "Show games that allow spectators"
games for reg only --> "Show games for registered users only"
games for unreg only --> "Show games for unregistered users"
```

That seems reasonable, I never had a great sense of what "available" meant without looking at the code. @ZeldaZach @ebbit1q , thoughts?

**Closed** 2020-10-27 19:49 UTC
Labels: App - Cockatrice, Good first issue, Medium Priority, UI / UX
