### ISSUE TITLE
Bigger image size on the older Cockatrice client Version ca60a46

### ISSUE THREAD

**Issue by raouldouglas** [Cockatrice/Cockatrice#1730] opened 2015-12-29 18:20 UTC
Hello,
Thanks for your work on the Cockatrice clients.
This troubles me on the newest client.
The size off the picture on the right side of the screen is smaller than it was on the older client (ca60a46), that I already own, but is no longer supported by the servers.

Here are two pictures to compare the sizes.

Older version

![image 2015-12-29 a 19 08 32](https://cloud.githubusercontent.com/assets/16477944/12039411/7d6a8344-ae60-11e5-882b-45f70188d8f9.png)

New version

![image 2015-12-29 a 19 09 21](https://cloud.githubusercontent.com/assets/16477944/12039416/8909bbde-ae60-11e5-8e3b-802540314257.png)

On the newest Client (Version d55e44e), the size is not ajustable to make the picture as wide as on the older client.
Could you ajust this option in order to have a bigger image on the new version ? It is way more confortable for playing on wide screens.

Thank you by advance for your involvement to resolve this issue.

**Comment by tooomm** [comment] 2015-12-29 18:33
This might be affected/solved by https://github.com/Cockatrice/Cockatrice/pull/1544

**Comment by tooomm** [comment] 2016-01-11 15:13
@raouldouglas Please test this version and report back if that's helping you:
https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/0.0.1~git20160111.5350302/view#files

**Comment by raouldouglas** [comment] 2016-01-11 15:57
Just tried it, and the software is quitting quitting when I try to open it.

![image 2016-01-11 a 16 53 56](https://cloud.githubusercontent.com/assets/16477944/12238442/52414800-b884-11e5-9906-58c9ed1ea406.png)

**Comment by ZeldaZach** [comment] 2016-01-11 16:01
Can you troubleshoot that? Look on the troubleshooting section as it's very easy on Mac

**Comment by Daenyth** [comment] 2016-01-11 16:03
You should also be able to open the "report" button (I think you want Signaler?), and if it includes a bunch of technical looking text, post it to gist.github.com and link that page on here. It will help us solve the issue.

**Comment by tooomm** [comment] 2016-01-11 16:07
The feature is not released yet and under review at the moment, see #1753.
It's working for me on windows though. The finished version should exactly address your issue. 

If you can help troubleshooting this we should be able to fix the problem you run into on mac faster.

**Comment by raouldouglas** [comment] 2016-01-11 16:12
Here is the "Troubleshouting / Signaler" box report.

Process:         launchd [7049]
Path:            /Applications/Cockatrice/cockatrice.app/Contents/MacOS/cockatrice
Identifier:      com.cockatrice.cockatrice
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [130]

Date/Time:       2016-01-11 17:08:53.272 +0100
OS Version:      Mac OS X 10.7.5 (11G63b)
Report Version:  9

Interval Since Last Report:          3105397 sec
Crashes Since Last Report:           172
Per-App Crashes Since Last Report:   21
Anonymous UUID:                      D12EB925-8BD7-4949-98B4-E81A3FD83C69

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 1

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 8590
    thread_create: 1
    thread_set_state: 0

Model: Macmini5,2, BootROM MM51.0077.B10, 2 processors, Intel Core i7, 2.7 GHz, 8 GB, SMC 1.75f0
Graphics: AMD Radeon HD 6630M, AMD Radeon HD 6630M, PCIe, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533643465238432D48392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80AD, 0x484D54333531533643465238432D48392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xE4), Broadcom BCM43xx 1.0 (5.106.198.19.22)
Bluetooth: Version 4.0.8f17, 2 service, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE SSD TS256C, 251 GB
Serial ATA Device: APPLE HDD HTS727575A9E362, 750,16 GB
USB Device: hub_device, 0x0424  (SMSC), 0x2513, 0xfa100000 / 2
USB Device: Keyboard Hub, apple_vendor_id, 0x1006, 0xfa120000 / 5
USB Device: Apple Optical USB Mouse, apple_vendor_id, 0x0304, 0xfa123000 / 7
USB Device: Apple Keyboard, apple_vendor_id, 0x0250, 0xfa122000 / 6
USB Device: BRCM20702 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0xfa110000 / 3
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8281, 0xfa113000 / 4
USB Device: hub_device, 0x0424  (SMSC), 0x2513, 0xfd100000 / 2

**Comment by ctrlaltca** [comment] 2016-01-11 17:10
Looks more like a generic problem of running travis-compiled builds than a specific problem due to #1753. Old builds were compiled by @woogerboy21 on OSX 10.6 iirc, while travis compiles on 10.9.5.

**Comment by ctrlaltca** [comment] 2016-01-28 22:12
#1753 has been merged, so this issue should have been addressed aswell.
We need to provide the user an Osx 10.7 compatible package of the new build.

**Comment by tooomm** [comment] 2016-03-08 14:59
Somebody can do that for the last full release aka Gatewatchers? @woogerboy21 maybe?
We could upload it to Bintray then as well.

**Comment by Daenyth** [comment] 2016-03-09 13:34
I'm OK with a team member uploading a manual build to bintray. I can adjust permissions for it if needed.

**Comment by raouldouglas** [comment] 2016-04-13 07:44
Hello guys !
Just coming back for news, to know if a new stable version built compatible package for Mac OSX 10.7 Lion has been released.

Thanks by advance !

**Comment by tooomm** [comment] 2016-04-13 07:55
You're running an OS that's "unsupported as of about October 2014" and which doesn't get security updates therefore. ([source](https://en.wikipedia.org/wiki/Mac_OS_X_Lion))
Is there a reason why you not just upgrade to a secure OS?

**Comment by raouldouglas** [comment] 2016-04-13 08:03
Always played on Cockatrice on this OS. Updating takes computer ressources and diskspace. OSX 10.7 has been made for my mac mini. It's running well, and when I want to update, it's always the risk the machine is in pain with the new OS version.
My version of cockatrice Version d55e44e (2015-09-23) is running well. I've just this problem of the image size. I did'nt thing it was this difficult to fix that regard to the last message that have been posted. That's why I came back to ask if it has been fix since my last message. ^_^

**Comment by Daenyth** [comment] 2016-04-13 13:19
@raouldouglas We don't support OSX 10.7 any more. That being said, you should be able to [compile it yourself using the instructions on the wiki](https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#compiling-with-homebrew)

Specifically, this should more or less be the full process;

```bash
brew install qt5 cmake protobuf git
git clone git://github.com/Cockatrice/Cockatrice
cd Cockatrice
mkdir build
cd build
QT5_DIR=$(brew info --installed qt5 | grep "^$(brew --cellar qt5)" | cut -d' ' -f1)
cmake .. -DWITH_SERVER=0 -DWITH_CLIENT=1 -DCMAKE_PREFIX_PATH=$QT5_DIR/
make -j
make package
open *.dmg
```

**Comment by ctrlaltca** [comment] 2016-04-13 13:23
The problem is to get homebrew working on 10.7, since you it needs and old version of Xcode and Apple removed links to old versions.

**Comment by ctrlaltca** [comment] 2016-07-01 13:24
Closing as: we're not able to provide a build working on OSX < 10.9 anymore due restrictions imposed by Apple.

**Closed by ctrlaltca** 2016-07-01 13:24 UTC
Labels: App - Cockatrice, UI / UX
