### ISSUE TITLE
Counterclockwise "Tapping" option

### ISSUE THREAD

**Issue by IttaloXD** [Cockatrice/Cockatrice#1743] opened 2016-01-04 20:01 UTC
Hi, as you all know, cockatrice isn't used only to test and play with decks for Magic The Gathering, lots of databases and the versatility of the program let us play other games like yu-gi-oh and more. I'm Brazilian and play the Marvel Battle Scenes TCG, but the TAP counterclockwise are also needed to play the game. Do you thing it's possible to put this option on the next update for the program?
I spoke with Mr. Collins and he said that it is possible, and I should put this sugestion here.

**Comment by Daenyth** [comment] 2016-01-04 20:14
Do you want a cosmetic change (cards appear ccw rotated instead of cw) or are you looking for a new card state (card is untapped, card is tapped, card is ccw-tapped)?

**Comment by tooomm** [comment] 2016-01-04 20:28
Is it needed to distinguish between `tapped` and `tapped counterclockwise` for your use case?
Do you use both types of tapped in the game at the same time, e.g. some are tapped right and others are tapped left?

**Comment by Daenyth** [comment] 2016-01-04 20:30
> Do you use both types of tapped in the game at the same time, e.g. some are tapped right and others are tapped left?

That's what I was getting at.

**Comment by radioactivehazards** [comment] 2016-01-06 01:25
I would love to find a Ascension group. Maybe make seperate chat-rooms for each game

**Comment by IttaloXD** [comment] 2016-01-07 21:35
Yes, it is needed to distinguish between tapped and tapped counterclockwise, some card are tapped right and others are tapped left all the time in the game. Some cards will be on the stage 0 of capacity (incapacitated), some cards will be on the stage 1, and some ones on the stage 2. 

![Iron Man](http://www.battlescenes.com.br/assets/BATTLE_BOX_008.png)

**Comment by Daenyth** [comment] 2016-01-08 11:02
OK. That's a much bigger feature. I'll have to think about the best way to represent it in the protocol. Even once it's implemented I don't expect to add a game action for it yet. Though maybe we could hide it by default and with a setting show it.

**Comment by Daenyth** [comment] 2016-01-08 11:04
@radioactivehazards Not going to happen any time soon; Cockatrice doesn't have a concept of a shared deck. It'll happen eventually, but there's a lot of work needed to support it.

**Comment by IttaloXD** [comment] 2016-01-08 18:52
@Daenyth There's no problem if the option comes hidden by defalt, if it exists, will be a great thing!

**Comment by ebbit1q** [comment] 2020-10-09 22:38
dupe of #3094

**Closed by ebbit1q** 2020-10-09 22:38 UTC
Labels: App - Protocol / API, Suggestion
