### ISSUE TITLE
Random P/T Setting

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2332] opened 2017-01-01 23:00 UTC
<b>OS: macOS 10.12.2</b>

<b>Cockatrice version: f7c8651 (2016-12-30)</b>

___
<br>

I don't know how this happens and I've been unable to create it. Had a clue token in play put a creature on the stack, then the clue token somehow has the p/t of the creature. Nothing showed up in the game log where the p/t was set. Happened twice early in this game.

https://www.dropbox.com/s/cfvd54xqzm5abt3/replay_3874.cor?dl=0

**Comment by Daenyth** [comment] 2017-01-23 00:53
Was it via related card or similar feature?

**Comment by ZeldaZach** [comment] 2017-01-23 20:31
I took a look at the replay and it just _randomly_ happened. I didn't see anything that should have caused that result in the chat log nor game... Maybe this is a protocol failure between the server/client?

**Comment by Daenyth** [comment] 2017-01-24 15:55
Could be. Make a python script to parse the .cor file into a list of
protocol items? It's basically a big array of game event messages

**Comment by ctrlaltca** [comment] 2017-04-25 16:09
Here's the replay log, cleaned of unuseful stuff:
```
"[Event_SetActivePlayer.ext] { active_player_id: 0 }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"player_id: 1 [Event_RollDie.ext] { sides: 20 value: 12 }"
"player_id: 1 [Event_Shuffle.ext] { zone_name: \"deck\" }"
"player_id: 1 [Event_Shuffle.ext] { zone_name: \"deck\" }"
"player_id: 0 [Event_GameSay.ext] { message: \"glhf\" }"
"player_id: 0 [Event_RollDie.ext] { sides: 20 value: 1 }"
"player_id: 0 [Event_Shuffle.ext] { }"
"player_id: 0 [Event_DrawCards.ext] { number: 7 cards { id: 42 name: \"Spirebluff Canal\" } cards { id: 5 name: \"Concealed Courtyard\" } cards { id: 52 name: \"Toolcraft Exemplar\" } cards { id: 54 name: \"Unlicensed Disintegration\" } cards { id: 2 name: \"Aether Hub\" } cards { id: 48 name: \"Thraben Inspector\" } cards { id: 35 name: \"Scrapheap Scrounger\" } }"
"player_id: 1 [Event_GameSay.ext] { message: \"same!\" }"
"player_id: 1 [Event_Shuffle.ext] { zone_name: \"deck\" }"
"player_id: 1 [Event_Shuffle.ext] { zone_name: \"deck\" }"
"player_id: 1 [Event_Shuffle.ext] { zone_name: \"deck\" }"
"player_id: 1 [Event_Shuffle.ext] { }"
"player_id: 1 [Event_DrawCards.ext] { number: 7 cards { id: 31 name: \"Plains\" } cards { id: 11 name: \"Spell Queller\" } cards { id: 24 name: \"Island\" } cards { id: 52 name: \"Always Watching\" } cards { id: 8 name: \"Spell Queller\" } cards { id: 28 name: \"Plains\" } cards { id: 38 name: \"Port Town\" } }"
"player_id: 0 [Event_GameSay.ext] { message: \"kp\" }"
"player_id: 1 [Event_GameSay.ext] { message: \"kp\" }"
"player_id: 1 [Event_MoveCard.ext] { card_id: 38 card_name: \"Port Town\" start_player_id: 1 start_zone: \"hand\" position: -1 target_player_id: 1 target_zone: \"table\" x: 0 y: 2 new_card_id: 38 face_down: false }"
QString::arg: Argument missing: "cchichy puts <i><a href=\"card://Port Town\">Port Town</a></i> into play from their hand." , 0
"player_id: 1 [Event_MoveCard.ext] { card_id: 31 card_name: \"Plains\" start_player_id: 1 start_zone: \"hand\" position: -1 target_player_id: 1 target_zone: \"table\" x: 6 y: 2 new_card_id: 31 face_down: false }"
QString::arg: Argument missing: "cchichy puts <i><a href=\"card://Plains\">Plains</a></i> into play from their hand." , 6
"player_id: 1 [Event_MoveCard.ext] { card_id: 31 card_name: \"Plains\" start_player_id: 1 start_zone: \"table\" position: -1 target_player_id: 1 target_zone: \"hand\" x: 0 y: 0 new_card_id: 31 face_down: false }"
QString::arg: Argument missing: "cchichy moves <i><a href=\"card://Plains\">Plains</a></i> from play to their hand." , 0
"[Event_SetActivePlayer.ext] { active_player_id: 1 }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"[Event_SetActivePhase.ext] { phase: 10 }"
"[Event_SetActivePlayer.ext] { active_player_id: 0 }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"[Event_SetActivePhase.ext] { phase: 2 }"
"player_id: 0 [Event_DrawCards.ext] { number: 1 cards { id: 9 name: \"Cultivator\\'s Caravan\" } }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 5 card_name: \"Concealed Courtyard\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 target_zone: \"table\" x: 0 y: 2 new_card_id: 5 face_down: false }"
QString::arg: Argument missing: "Jinete_del_Viento puts <i><a href=\"card://Concealed Courtyard\">Concealed Courtyard</a></i> into play from their hand." , 0
"player_id: 0 [Event_MoveCard.ext] { card_id: 52 card_name: \"Toolcraft Exemplar\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 target_zone: \"table\" x: 0 y: 0 new_card_id: 52 face_down: false }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 52 attribute: AttrPT attr_value: \"1/1\" }"
QString::arg: Argument missing: "Jinete_del_Viento puts <i><a href=\"card://Toolcraft Exemplar\">Toolcraft Exemplar</a></i> into play from their hand." , 0
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 5 attribute: AttrTapped attr_value: \"1\" }"
"[Event_SetActivePhase.ext] { phase: 10 }"
"[Event_SetActivePlayer.ext] { active_player_id: 1 }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"player_id: 1 [Event_SetCardAttr.ext] { zone_name: \"table\" attribute: AttrTapped attr_value: \"0\" }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"[Event_SetActivePhase.ext] { phase: 1 }"
"[Event_SetActivePhase.ext] { phase: 2 }"
"player_id: 1 [Event_DrawCards.ext] { number: 1 cards { id: 53 name: \"Stasis Snare\" } }"
"player_id: 1 [Event_MoveCard.ext] { card_id: 31 card_name: \"Plains\" start_player_id: 1 start_zone: \"hand\" position: -1 target_player_id: 1 target_zone: \"table\" x: 3 y: 2 new_card_id: 31 face_down: false }"
QString::arg: Argument missing: "cchichy puts <i><a href=\"card://Plains\">Plains</a></i> into play from their hand." , 3
"[Event_SetActivePhase.ext] { phase: 10 }"
"[Event_SetActivePlayer.ext] { active_player_id: 0 }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" attribute: AttrTapped attr_value: \"0\" }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"[Event_SetActivePhase.ext] { phase: 2 }"
"player_id: 0 [Event_DrawCards.ext] { number: 1 cards { id: 27 name: \"Mountain\" } }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 48 card_name: \"Thraben Inspector\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 target_zone: \"stack\" x: 0 y: 0 new_card_id: 48 face_down: false }"
QString::arg: Argument missing: "Jinete_del_Viento plays <i><a href=\"card://Thraben Inspector\">Thraben Inspector</a></i> from their hand." , 0
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 5 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 1 [Event_SetCounter.ext] { counter_id: 0 value: 19 }"
"player_id: 1 [Event_SetCounter.ext] { counter_id: 0 value: 18 }"
"player_id: 1 [Event_SetCounter.ext] { counter_id: 0 value: 17 }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 48 card_name: \"Thraben Inspector\" start_player_id: 0 start_zone: \"stack\" position: -1 target_player_id: 0 target_zone: \"table\" x: 3 y: 0 new_card_id: 48 face_down: false }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 48 attribute: AttrPT attr_value: \"1/2\" }"
QString::arg: Argument missing: "Jinete_del_Viento puts <i><a href=\"card://Thraben Inspector\">Thraben Inspector</a></i> into play from the stack." , 3
"player_id: 0 [Event_CreateToken.ext] { zone_name: \"table\" card_id: 75 card_name: \"Clue\" color: \"\" pt: \"\" annotation: \"\" destroy_on_zone_change: true x: 0 y: 1 }"
"[Event_SetActivePhase.ext] { phase: 5 }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 52 attribute: AttrTapped attr_value: \"1\" }"
"[Event_SetActivePhase.ext] { phase: 9 }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 42 card_name: \"Spirebluff Canal\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 target_zone: \"table\" x: 3 y: 2 new_card_id: 42 face_down: false }"
QString::arg: Argument missing: "Jinete_del_Viento puts <i><a href=\"card://Spirebluff Canal\">Spirebluff Canal</a></i> into play from their hand." , 3
"[Event_SetActivePhase.ext] { phase: 10 }"
"[Event_SetActivePlayer.ext] { active_player_id: 1 }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"player_id: 1 [Event_SetCardAttr.ext] { zone_name: \"table\" attribute: AttrTapped attr_value: \"0\" }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 2 card_name: \"Aether Hub\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 x: 0 y: 0 new_card_id: 2 face_down: false }"
"[Event_SetActivePhase.ext] { phase: 1 }"
"[Event_SetActivePhase.ext] { phase: 2 }"
"player_id: 1 [Event_DrawCards.ext] { number: 1 cards { id: 29 name: \"Plains\" } }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 27 card_name: \"Mountain\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 x: 1 y: 0 new_card_id: 27 face_down: false }"
"player_id: 1 [Event_MoveCard.ext] { card_id: 24 card_name: \"Island\" start_player_id: 1 start_zone: \"hand\" position: -1 target_player_id: 1 target_zone: \"table\" x: 6 y: 2 new_card_id: 24 face_down: false }"
QString::arg: Argument missing: "cchichy puts <i><a href=\"card://Island\">Island</a></i> into play from their hand." , 6
"[Event_SetActivePhase.ext] { phase: 10 }"
"[Event_SetActivePlayer.ext] { active_player_id: 0 }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" attribute: AttrTapped attr_value: \"0\" }"
"[Event_SetActivePhase.ext] { phase: 0 }"
"[Event_SetActivePhase.ext] { phase: 2 }"
"player_id: 0 [Event_DrawCards.ext] { number: 1 cards { id: 44 name: \"Spirebluff Canal\" } }"
"[Event_SetActivePhase.ext] { phase: 4 }"
"[Event_SetActivePhase.ext] { phase: 5 }"
"player_id: 1 [Event_SetCounter.ext] { counter_id: 0 value: 16 }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 48 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 52 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 1 [Event_SetCounter.ext] { counter_id: 0 value: 15 }"
"player_id: 1 [Event_SetCounter.ext] { counter_id: 0 value: 14 }"
"player_id: 1 [Event_SetCounter.ext] { counter_id: 0 value: 13 }"
"[Event_SetActivePhase.ext] { phase: 9 }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 44 card_name: \"Spirebluff Canal\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 target_zone: \"table\" x: 4 y: 2 new_card_id: 44 face_down: false }"
QString::arg: Argument missing: "Jinete_del_Viento puts <i><a href=\"card://Spirebluff Canal\">Spirebluff Canal</a></i> into play from their hand." , 4
"player_id: 0 [Event_MoveCard.ext] { card_id: 9 card_name: \"Cultivator\\'s Caravan\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 x: 4 y: 0 new_card_id: 9 face_down: false }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 35 card_name: \"Scrapheap Scrounger\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 x: 1 y: 0 new_card_id: 35 face_down: false }"
"player_id: 0 [Event_MoveCard.ext] { card_id: 9 card_name: \"Cultivator\\'s Caravan\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 target_zone: \"stack\" x: 0 y: 0 new_card_id: 9 face_down: false }"
QString::arg: Argument missing: "Jinete_del_Viento plays <i><a href=\"card://Cultivator's Caravan\">Cultivator's Caravan</a></i> from their hand." , 0
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 42 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 5 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 44 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 1 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 38 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 1 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 31 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 1 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 24 attribute: AttrTapped attr_value: \"1\" }"
"player_id: 1 [Event_MoveCard.ext] { card_id: 8 card_name: \"Spell Queller\" start_player_id: 1 start_zone: \"hand\" position: -1 target_player_id: 1 target_zone: \"table\" x: 0 y: 0 new_card_id: 8 face_down: false }"
"player_id: 1 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 8 attribute: AttrPT attr_value: \"2/3\" }"
QString::arg: Argument missing: "cchichy puts <i><a href=\"card://Spell Queller\">Spell Queller</a></i> into play from their hand." , 0
"player_id: 0 [Event_MoveCard.ext] { card_id: 9 card_name: \"Cultivator\\'s Caravan\" start_player_id: 0 start_zone: \"stack\" position: -1 target_player_id: 1 target_zone: \"table\" x: 1 y: 0 new_card_id: 75 face_down: false }"
"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 75 attribute: AttrPT attr_value: \"5/5\" }"
```

Looks like the "Clue" token entered the table with a card id of 75:
`"player_id: 0 [Event_CreateToken.ext] { zone_name: \"table\" card_id: 75 card_name: \"Clue\" color: \"\" pt: \"\" annotation: \"\" destroy_on_zone_change: true x: 0 y: 1 }"`

"Cultivator's Caravan" entered the table with a card id of 9:
"player_id: 0 [Event_MoveCard.ext] { card_id: 9 card_name: \"Cultivator\\'s Caravan\" start_player_id: 0 start_zone: \"hand\" position: -1 target_player_id: 0 x: 4 y: 0 new_card_id: 9 face_down: false }"

When "Cultivator's Caravan" was moved under the control of the opponent, it was assigned a new card id of.. 75:
`"player_id: 0 [Event_MoveCard.ext] { card_id: 9 card_name: \"Cultivator\\'s Caravan\" start_player_id: 0 start_zone: \"stack\" position: -1 target_player_id: 1 target_zone: \"table\" x: 1 y: 0 new_card_id: 75 face_down: false }"
`

The next message sets pt 5/5 to the card with id 75:
`"player_id: 0 [Event_SetCardAttr.ext] { zone_name: \"table\" card_id: 75 attribute: AttrPT attr_value: \"5/5\" }"`

**Comment by ctrlaltca** [comment] 2017-04-25 16:38
After some investigation, the problem is due to the fact that the card changed owner while being put in play on the table.
When a card is moved to a public zone, the server sends informations about its attributes, in this case its PT; the information is sent as [player id, zone, card id, attributes]. If the card changed player during the move, the information is still sent with the old player id, causing the problem.

If no card with the specified card id exists on the table of the "old" player, the event is discarded and cockatrice outputs a "Player::eventSetCardAttr: card id=xx not found" debug message.
If by chance the "old" player has a card on the table with the same card id, then the attribute is assigned to the wrong card.

**Comment by ZeldaZach** [comment] 2017-04-25 16:43
Sounds like we'll need to do a better job at handling unique card IDs when in a game.

**Comment by ctrlaltca** [comment] 2017-04-25 17:11
Mismerge, reopening

**Comment by ctrlaltca** [comment] 2017-04-25 17:40
Gosh reopen

**Closed** 2017-04-29 10:21 UTC
Labels: App - Cockatrice, Defect - Basic
