### ISSUE TITLE
Game replays: Skipping ahead with the replay timeline instead causes it to skip to the very end of the replay without updating the replay.

### ISSUE THREAD

**Issue by Dalenacio** [Cockatrice/Cockatrice#4708] opened 2022-11-17 22:39 UTC
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9

_______________________________________________________________________________________
When using the "Game Replays" feature, trying to skip ahead on the Replay Timeline does not work properly. Trying to skip to a point within the first 10-ish minutes of the game works fine, however, anything later than that, and the replay will get bounced straight to the end (the replay bar will fill green but the board state will not change accordingly)

This means that the only way to skip to a specific point in a replay, beyond the very start of the match, is to sit through the whole thing until it gets to the relevant part. Even trying to jump back a few seconds to an already viewed section within the "unsafe" zone will cause the bug.

_______________________________________________________________________________________
**Steps to reproduce:**
 - Open a game replay.
 - Try to skip to a point after the relative start of the game using the Replay Timeline.

Overview of the "problematic area" of the replay timeline:
![image](https://user-images.githubusercontent.com/12587061/202574324-1f6ccead-f1a6-476d-9894-ab1d33855295.png)

Clicking a random point within the "safe" area:
![image](https://user-images.githubusercontent.com/12587061/202574420-ca1d9c1f-ed95-42de-8a4f-c2fe6d02a9e2.png)

Clicking any point within the "unsafe" area:
![image](https://user-images.githubusercontent.com/12587061/202574479-c064ace3-fd98-4755-8729-61cb1ee1cb61.png)

**Comment by ebbit1q** [comment] 2022-11-18 00:05
duplicate of https://github.com/Cockatrice/Cockatrice/issues/3941 fixed by https://github.com/Cockatrice/Cockatrice/pull/4519 please install the beta version to help test our latest version

**Closed by ebbit1q** 2022-11-18 00:05 UTC
Labels: Bug
