### ISSUE TITLE
how can i install a 32bit version of cockatrice? unable to do it 

### ISSUE THREAD

**Issue by msi1289** [Cockatrice/Cockatrice#3169] opened 2018-04-05 08:37 UTC
<b>System Information:</b>
   

_________________________________________________________________________________

**Comment by ctrlaltca** [comment] 2018-04-05 08:39
If you go to the "releases" page: https://github.com/Cockatrice/Cockatrice/releases
you'll see that a `-win32.exe` is still available. It requires Windows 7, anyway.

**Comment by msi1289** [comment] 2018-04-05 08:42
thanks but i install the last version,the 2/3/18 release but it doesn't finish the install process

**Comment by ctrlaltca** [comment] 2018-04-05 08:52
If you have a problem, please explain it. Eg. if you receive an error, report it here or attach a screenshot.

**Comment by msi1289** [comment] 2018-04-05 09:16
okay so i logged in to the server and cocka told me that some items were missing
the message was this: recover password button missing,to solve push help-update cockatrice.
everytime i try to update the client crashes.So i unistalled the program,downloaded the 32bit version released on 2/03/18 but is impossible to finish the installing process.
Any suggest for me? thanks in advance for your kindness.

**Comment by tooomm** [comment] 2018-04-05 10:56
The installation process includes the needed vcredist packages in recent versions.
Installing them takes a while and you might think the installation freezes. Try giving it some minutes and let it finish without closing the installer manually.

**Comment by msi1289** [comment] 2018-04-05 11:09
thanks for the suggest,so better to wait a while.so the release of 02/03/18 it's ok right? thanks a lot

**Comment by msi1289** [comment] 2018-04-05 11:59
ok thanks a lot,i'll try again later and let u know.Cheers

**Comment by msi1289** [comment] 2018-04-06 12:04
![img_0693](https://user-images.githubusercontent.com/38098284/38420168-31680d06-39a3-11e8-8c30-a84974f764d2.JPG)
So that's the problem,i left it install for 3 hours and the result is the one on the screenshot.this is the only version i'm not able tp install but all the others require me to update the version

**Comment by ctrlaltca** [comment] 2018-04-06 12:27
Can you please try to download and run vc_redist.x86.exe from
https://support.microsoft.com/en-sg/help/2977003/the-latest-supported-visual-c-downloads ?
The version you want is:
![schermata 2018-04-06 alle 14 26 34](https://user-images.githubusercontent.com/1631111/38421193-9f54c7a2-39a6-11e8-84d2-acef0245bf78.png)

After installing the vcredist package, please try to install again cockatrice.

**Comment by ctrlaltca** [comment] 2018-04-06 12:29
Sounds like a duplicate of #3125
@Cockatrice/developers, do we want to remove the `/quiet` switch from the vcredist installation so that users can see if there's any problem?

**Comment by msi1289** [comment] 2018-04-06 13:03
Guyssss solved!!! thanks thanks a lot for your help,have a nice weekend!

**Comment by tooomm** [comment] 2018-04-06 15:06
That are good news, thanks for letting us know @msi1289 👍 

@ctrlaltca I triggered a build with no `\quiet` option for testing: https://ci.appveyor.com/project/Daenyth/cockatrice/build/2.4.1-branch-tooomm-loud-build-957
Will give it a try to see what it changes exactly.

**Comment by tooomm** [comment] 2018-04-06 15:32
The result is that one sees this dialog to repair or uninstall the package, which is also not what we want. I'm sure a lot of users would be confused by that and in the end that is exactly the opposite of what we want. :)
![redist-no-quiet](https://user-images.githubusercontent.com/9874850/38429964-3d9db16c-39c0-11e8-8e6e-668eca95e12b.png)

Only for the first time when it's actually installed it might be a better user experience...

**Comment by ctrlaltca** [comment] 2018-04-06 15:40
There should be a `/passive` option that is halfway between normal and quiet, showing a progressbar only:
![schermata 2018-04-06 alle 17 39 44](https://user-images.githubusercontent.com/1631111/38430438-919cd634-39c1-11e8-924d-e1b6683cd370.png)

**Comment by tooomm** [comment] 2018-04-07 04:43
@ctrlaltca check with `/passive`:
https://ci.appveyor.com/project/Daenyth/cockatrice/build/2.4.1-branch-tooomm-loud-build-960

It pops up a dialog which immediately closes again if it's already installed...
Otherwise it'll show you a dialog with the install progress which automatically closes after it's done.
In @msi1289's case he probably would have seen some kind of error there without the need to check some logs which are placed in the TEMP folder regarding your last screen.

If you like the passive option and think it's an improvement i'll put up a PR! 👍

**Closed** 2018-04-07 16:32 UTC
