### ISSUE TITLE
Add search in replay list

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1430] opened 2015-08-27 20:18 UTC
Can we put a "search user" function in the replay area? I sometimes have a hard time remembering people who i played against and it would help to see Certain games over without having to scour the list trying to find 1.

**Comment by Daenyth** [comment] 2015-08-27 23:16
That's a great idea

**Comment by tooomm** [comment] 2019-08-05 08:26
Such a "filter" could be handy not only for `Game replays`, but in the `Deck storage` tab as well.

**Comment by ZeldaZach** [comment] 2020-10-23 20:09
Dupe of #1526

**Closed by ZeldaZach** 2020-10-23 20:09 UTC
Labels: App - Cockatrice, Suggestion
