### ISSUE TITLE
No way of choosing a card from opponent's library secretly.

### ISSUE THREAD

**Issue by Xelsia** [Cockatrice/Cockatrice#1271] opened 2015-07-17 18:17 UTC
Impossible to resolve Praetor's Grasp without revealing hidden information.

**Comment by ZeldaZach** [comment] 2015-07-17 21:42
Dupe of #788.

Thanks for bringing this up again. I'm sure we'll look into this soon!

**Closed by ZeldaZach** 2015-07-17 21:42 UTC
