### ISSUE TITLE
Feature: Start game that is not full

### ISSUE THREAD

**Issue by sbheinric** [Cockatrice/Cockatrice#3277] opened 2018-06-10 14:34 UTC
When playing commander I prefer to have 4 players, but it can take too long to wait.  For this reason myself and many others will only create 3 player games.

I would prefer if I could make a 4 player game, and then if we find ourselves waiting too long for a 4th player, have the option of being able to start the game with only 3 players if people get antsy, without needing to ask everyone to rejoin a new room.

This feature could be supported by simply adding a "start game" button next to the existing "ready to play" button

**Comment by Daenyth** [comment] 2018-06-10 19:29
I think there's a more general ticket about changing game lobby settings,
which would allow this by changing the player limit

**Comment by ctrlaltca** [comment] 2019-02-08 17:02
Closing as a duplicate of #434

**Closed by ctrlaltca** 2019-02-08 17:02 UTC
