### ISSUE TITLE
Choose single Card Printing

### ISSUE THREAD

**Issue by ArtemisGraphic** [Cockatrice/Cockatrice#3929] opened 2020-03-25 09:26 UTC
Would it be possible to add a selector for each card in a deck where the user can choose their favorite printing for that specific card? I know it's possible to order set priority, but that's awkard and unreliable. Also, it does not give me the chance to show my version of the card to my opponent. Let's say I play legacy merfolk, I really want to see judge promo Chalice of the Void, but I don't want the judge Lord of Atlantis, this is not possible at the time. I'd also like to show my opponent my version of chalice, like in real life, where player can express themselves with a particular version of a card. If my opponent is using mirrodin Chalice, it's ok if I see that version (like in MTGO. I don't know how hard it would be to implement, but I think this is a basic and natural function, as in real life one is free to choose wich version of a card to use and show.

**Comment by ZeldaZach** [comment] 2020-09-27 21:33
This is a dupe of #217 but I do want to look into that

**Closed by ZeldaZach** 2020-09-27 21:33 UTC
Labels: Feature Request
