### ISSUE TITLE
Initial Filter settings

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1660] opened 2015-10-26 06:45 UTC
With the 9/23 version when first installed it sets peoples filters for games with a maximum of 1 player, which hides all the games from them. Many people are just confused at this and end up asking the chat 'wtf'.

**Comment by Nightfirecat** [comment] 2015-10-26 07:01
Dupe of #1476, I think.

**Closed** 2015-10-26 12:03 UTC
