### ISSUE TITLE
Sprouting Renewal image is french (or something)

### ISSUE THREAD

**Issue by aculver** [Cockatrice/Cockatrice#3400] opened 2018-09-28 23:47 UTC
<b>System Information:</b>
  

  
__________________________________________________________________________________________

**Comment by Daenyth** [comment] 2018-09-29 00:04
This might just be a gatherer bug. @ZeldaZach ?

**Comment by aculver** [comment] 2018-09-29 00:54
The image was English a couple days ago.

**Comment by skwerlman** [comment] 2018-09-29 01:12
this might be a dupe of #3263 since it got reprinted in GRN

**Comment by Daenyth** [comment] 2018-09-29 11:35
Specifically the debug output from the session where you downloaded the image

**Comment by ctrlaltca** [comment] 2019-01-27 16:32
Looks like it's working correctly now.

**Closed by ctrlaltca** 2019-01-27 16:32 UTC
