### ISSUE TITLE
Format filter error: Birds of Paradise, Modern

### ISSUE THREAD

**Issue by liyangwu** [Cockatrice/Cockatrice#4832] opened 2023-07-21 18:14 UTC
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: de_DE
Install Mode: Portable
---------------------------------------------------------------------------
Portable mode enabled
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "D:/Programme/Cockatrice/data/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
QWindowsWindow::setGeometry: Unable to set geometry 3440x1370+0+23 (frame: 3456x1409-8-8) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 3440x1369+0+23 (frame: 3456x1408-8-8) margins: 8, 31, 8, 8 minimum size: 1234x1370 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=1250,1409 maxtrack=0,0)
PictureLoader: cache fail for "_trice_card_back_401575"
[CardDatabase] loadCardDatabase(): Path = "D:/Programme/Cockatrice/data/cards.xml" Status = 0 Cards = 27289 Sets= 715
[CockatriceXml4Parser] Trying to parse:  "D:/Programme/Cockatrice/data/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "D:/Programme/Cockatrice/data/tokens.xml" Status = 0 Cards = 28001 Sets= 715
[CardDatabase] loadCardDatabase(): Path = "D:/Programme/Cockatrice/data/spoiler.xml" Status = 4 Cards = 28001 Sets= 715
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "Little Girl"  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "Little Girl"  set:  "UNH" ]: Picture found on disk.
PictureLoader: [card:  "Trash Bin"  set:  "UNF" ]: Trying to load picture
PictureLoader: [card:  "Trash Bin"  set:  "UNF" ]: Picture found on disk.
PictureLoader: [card:  "Bottomless Vault"  set:  "5ED" ]: Trying to load picture
PictureLoader: [card:  "Bottomless Vault"  set:  "5ED" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Bottomless Vault"  set:  "5ED" ]: Trying to download picture from url: "https://api.scryfall.com/cards/c8913994-c3e7-4d9e-9409-a8409ce68442?format=image&face=front"
PictureLoader: [card:  "Bottomless Vault"  set:  "5ED" ]: following redirect: "https://cards.scryfall.io/large/front/c/8/c8913994-c3e7-4d9e-9409-a8409ce68442.jpg?1562594227"
PictureLoader: [card:  "Boreal Shelf"  set:  "CSP" ]: Trying to load picture
PictureLoader: [card:  "Boreal Shelf"  set:  "CSP" ]: Picture found on disk.
PictureLoader: [card:  "Borderland Explorer"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Borderland Explorer"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Borderland Explorer"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Borderland Explorer"  set:  "MB1" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Bottomless Vault"  set:  "5ED" ]: Image successfully downloaded from  "https://cards.scryfall.io/large/front/c/8/c8913994-c3e7-4d9e-9409-a8409ce68442.jpg?1562594227"
PictureLoader: [card:  "Borderland Explorer"  set:  "MB1" ]: Trying to download picture from url: "https://api.scryfall.com/cards/aebc9aeb-3b98-4cfa-a2b5-44e424eceeb0?format=image&face=front"
PictureLoader: [card:  "Borderland Explorer"  set:  "MB1" ]: following redirect: "https://cards.scryfall.io/large/front/a/e/aebc9aeb-3b98-4cfa-a2b5-44e424eceeb0.jpg?1573513201"
PictureLoader: [card:  "Borderland Explorer"  set:  "MB1" ]: Image successfully downloaded from  "https://cards.scryfall.io/large/front/a/e/aebc9aeb-3b98-4cfa-a2b5-44e424eceeb0.jpg?1573513201"
PictureLoader: [card:  "Kabira Crossroads"  set:  "C17" ]: Trying to load picture
PictureLoader: [card:  "Kabira Crossroads"  set:  "C17" ]: Picture found on disk.
PictureLoader: [card:  "Birds of Paradise Avatar"  set:  "PMOA" ]: Trying to load picture
PictureLoader: [card:  "Birds of Paradise Avatar"  set:  "PMOA" ]: Picture found on disk.

_______________________________________________________________________________________

For some reason, the card "Birds of Paradise" is not recognized as a Modern legal card. See screenshots.

![image](https://github.com/Cockatrice/Cockatrice/assets/27956693/907966b9-7e47-42fa-b84a-04c1a1e84323)
![image](https://github.com/Cockatrice/Cockatrice/assets/27956693/41fbb649-80cb-424c-966c-06bf5d6bc624)

I haven't found other examples yet.
I rely on Cockatrice to check if a card is Modern legal. Would be great if this gets fixed.
_______________________________________________________________________________________

**Steps to reproduce:**
Type "Birds of Paradise" into the "Serach by card namne". -> Birds of Paradise sould be visible in the result list.
Filter for "Format=Modern" -> Now Birds of Paradise disapears from the result list.

Both steps can be done in reverse order with the same result.

**Comment by ebbit1q** [comment] 2023-07-22 21:04
duplicate of https://github.com/Cockatrice/Cockatrice/issues/4783
please add to existing tickets instead of starting new ones

**Closed by ebbit1q** 2023-07-22 21:04 UTC
Labels: Bug
