### ISSUE TITLE
Revelation

### ISSUE THREAD

**Issue by Marco-Wolf-original** [Cockatrice/Cockatrice#5050] opened 2024-06-12 01:19 UTC
**System Information:**

_______________________________________________________________________________________

When using cards like revelation the revealed hands don't refresh automatically as if the hands were revealed at all times

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment] 2024-06-12 11:49
this is intentional, you will need to show your hand every time it changes or play with your hand on the battlefield instead

**Comment by ebbit1q** [comment] 2024-12-03 22:45
duplicate of https://github.com/Cockatrice/Cockatrice/issues/3295

**Closed by ebbit1q** 2024-12-03 22:45 UTC
Labels: Bug
