### ISSUE TITLE
debug build fails on fresh ubuntu 18.04 install

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3431] opened 2018-11-07 03:12 UTC
<b>System Information:</b>
Ubuntu 18.04 x64
Qt 5.9.5
gcc 7.3.0
cmake 3.10.2
protobuf-compiler 3.0.0-9.1
building from master
__________________________________________________________________________________________

Building fails on the generated protobuf source files at a warning (due to the -Werror flag) when using the debug build with `-DCMAKE_BUILD_TYPE=Debug`.
We can't fix this inside the source files because they are generated by the protobuf compiler instead.
Setting -Wno-error=unused-parameter -Wno-error=misleading-indentation fixes this, but these errors are preferred to trigger on normal source files.

The first generated error is as follows, there is about a hundred similar ones:
```
/Cockatrice/build/common/pb/admin_commands.pb.cc: In member function 'virtual google::protobuf::uint8* AdminCommand::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const':
/Cockatrice/build/common/pb/admin_commands.pb.cc:367:10: error: unused parameter 'deterministic' [-Werror=unused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
```

**Comment by ctrlaltca** [comment] 2018-11-07 07:12
duplicate of #2343

**Closed** 2018-11-09 10:05 UTC
