### ISSUE TITLE
[GalliumOS] Difficulty installing Cockatrice

### ISSUE THREAD

**Issue by welbinator** [Cockatrice/Cockatrice#1806] opened 2016-02-11 16:19 UTC
when I try to install the .deb file I get this error in the Ubuntu software center:

Dependency is not satisfiable libprotobuf8

**Comment by ctrlaltca** [comment] 2016-02-11 16:31
Knowing ay least the name of the package you're trying to install and the version of ubuntu you are using could help a bit in troubleshooting the problem.

**Comment by ctrlaltca** [comment] 2016-02-12 13:57
Looking at http://packages.ubuntu.com/search?keywords=libprotobuf , it seems that ubuntu likes to ship different versions of protobuf on every distro:
```
precise (12.04LTS): libprotobuf7, aka protobuf 2.4.1
trusty (14.04LTS): libprotobuf8, alka protobuf 2.5.0
vivid (15.x): libprotobuf9, aka protobuf 2.6.1
```

I suppose he only way to get Cockatrice working is to compile it manually from source; the instructions from https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#ubuntu-14xx should work.

**Comment by berserkingyadis** [comment] 2016-02-12 14:19
Doesnt ubuntu offer a solution to resolve the dependencies? Have you tried installing it with apt-get? Alternatively you can use `sudo apt-get -f install`

**Comment by welbinator** [comment] 2016-02-12 14:53
I'm using Gallium OS. 

Using apt get gives me an error about broken packages or something.

I just installed the windows version with Wine

**Comment by Daenyth** [comment] 2016-02-12 15:04
@welbinator If gallium has its own packages distinct from the ubuntu ones, then the deb we provide wont work and you'll need to compile it yourself. The wiki page linked by @ctrlaltca has instructions for different linux distributions, the part that is likely to differ for yours is the names of packages you need to install as dependencies. We're more than happy to help support you getting it working natively.

**Comment by Daenyth** [comment] 2016-02-12 15:05
OK, from googling it looks like gallium is a separate distro, so the deb definitely won't work.

**Comment by ctrlaltca** [comment] 2016-02-12 15:14
> gallium is a separate distro

Built on top of Xubuntu

**Comment by Daenyth** [comment] 2016-02-12 18:03
If it uses the ubuntu official repositories, then our deb should work. If it doesn't, it won't. We'll have to look into the specifics

**Comment by ctrlaltca** [comment] 2016-02-12 18:42
He's using GalliumOS, based on XUbuntu 15.04. Ubuntu 15 only ships a "libprotobuf" package containing "libprotobuf9". We are creating the package on ubuntu trusty 14.04, that uses a "libprotobuf" package containing "libprotobuf8", so we link against a differently numbered version of the library.

**Comment by Daenyth** [comment] 2016-02-12 19:00
ok, well that makes the issue more clear. We don't offer builds for ubuntu 15.04, only 14.04 and 12.04.

I'm not sure how much work we want to do short of maintaining a real deb package on a ppa. @welbinator for now just compile.

**Comment by welbinator** [comment] 2016-02-12 19:56
thanks guys, but I'm a linux noob so I think I'll pass on the compiling. I'll just keep using the Windows version in Wine. I just wanted to make sure you guys were aware of my issue in case it was something you should know about or that would help you.

**Comment by tooomm** [comment] 2016-03-08 15:52
Does it makes more sense to support recent LTS + newest version, instead of the last two LTS versions?

**Comment by ctrlaltca** [comment] 2016-03-08 15:55
It makes sense, but it requires somebody to open an account at launchpad, create a Personal Package Archive (PPA) and mess around to get working packages out of that. Any ubuntu user up to the task?

**Comment by tooomm** [comment] 2016-03-11 17:25
Sounds a bit tedious with the PPA...

Can we close this since the problem is clear and the topic starter prefers to use the win version instead?

**Closed** 2016-03-11 19:56 UTC
Labels: OS - Linux, Troubleshooting
