### ISSUE TITLE
"Show buddies only" option state is not read from config

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4074] opened 2020-08-24 10:41 UTC
See https://www.reddit.com/r/Cockatrice/comments/ie5vrv/show_buddies_only_games_doesnt_rememberis_this_in/

**Comment by ebbit1q** [comment] 2020-08-24 10:49
I'd rephrase this to isn't read, because it is saved.

**Comment by skwerlman** [comment] 2020-08-24 11:28
duplicate of #3282

**Closed** 2020-08-24 11:38 UTC
Labels: App - Cockatrice, Bug
