### ISSUE TITLE
Oracle can't download card database with SSL

### ISSUE THREAD

**Issue by Zombiekwest** [Cockatrice/Cockatrice#2992] opened 2018-01-05 20:18 UTC
<b>Windows 10 x64</b>

<b>Version 2.4.0 (2017-11-19)
</b>

__________

![error](https://user-images.githubusercontent.com/35150063/34626626-1dc2a940-f223-11e7-8d35-f574d5bd48cc.jpg)

Trying to reinstall Cockatrice on a new computer. Every time I try to load Oracle I keep getting this error. I was able to copy and past load from local, but now I can't seem to get the tokens to want to load. Any idea on how to best work around this? THANKS!

**Comment by ZeldaZach** [comment] 2018-01-05 20:19
Known issue; change your download URL to HTTP instead of HTTPS for now.

**Comment by Zombiekwest** [comment] 2018-01-05 20:21
It worked for the card database, but not for tokens.

**Comment by tooomm** [comment] 2018-01-06 19:48
duplicate of https://github.com/Cockatrice/Cockatrice/issues/2031

**Closed by tooomm** 2018-01-06 19:48 UTC
