### ISSUE TITLE
Feature: better tracking of drawing multiple cards

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#743] opened 2015-02-15 06:51 UTC
Sometimes when people use the crtl-D function to draw multiple cards, it can be hard for the opponent to track how many cards were drawn. (The crtl-E function does exist, but not all players use it.) For example:
Player_A draws 1 card(s).
Player_A draws 1 card(s).
Player_A draws 1 card(s).
Player_A draws 1 card(s).
Player_A draws 1 card(s).

It's hard to tell how many cards were drawn. It would be good if the client added a card count at the end of each message for all draws that occur within 0.5 (?) seconds of each other. e.g.:

Player_A draws 1 card(s).
Player_A draws 1 card(s). (2)
Player_A draws 1 card(s). (3)
Player_A draws 1 card(s). (4)
Player_A draws 1 card(s). (5)

This makes it easy to see the total amount of cards drawn. 

On a related note, when a player draws a single card, there's no need for the "(s)" on the end of the message  - the client should just say "Player_A draws 1 card." or just "Player_A draws a card." So the final implementation would look like:

Player_A draws a card.
Player_A draws a card. (2)
Player_A draws a card. (3)

**Comment by ZeldaZach** [comment] 2015-02-15 06:58
This should apply to any actions where `currentMessage == currentMessage-1`

My idea is instead of just adding a (2), (3), and so on to messages, we can do a replacement to save room.
i.e. if they draw a card then draw another before any other interaction is done in the chat, the message will be deleted and replace with "Player draws a card. (2)" to keep the chat from being flooded.

**Comment by FrozenSlave** [comment] 2015-02-16 23:02
unrelated issue. The in game chat box, any idea how to make it bigger?

**Comment by MassCraziness** [comment] 2015-02-16 23:05
@FrozenSlave You can adjust the size of the chat box, make the players box smaller, and also set it to show "card only" or "text only" to make the chatbox a bit bigger

**Comment by ZeldaZach** [comment] 2020-11-03 21:49
Dupe of #2663

**Closed by ZeldaZach** 2020-11-03 21:49 UTC
Labels: App - Cockatrice, Suggestion, UI / UX
