### ISSUE TITLE
Notes Text for Buddies

### ISSUE THREAD

**Issue by Narglfrob** [Cockatrice/Cockatrice#4579] opened 2022-02-22 21:07 UTC
**Description of New Feature**
For entries in my buddies list (i.e. other players I have tagged as a buddy) add the ability to write text notes that are associated with that player, viewable (and editable) only by me.

**Additional Context**
I play cockatrice on and off for years. I come across other players that are enjoyable to play with, who I tag as a buddy. However my memory is not good. After weeks/months/years I do not remember who these players I have tagged as buddies are, or why I know them. This inhibits me from reaching out to them, inhibits the fostering of a community on cockatrice, and inhibits the utility of the buddies list (its full of people I don't remember).

If I was able to write a quick note to myself about how this person is, it would overcome the above issues.

Discord has this feature, for an example implementation to copy off.

**Comment by ebbit1q** [comment] 2022-02-22 21:28
duplicate of #1957 please check if there is a ticket for your suggestion first and leave a comment on that ticket instead

**Closed by ebbit1q** 2022-02-22 21:28 UTC
Labels: Feature Request
