### ISSUE TITLE
Tokens again, not same problem though!

### ISSUE THREAD

**Issue by Jorenthar** [Cockatrice/Cockatrice#1811] opened 2016-02-13 15:12 UTC
I have yet another problem with tokens now. I reinstalled the new version that I was apparently missing (looks nice), but now when I do ctrl + T to create named token like if I roll a die and want to write the number on a token it gets named "    " (<- nothing) and gets put down where one usually puts lands instead. Someone said it might be a bug with the new version and all. Please fix it as fast possible because I am far too lazy to scroll back up after the wall of text to look what I rolled and say it in chat. You get what I mean. Great work with Cockatrice anyway! :D

**Comment by Nightfirecat** [comment] 2016-02-13 16:17
Duplicate of #1768.

**Closed** 2016-02-13 16:24 UTC
