### ISSUE TITLE
Able to Select Card Art 

### ISSUE THREAD

**Issue by issa-puppi** [Cockatrice/Cockatrice#4713] opened 2022-12-01 01:48 UTC
I think it would be a nice QoL upgrade to be able to either in deck building (via set codes like Arena does for deck exporting) and/or to see all the available card artworks for a card and select which one you would like to have visible. It would additionally be nice to be able to filter the card art's by language if users have a preference for one language over another.

I think this could be done by adding a dropdown right click context menu that allows to pull up the database of art for that card. The set priority system is very clunky and unfriendly to use so this would be a nice QoL upgrade for users.

**Comment by ebbit1q** [comment] 2022-12-01 19:47
duplicate of https://github.com/Cockatrice/Cockatrice/issues/486
please comment on existing tickets before opening new ones with the same topic

**Closed by ebbit1q** 2022-12-01 19:47 UTC
Labels: Feature Request
