### ISSUE TITLE
Card Art Loading Issues

### ISSUE THREAD

**Issue by disasterpiece** [Cockatrice/Cockatrice#2788] opened 2017-06-29 12:32 UTC
<b>OS:</b>
Windows 10 Pro
<b>Cockatrice version:</b>
Cockatrice 2.3.17
__________

I just want to say that I love this platform for playing magic, kudos!! The only issue that I have is the card art not loading properly. When I load a deck many of the cards will be blank with a name only. I've even had it where in the pregame lobby all of the cards will have the artwork displayed, but when in the game they won't display. Sometimes other players can see the cards while I can not. I frequently update the card database, almost every time I load cockatrice so I really don't know what the problem is or how to fix it. In a game like magic, not being able to see the card art and text etc. is crippling to the point where you can't play the game at all and when that happens I just go to another platform like untap.in where the cards load properly. Please let me know how I can resolve this because I want to stick with cockatrice!!

Thank you,
RHR

**Comment by skwerlman** [comment] 2017-06-29 12:37
this is probably a dupe of #2782, but since there're multiple reports now, i'm betting there's either a regression somewhere or a windows update broke something...

can you post the contents of your debug log? you can find it at <kbd>Help</kbd>-><kbd>View debug log</kbd>

**Comment by disasterpiece** [comment] 2017-06-29 12:39
Theme changed: "Plasma"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
cache fail for "_trice_card_back_226281"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/rossr/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 17145 Sets= 207
[CardDatabase] loadCardDatabase(): Path = "C:/Users/rossr/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17502 Sets= 207
CardDatabase::loadCardDatabases success
QLayout: Attempting to add QLayout "" to ShortcutsTab "shortcutsTab", which already has a layout
Theme changed: "VelvetMarble"
Card Database load status:  0
cache fail for "_trice_card_back_226281"
QLayout: Attempting to add QLayout "" to ShortcutsTab "shortcutsTab", which already has a layout
Theme changed: "Fabric"
Theme changed: "Leather"
Card Database load status:  0
cache fail for "_trice_card_back_226281"
getPort() index =  1  port.val =  "4747"
getPlayerName() index =  1  name.val =  "disasterpiece"
link path1214 hasn't been detected!
link path1563 hasn't been detected!
link path1563 hasn't been detected!
QObject::connect: No such slot TabSupervisor::resetIdleTimer()
QLayout: Attempting to add QLayout "" to ShortcutsTab "shortcutsTab", which already has a layout
Theme changed: "Plasma"
Card Database load status:  0
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/rossr/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 17145 Sets= 207
[CardDatabase] loadCardDatabase(): Path = "C:/Users/rossr/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17502 Sets= 207
CardDatabase::loadCardDatabases success
cache fail for "_trice_card_back_226281"
Trying to load picture (set:  "pCEL"  card:  "1996 World Champion" )
Picture NOT found, trying to download (set:  "pCEL"  card:  "1996 World Champion" )
starting picture download: "1996 World Champion" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card")
Download failed: "Error transferring http://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card - server replied: Forbidden"
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "pCEL"  card:  "1996 World Champion" )
QPixmap::scaled: Pixmap is a null pixmap

**Comment by tritoch** [comment] 2017-06-29 13:29
Can you visit [this page](http://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card) in your web browser? Should show a card back.

**Comment by disasterpiece** [comment] 2017-06-29 13:38
No, content filtering has it blocked because I am on a work laptop. Probably why nothing works. But this even happens on my linux laptop at home. I just put cockatrice on this computer because my linux machine is down for the moment.

**Comment by tritoch** [comment] 2017-06-29 13:47
We'd need to see the error (debug log) from your other computer.  Images aren't working on your work laptop because it cannot access gatherer to download the images.

**Comment by ZeldaZach** [comment] 2017-06-30 00:37
>No, content filtering has it blocked because I am on a work laptop. Probably why nothing works. But this even happens on my linux laptop at home. I just put cockatrice on this computer because my linux machine is down for the moment.

If you're on a work machine it's possible the default links for downloading card images are blocked. I recommend you either manually download them from a site like slightly magic or find another way to get cards.

**Comment by skwerlman** [comment] 2017-06-30 11:55
@tritoch i think 1996 World Champion won't load normally anyway:
```
Trying to load picture (set:  "pCEL"  card:  "1996 World Champion" )
Picture NOT found, trying to download (set:  "pCEL"  card:  "1996 World Champion" )
starting picture download: "1996 World Champion" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card")
Picture downloaded, but blacklisted, will consider it as not found
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "pCEL"  card:  "1996 World Champion" )
```

**Comment by disasterpiece** [comment] 2017-06-30 11:57
I had our IT guys add gatherer and a few other sites to the whitelist so my laptop can access them and now the problem is resolved! Thx for the suggestions!

**Comment by tooomm** [comment] 2017-06-30 14:06
Hehe, great!

**Closed by tooomm** 2017-06-30 14:06 UTC
