### ISSUE TITLE
Cockatrice window opens with fixed size on application launch

### ISSUE THREAD

**Issue by kvesel** [Cockatrice/Cockatrice#3460] opened 2018-11-28 06:07 UTC
When changing size of Cockatrice application window there is not saving to file with new window attributes. Closing Cockatrice and open again will show window is same size as default when this is fresh install.

**Comment by Daenyth** [comment] 2018-11-30 23:49
I think this is a dupe of another ticket, but I'm not sure which one. This should be easy to fix.

**Comment by Daenyth** [comment] 2018-11-30 23:54
Probably need to start looking around here: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/window_main.cpp#L804

**Comment by kvesel** [comment] 2018-12-02 14:00
`
if (!restoreGeometry(settingsCache->getMainWindowGeometry())) {
        setWindowState(Qt::WindowMaximized);
}
`

This is making window maximized but window is starting not maximized but only will start very small sizing. In settings file main window metrics is not changing when closing program.

**Comment by ebbit1q** [comment] 2018-12-02 14:49
Managed to replicate this on Ubuntu but not on windows, this might be a linux issue.

**Comment by tooomm** [comment] 2018-12-02 18:30
There are many other issues on different platforms regarding resizing and start up size, e.g.
https://github.com/Cockatrice/Cockatrice/issues/1904, https://github.com/Cockatrice/Cockatrice/issues/2621, https://github.com/Cockatrice/Cockatrice/issues/2708, https://github.com/Cockatrice/Cockatrice/issues/3326

**Comment by ebbit1q** [comment] 2020-09-28 20:25
I merged these tickets into https://github.com/Cockatrice/Cockatrice/issues/4114

**Closed by ebbit1q** 2020-09-28 20:25 UTC
Labels: App - Cockatrice, Defect - Basic, UI / UX
