### ISSUE TITLE
Allow Deck Storage and Game Replay tabs to be closable.

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2265] opened 2016-11-06 11:49 UTC
Tabs are infrequently used, should be closable, and reopenable with a menu item.

**Comment by ZeldaZach** [comment] 2016-11-06 19:02
I think i've opened an issue on this in the past... Anyway, I wasn't able to find a way to accomplish this on a first glance but I'm sure i'll try again soon or someone else can.

**Comment by poixen** [comment] 2016-11-06 19:28
I think you can add X to the tabs in the TabSupervisor class.

**Comment by Daenyth** [comment] 2016-11-06 20:30
We'll also need to make sure we have a menu entry to open these tabs again.
If dockable UI stuff is any indication then people will get confused

**Comment by ZeldaZach** [comment] 2020-10-06 22:04
Dupe of #1963

**Closed by ZeldaZach** 2020-10-06 22:04 UTC
Labels: App - Cockatrice, Suggestion
