### ISSUE TITLE
Requiring new features should be tied to the regular release of a well tested beta client.

### ISSUE THREAD

**Issue by MustyMustelidae** [Cockatrice/Cockatrice#1591] opened 2015-09-26 19:22 UTC
Right now new downloads are based on weekly completed PRs which are usually only tested by a few devs. The downloads seem to go from bleeding edge after a PR is completed to main channel in days, with little to no testing outside of people who are already developing.

If new versions of the client are being required, the new feature sets should not force users to use a bleeding edge build with minimal testing. The recent botched release of the so-called "Expedtions" build is proof that unless the newest versions of cockatrice aren't required, there must be a beta channel offering release candidates that have their features frozen and go into bug fixing mode, rather than new features being lumped on with minimal testing outside of a few people then pushed out and required.

The servers should also not require features that have not gone through an RC process, so that users on the latest stable builds can stay on them until bugs are fixed.

Those RCs should also be offered as a compiled binary to encourage more people than just devs to use and test them. If a build carries a "beta" or "RC" moniker, users are a lot more likely to be receptive to issues and provide **meaningful** feedback, rather than repeatedly flooding the support channels with their issues. It also doesn't reflect well on the project when within 24hrs of a new release, the first "named" release in months, a new version is needed to fix a bug that breaks core functionality and stability in such an easy to reproduce way. It implies that devs aren't taking the community into the process. 

Cockatrice might be open source, but GitHub is a decidedly dev oriented environment. Involving the community in testing takes a lot more than just putting Cockatrice on public repository where they can build it. It means things like compiled betas that can be advertised as incomplete but precursors to a stable build that they can expect to work. Things like that will also let the community become more carefully integrated with the development of their program. If we announce features before their implemented, we can integrate feedback on them *before* making them features in a main release, rather than simply after they pass the PR process. 

I brought up this point a long time ago, back when "Summer Magic" came out and weeklies started to replace stable downloads on the site, in direct communication with some devs, and have brought it up time and time again, yet nothing seems to be happening. All of this is generally standard procedure for community oriented projects, and really any sort of successful software. A merged PR doesn't have to mean that a feature is *completely* "bug free" , *unless* it's to the **main** release branch. PRs to that branch simply cannot break the program in a way that users are able to reproduce within hours, nor should they be features that users feel they had no warning about, like the recent change to the theme system. At first there wasn't even documentation for it yet, features like that necessitate a beta or RC release channel.

As I said above, GItHub maybe be open, but browsing through PRs and hearing individual devs say "we're doing X" shouldn't be the only way that users know about a feature right up until it suddenly becomes part of the only release channel. They should have a chance to test multiple new features regularly besides building every single PR for themselves. The developers are letting down the program's users if they keep up this pattern of using the entire user base as a test bed then releasing fixes to brand new features.

**Comment by woogerboy21** [comment] 2015-09-26 20:11
One thing to mention about this (just a thought).  The development course of the application would work fine with the idea's you laid out.  How ever the people doing the server operation may not necessarily agree with the concepts here and wish to run cutting or bleeding edge code requiring users that connect to there server to upgrade.

**Comment by MustyMustelidae** [comment] 2015-09-26 20:26
It's true, but that's also against the basic tenets of QA and UX. If an individual server administrator decides that they don't value the quality of the experiences users of the program have over simply having a slew of *relatively* untested bleeding edge features it should be a choice they make, not the project and it's developers. 

Those features I've seen listed in the new QMap are mostly moderation tools meant to improve their experiences by aiding mods, yet they cause *a lot* of manpower to be spent on aiding users with unrelated new features that come tacked on.

The way to address those with more consideration taken to users is to keep the moderation changes isolated when it comes to adding them to an beta/RC. Their beta cycles would be shorter than average since less features added to the stable branch would mean less time needed in beta to test changes. 

It'd standardize a method to ensure that all mods on all servers have the newest tools, and still allow users to use a well tested client.

**Comment by woogerboy21** [comment] 2015-09-26 20:28
@MustyMustelidae I think were slowly getting to what you've described.  There was just a point in which we had to bring clients up to date.  This being that point.  And the change that was made a number of days ago only required the client id functionality which was available in prior "official" releases to expeditions.

**Comment by Daenyth** [comment] 2015-09-26 20:29
It's worth noting that the required upgrade wasn't to expeditions, it was just to anything made since about early August

**Comment by woogerboy21** [comment] 2015-09-26 20:30
Going forward there should be a much smoother upgrade path for end users.  Now there is a notification system in place and requiring features that are pretty much untested aren't expected to be enforced immediately.

**Comment by woogerboy21** [comment] 2015-09-26 20:31
Thats not to say there couldn't be a similar structure as to what is described.  Just mentioning it.

**Comment by Daenyth** [comment] 2015-09-26 20:44
I hopefully will have some time tonight to write a more detailed reply

**Comment by Daenyth** [comment] 2015-09-27 12:59
First, I'd like to thank you for the detailed and thoughtful feedback. I really appreciate it.

Right now we're working on getting fully automatic builds produced that will enable easier testing.

My next major work item is to introduce automated tests to help prevent regressions without manual testing.

Regarding server requiring features - that's at the sole discretion of the server owner. By default we don't have things enabled. If that's how the server owner wants to run it, we can't do much about that.

I'd also like to get automatic changelogs put out so that users can be more aware of incoming changes.

Are there other concrete changes you think we should move towards?

**Comment by MustyMustelidae** [comment] 2015-09-27 14:38
Those all sound like helpful measures, but main change that is likely needed is adding beta branches that lead to special builds marked as stable. 

Once a beta is forked from the current snapshot no new PRs should be allowed that do anything but fix existing bugs with that beta. Any fixes that show up in a beta channel should then be merged back into the main branch. It's slightly backwards from what other programs might do, using the master for stable and additional branches for bleeding edge, but at least that way we have a beta system and the current build system isn't interrupted too much. 

Automatic builds make it easier to test, but without a dedicated beta channel that features promotion to stable, there's no way to ensure that each build marked as stable is actually stable. While unit testing will help find regressions, we still need a beta channel that's advertised to be tested by users.

Servers requiring features are indeed currently at the sole discretion of the server owner, but I don't think we should allow sever connections to be blocked based on features that are bleeding edge in the system to start with. The system should be based on client version numbers, not individual features. As @woogerboy21 there is indeed a need to bring clients up to date eventually, I'm not disagreeing with that. Fragmentation means that new updates have to tread around old issues. 

But simply differentiating based on features doesn't do that. Just as @Daenyth said, those new features were supposed to be in clients going back almost 2 months, that covers many versions, many of which weren't tested. Basing it on a dynamically typed string dictionary as it is now isn't tackling the real issue of fragmentation at all, it's just creating new arbitrary boundaries for fragmentation. If client version 1.1 reports supporting feature "X" and versions 1.2 contains an important fix for feature X, v1.1 isn't going to stop reporting it supports feature "X". We'll now be working with 2 versions claiming to support a feature with one supporting it in a broken way, and the only way to fix that will be to add an arbitrary new term to the feature list, like feature "X,v2" or feature Y (meaning that the server is just forcing every new PR on clients), or to make the server now reject connections for v1,1. In no time at all either option will become unwieldy, with a terrible patchwork of versions that work and don't work, with fragmentation no longer even based on the age of a build, but on an unreasonably specific combination of features and versions..

Just yesterday I logged in on a server and had to update, as the connection was refused on the basis of new features. A week ago I had installed the latest build. So now we've gone to backwards compatibility that extended multiple years of clients (which had it's own issues) to the opposite backwards compatibility, forced bleeding edge clients that need to be constantly to be updated to minimally tested versions to connect to the default server.

There's something in-between, and that's simply requiring the latest stable build, based on a beta/RC branch system. It has it's own inherent ways of ensuring that server admins aren't able to force users to use untested software (which generates unhelpful feedback for the project with people constantly having benign issues like invisible game lists due to issues with filters), while making sure that the developers don't have to deal with issues that arise from trying to support clients that are years old. 

There are no stable builds right now, so instead of adding more and more feature that aren't tested while something is worked on, the current feature system should be replaced with a system that requires the first feature that was added and no more (ie. a PR that replaces the dynamic QMap with an instance defining the first one that a client went out with). That immediately ends support for clients older than 2 months or so, as was intended from what @Daenyth said. 

From there a branch of the current build should be made that is labeled as Beta or RC 1. New PRs will still go to master, and stay on master, as the features for the first stable build will have been frozen after the beta branch is made. That branch should be compiled and offered as a new download, a beta. The current download is an alpha build, with no formal testing process established before it was implemented, and should be marked as so. Players should be encouraged to download the beta with the disclaimer that issues are to be expected, and given a URL to report issues with it to. Any issues found should have PRs that first get merged to the beta branch, and tick up the minor version of the beta. 

Once issues stop coming in on the beta branch, that's build should be promoted to stable, and shared as the new main download. Any PRs that fixed issues in the beta branch should be introduced into the master branch, and after that the master branch will consist of the current stable version + any new features added while that version was in beta. After a short pause to decide what features should make it to the next stable versions, the process would repeat itself with a new beta branch. All features between stable branches would be listed on roadmaps as either currently in beta and slated for the next stable, or currently in master slated for the next beta.

The version number would be based on the date of it's build like current builds are. A new PR that refuses connections **only** based on the date of a build would then be merged. The date that servers refuse builds on should be the date of the last stable build. Meaning that as long as a user is *at least* on the last stable build, they can connect to a server. 

A version number would be more ideal, but without automated builds being in place yet, it'd be an error prone method. As soon as those are implemented though, versions number will be a must. With version numbers, servers can refuse clients only when the major version number of the client is lower than the major version number of the server. Because we're using dates, nothing stops an administrator from simply changing the last date allowed (the date should be in the code vs the ini to discourage it though). 

With version numbers the clients wouldn't have to report their minor version number, meaning that administrators couldn't micro-manage the clients allowed to connect, since the alpha client will never have a higher *major* version number than the last stable. 

While some options are up to admins, some aspects like release branches is up to devs, not server admins. Additionally I doubt that sever admins will see much of an increase in users, and if anything should expect a decline, if users are constantly dealing with benign issues due to the combination of a lack of testing and forced updates. Sometimes force updates are needed, and if testing is implemented we can do that without issue.

**Comment by Daenyth** [comment] 2015-09-28 02:20
After the expeditions release we've been discussing changing PR merge strategy in #1562 - I've updated that with an RC period for `featureset` features.

Going forward, that combined with the upcoming automated releases (hosted on bintray, not woogerworks) should cover a lot of your concerns.

Specifically also, requiring features vs versions is because it's more specific and more flexible. If we use version numbers it means that every app using the cockatrice protocol must use the Cockatrice app version numbers.

**Comment by Daenyth** [comment] 2015-09-28 02:33
I'm closing this since we'll be incorporating the main suggestion from now on.

**Closed by Daenyth** 2015-09-28 02:33 UTC
Labels: Suggestion
