### ISSUE TITLE
Clicking away from mention right-click still appends mention to chat message

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#2356] opened 2017-01-11 07:32 UTC
<b>OS:</b>
Win7 SP1

<b>Cockatrice version:</b>
f7c8651d (2016-12-30)

___
<br>

While in a server's "Main" room (and others? not sure), right-clicking on a mention in the chat window, then left-clicking anywhere else on the screen causes the mention to be appended to your current chat message. I would expect that clicking away from the right-click menu would not add a mention to my chat message.

**Comment by ZeldaZach** [comment] 2017-06-03 18:03
@Nightfirecat Can you try this again? I don't seem to have this issue on Mac.

1) Type "@s" then a popup appears. 2) Right click on a user on the list. 3) Left click anywhere. Result: My chat bar just says "@s"

**Comment by Nightfirecat** [comment] 2017-06-03 18:07
Give me a minute, I think we're testing slightly differently. I should be able to get a gif of the issue; I'll see if it's still present in stable now.

**Comment by Nightfirecat** [comment] 2017-06-03 18:16
Strangely enough, my recording program didn't reproduce it perfectly, so I had to write up some steps on how to repro... First,the gif:

![menu-demonstration](https://cloud.githubusercontent.com/assets/2199511/26756006/fcffa1ec-484d-11e7-9cae-a299d6d3dbaf.gif)

And the written steps to repro:

![menu-bug1](https://cloud.githubusercontent.com/assets/2199511/26756008/16fe7398-484e-11e7-9e75-913236cae4b3.png)
![menu-bug2](https://cloud.githubusercontent.com/assets/2199511/26756010/1959898e-484e-11e7-9970-ce70eb04b7df.png)

**Comment by ZeldaZach** [comment] 2017-06-03 19:47
So I don't seem to have this issue on Mac/Linux.  I follow your steps and these are the actions that take place.

<img width="397" alt="screenshot 2017-06-03 15 46 59" src="https://cloud.githubusercontent.com/assets/7460172/26756585/e8cef288-4873-11e7-860e-80bd2a64f589.png">
<img width="439" alt="screenshot 2017-06-03 15 47 03" src="https://cloud.githubusercontent.com/assets/7460172/26756586/e8d104e2-4873-11e7-836f-1dc7173534cf.png">

**Comment by tritoch** [comment] 2017-06-04 01:43
> Mac/Linux

The "Copy / Copy LInk Location / Select All" menu should not appear when clicking away from the user context menu.  It's a different behavior but still undesired.

**Comment by ZeldaZach** [comment] 2020-10-06 21:51
Closing as it's a dupe of #3935 (different showing, but exact same issue)

**Closed by ZeldaZach** 2020-10-06 21:51 UTC
Labels: App - Cockatrice, Defect - Basic, OS - Windows
