### ISSUE TITLE
Order card sets by date no longet an option

### ISSUE THREAD

**Issue by k5t77** [Cockatrice/Cockatrice#3462] opened 2018-11-29 09:15 UTC
<b>System Information:</b>
  
Windows 10 x64, Cockatrice "Version 2.6.1 (2018-07-17)"
  
__________________________________________________________________________________________

  
The option of ordering card sets by date is no longer allowed. Why? I seem to not be the only one who prefers ordering by "oldest first", and these days, it can't be done. Very frustrating.

**Comment by ebbit1q** [comment] 2018-11-29 13:41
Duplicate of https://github.com/Cockatrice/Cockatrice/issues/3359
We are already aware of this issue and will try to resolve it in due time.

**Closed** 2018-11-29 16:48 UTC
