### ISSUE TITLE
Adding a Commander Mode

### ISSUE THREAD

**Issue by KeroroLulu** [Cockatrice/Cockatrice#4693] opened 2022-10-19 10:52 UTC
As a Commander player I find it quite troublesome to have my commander on the stack, it would be nice to add a command zone when we are starting a Commander game.

Also, having a more ergonomic way to count for Commander damages instead of using counters on the side that we are already using for counting floating mana and infect.

The last request isn't for commanders really but it would be nice to have a best way to manage our exile stack. Because technically we can have different exile types, like temporary exile with cascades. When I play cascade, to not mix my exiled card from other sources and my exiled cards from cascade I put the cascade exile on the battlefield but it's starting to get really big when I have to exile 70 cards before getting a proper card that I can cascade (Codie with Hypergenesis build when this one is at the bottom of my lib). So maybe having a way to separate exile stacks, and also putting counters on exiled cards (for effects like Karn)

Imo it would be really great to get something like that and would help to have a better experience in cockatrice

**Comment by ebbit1q** [comment] 2022-10-19 14:58
please make separate tickets for separate feature requests, this allows us to track progress.
also check if something has been requested already add your input as a comment on that ticket.
your first suggestion would be a duplicate of #1740

**Closed** 2023-02-01 21:52 UTC
Labels: Feature Request
