### ISSUE TITLE
Commanders should have a Command Zone.

### ISSUE THREAD

**Issue by mpalmujoki** [Cockatrice/Cockatrice#4158] opened 2020-11-04 10:43 UTC
We play Commander as well, and have found a bit of an issue of where the commander should rest in the UI, while he is in the Command Zone and not out in play.

We use mainly the red stack area, but that's far from optimal.

Please implement some place players can drag their commander to, that would be visible for the rest of the players, that's not actively used for something else.

**Comment by tooomm** [comment] 2020-11-04 10:56
Dupe of https://github.com/Cockatrice/Cockatrice/issues/282, tracked in https://github.com/Cockatrice/Cockatrice/issues/1740

**Closed by tooomm** 2020-11-04 10:56 UTC
Labels: Feature Request
