### ISSUE TITLE
More art options for decks please 

### ISSUE THREAD

**Issue by TheSwedishLlama** [Cockatrice/Cockatrice#4571] opened 2022-02-09 03:02 UTC
**Similar Requests**
I didn't see anything similar but i could have missed it

**Description of New Feature**
I would like to be able to have multiple different arts of a card in a deck for example i want 4 copies of Thalia, Guardian of Thraben in my deck, but i want each one to be a different art. (example in attachments)

I've noticed some cards have (a) versions i feel like maybe this could be used to implement this idea? maybe the code tells the person with standard art on their computer to ignore the (a) / (b) / (c) and just show the card before the letter? 

If you need to reach me
email: k.johan.anderson@gmail.com
discord: The Swedish Llama#9486

**Additional Context**
![1bbde9d9-1723-4f26-8700-63c459ac80cb](https://user-images.githubusercontent.com/99294698/153113967-e8f23192-b3ec-4ec2-aaa3-3e274df1021a.jpg)
![717de388-0c07-4346-9c7e-7b06b14f1cc1](https://user-images.githubusercontent.com/99294698/153113971-a5371291-e8b1-43e4-a939-90f3d96b620b.jpg)
![b05031dc-f99c-49d3-9a20-3453587d8dea](https://user-images.githubusercontent.com/99294698/153113972-5bae186d-7fea-4838-a449-5a427985f3ab.jpg)
![d67a5aac-dbda-4e5d-ae4a-eb78dec6765b](https://user-images.githubusercontent.com/99294698/153113975-d6a08056-05f8-4817-b7bc-8d7c478c15c5.jpg)

**Comment by ebbit1q** [comment] 2022-02-09 03:06
duplicate of https://github.com/Cockatrice/Cockatrice/issues/486

**Closed by ebbit1q** 2022-02-09 03:06 UTC
Labels: Feature Request
