### ISSUE TITLE
Tokens Aligning to Table Grid Incorrectly

### ISSUE THREAD

**Issue by jonidcrushfire** [Cockatrice/Cockatrice#4248] opened 2021-02-09 02:44 UTC
When creating a token, usually when it is a copy of a permanent in play (shortcut CTRL+J, normally), the token immediately stacks to the left of whichever spot I put it in. 

For example, if there are two creatures in play, I copy one, and move the copy to the third spot in the row (immediately after the creatures), it will stack onto the last creature instead. I have to move it another spot over to get it to land where I want to place it.

Please let me know what you need to look into this. Thank you.

**Comment by jonidcrushfire** [comment] 2021-02-09 02:50
As I recall, the last issue, they asked me for this info:




Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Portable
---------------------------------------------------------------------------
Portable mode enabled
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Jonid/Desktop/Game Stuff/MTG/Cockatrice/data/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_226293"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Jonid/Desktop/Game Stuff/MTG/Cockatrice/data/cards.xml" Status = 0 Cards = 22167 Sets= 550
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Jonid/Desktop/Game Stuff/MTG/Cockatrice/data/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Jonid/Desktop/Game Stuff/MTG/Cockatrice/data/tokens.xml" Status = 0 Cards = 22666 Sets= 551
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Jonid/Desktop/Game Stuff/MTG/Cockatrice/data/spoiler.xml" Status = 4 Cards = 22666 Sets= 551
Loading Custom Set 0 ( "C:/Users/Jonid/Desktop/Game Stuff/MTG/Cockatrice/data/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Jonid/Desktop/Game Stuff/MTG/Cockatrice/data/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Jonid/Desktop/Game Stuff/MTG/Cockatrice/data/customsets/TK.xml" Status = 0 Cards = 22666 Sets= 551
CardDatabase::loadCardDatabases success

**Comment by ebbit1q** [comment] 2021-02-09 17:03
duplicate of https://github.com/Cockatrice/Cockatrice/issues/4235 fixed in https://github.com/Cockatrice/Cockatrice/pull/4236 update to beta to use the fixed version, note that servers should already have this deployed.

**Closed by ebbit1q** 2021-02-09 17:03 UTC
