### ISSUE TITLE
Servatrice: Users can edit email addresses without validation

### ISSUE THREAD

**Issue by Lachee** [Cockatrice/Cockatrice#3392] opened 2018-09-18 23:10 UTC
Servatrice allows users to edit their account without any validation of email address. They can set it to blank or what otherwise would be on a banned list. As you can see https://github.com/Cockatrice/Cockatrice/blob/dc727cb6206436060c46ae336d8528bf31bef12b/servatrice/src/serversocketinterface.cpp#L1167-L1196 , there is no check for its validity. 

In addition, users shouldn't be able to change their email in the first place. Email accounts are validated upon registration (optionally) so it makes no sense to allow those users to then change the emails once their account is created. 

I propose that validation is added and a extra configuration parameter to all together disable this function for the server.

**Comment by Daenyth** [comment] 2018-09-19 01:57
We should definitely fix this soon

**Comment by tooomm** [comment] 2018-09-19 04:12
https://github.com/Cockatrice/Cockatrice/issues/1639

**Comment by ZeldaZach** [comment] 2020-09-28 20:34
Agreed. Dupe of #1639

**Closed by ZeldaZach** 2020-09-28 20:34 UTC
Labels: App - Servatrice, Defect - Basic, High Priority
