### ISSUE TITLE
Server crashes when disconnecting

### ISSUE THREAD

**Issue by twiceineverymoment** [Cockatrice/Cockatrice#3936] opened 2020-04-02 00:26 UTC
Servatrice version: 2.7.2 (2019-08-31)
OS: Ubuntu 18.04.4 LTS minimal installation 64-bit

Servatrice seems to crash when I disconnect from the server while a game is in progress. If I'm in a game, even spectating, and I close the game tab and then disconnect, the server crashes and kicks everyone else off. At the time there is at most 1 game going on with 3-4 other players.

Tail of servatrice.log:

Tue Mar 17 19:12:31 2020 561611bfc660 game 0 player 0: [Command_LeaveGame.ext] { }
Tue Mar 17 19:12:31 2020 Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 0
Tue Mar 17 19:12:31 2020 Server_CardZone destructor: "deck"
Tue Mar 17 19:12:31 2020 Server_CardZone destructor: "grave"
Tue Mar 17 19:12:31 2020 Server_CardZone destructor: "hand"
Tue Mar 17 19:12:31 2020 Server_CardZone destructor: "rfg"
Tue Mar 17 19:12:31 2020 Server_CardZone destructor: "sb"
Tue Mar 17 19:12:31 2020 Server_CardZone destructor: "stack"
Tue Mar 17 19:12:31 2020 Server_CardZone destructor: "table"
Tue Mar 17 19:12:35 2020 561611bfbb70 game 0 player 2: [Command_MoveCard.ext] { start_player_id: 2 start_zone: "hand" cards_to_move { card { card_id: 1 face_down: false pt: "" } } target_player_id: 2 target_zone: "table" x: 18 y: 1 }
Tue Mar 17 19:12:38 2020 Socket error: QAbstractSocket::RemoteHostClosedError
Tue Mar 17 19:12:38 2020 Server::removeClient: name= "J0EST4R"
Tue Mar 17 19:12:38 2020 closed session id: 31
Tue Mar 17 19:12:38 2020 Server::removeClient: removed 0x561611bfc660 ; 2 clients;  2 users left
Tue Mar 17 19:12:38 2020 561611bfc660 TcpServerSocketInterface destructor
Tue Mar 17 19:12:39 2020 CRASH: SIGSEGV

Terminal output:

Error: signal 11:
./servatrice(_ZN13SignalHandler14sigSegvHandlerEi+0x34)[0x5587e092f5e4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7fa2062c7890]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZTVN10__cxxabliv120__si_class_type_infoE+0x10)[0x7fa2057d0438]
Segmentation fault (core dumped)

**Comment by ZeldaZach** [comment] 2020-04-02 01:05
If you update to the most recent version of Cockatrice/Servatrice, does that have the same issue?

**Comment by skwerlman** [comment] 2020-04-02 14:45
aadditionally, can you use gdb (or similar) to get a stack trace from the core dump?

**Comment by enforcer574** [comment] 2020-04-02 14:47
Sorry for the delay - I've updated to 2.7.4 and made a fresh SQL database. My playgroup is going to try and reproduce this again later in the day. I'm afraid I'm not too familiar with C, if you can point to a tutorial for getting the stack trace?

**Comment by skwerlman** [comment] 2020-04-02 15:11
to open gdb:
```sh
gdb $PATH_TO_SERVATRICE $PATH_TO_CORE_DUMP
```
then, in the gdb shell that opens:
```
bt full
```

**Comment by JoeRLDuncan** [comment] 2020-04-12 19:02
My issue is similar, except not just during disconnect: https://github.com/Cockatrice/Cockatrice/issues/3954

I can't seem to find my core dumps though, /var/crash/ is empty?!?

**Comment by twiceineverymoment** [comment] 2020-07-27 20:08
> to open gdb:
> 
> ```shell
> gdb $PATH_TO_SERVATRICE $PATH_TO_CORE_DUMP
> ```
> 
> then, in the gdb shell that opens:
> 
> ```
> bt full
> ```

I also have this issue. I'm trying to get the stacktrace but when I run gdb as described above I get:
"/var/crash/_usr_bin_servatrice.1000.crash" is not a core dump: File format not recognized

**Comment by skwerlman** [comment] 2020-07-27 20:54
ah, thats an apport crash file; use the following to run gdb on it:
```
apport-retrace --gdb --sandbox=system $PATH_TO_CRASH_FILE
```
then you can get the bt

**Comment by twiceineverymoment** [comment] 2020-07-28 04:49
`emily@LPNODE01:~$ apport-retrace --gdb --sandbox=system _usr_bin_servatrice.1000.crash
ERROR: report file does not contain one of the required fields: Package`

Still not working. Sorry if this is a dumb mistake, I'm not a C developer.

**Comment by ZeldaZach** [comment] 2020-09-27 21:29
Duplicate of #3954 (I know this is older, but we have trackign there)

**Closed by ZeldaZach** 2020-09-27 21:29 UTC
