### ISSUE TITLE
Use Shift for deck builder shortcuts (Shift + S, Shift + arrows)

### ISSUE THREAD

**Issue by JoshuaLamusga** [Cockatrice/Cockatrice#2937] opened 2017-12-03 21:34 UTC
There is conflicting functionality in Cockatrice's deck builder.

Using the left arrowkey on a card will decrease the amount of that card by 1, but focus will be moved to the parent element. So if you use the left arrowkey twice, you will decrease the amount of the selected card and then close the list it's in. Using the right arrowkey increases the amount of a card by 1 without inconsistent effects.

Using S will move a card to or from the sideboard. If focus is on the deck list, you can start typing a card name in your deck to select it, which is very useful. However, every time you press S the current card will switch to/from sideboard, which ruins this feature.

Both of these inconsistent behaviors can be resolved by requiring Shift to be held. Shift + S to sideboard cards and Shift + left arrow or Shift + right arrow to decrease or increase the quantity of a card by 1; respectively.

**Additional issue:** Sometimes, using left arrow to reduce the only card in a category to 0 quantity will hide that card and category instead of removing it. Even adding another card to that category won't reveal the hidden card, and it's not reflected in the number of cards in the deck. It gets saved with the deck and appears when reloading the deck or playing. I'm not sure if this is related.

**Comment by jrobe** [comment] 2017-12-05 05:44
I replicated that additional issue today - when I was trying to test the decklist.org export feature I had a sideboard card that i removed using the - sign, however when I exported to the decklist still would appear. I had to delete the deck to get it to go away.

**Comment by tooomm** [comment] 2017-12-11 15:49
>Using the left arrowkey on a card will decrease the amount of that card by 1, but focus will be moved to the parent element. So if you use the left arrowkey twice, you will decrease the amount of the selected card and then close the list it's in. Using the right arrowkey increases the amount of a card by 1 without inconsistent effects.

Can confirm. Also your mentioned **additional issue**.
This really is annoying and should be uniform for left and right arrow keys at least!

>Using S will move a card to or from the sideboard. If focus is on the deck list, you can start typing a card name in your deck to select it, which is very useful. However, every time you press S the current card will switch to/from sideboard, which ruins this feature.

Hmm, hitting `S` when the deck is in focus doesn't start searching for me

**Comment by JoshuaLamusga** [comment] 2017-12-11 18:54
@tooomm If you have _Venser's Journal_ in your deck and you want to quickly select it, you can start typing the letters: v, e, n. That will select the first card starting with Ven. But if you type S at any point while searching the card name, it will be moved to/from sideboard. Jumping to cards like _Shrieking Affliction_ isn't possible since they start with S. Other cards with S in the name pose the problem, too.

**Comment by tooomm** [comment] 2017-12-11 19:06
@JoshuaLamusga as I said... that does not work for me on Windows 10 64bit with Cockatrice 2.4.0.

Are you sure that you're not talking about the complete `card list` of all a enabled cards, instead the `deck`?

**Comment by JoshuaLamusga** [comment] 2017-12-11 19:34
Apologies @tooomm, I'm not making myself clear.

> Hmm, hitting S when the deck is in focus doesn't start searching for me

Hitting S will only switch to/from sideboard. Load a deck and click a card name in the deck, then start typing the name of a different card, preferably one without the letter S in the name. The focused card should change from the one you clicked to the one you started typing the name of. If this works, then my point is that hitting S switches to/from sideboard and disrupts the UI feature of typing a card name to switch to it.

I figure since we have the same specs (Windows 10 Home, 64-bit with Cockatrice 2.4.0), it should work on your end. (If it doesn't, that would be its own issue.)

**Comment by Daenyth** [comment] 2017-12-12 01:20
This sounds like a regression - absolutely not intended behavior

**Comment by tooomm** [comment] 2017-12-12 21:03
@JoshuaLamusga Ok, you have to click a card in your deck literally... if you just click in the deck list widget that's not enough. Got it...
Once you hit `S` and it moves the selected card to the sideboard, it resets the selection btw and you have to click at a card in the deck again to be able to search.

**Comment by JoshuaLamusga** [comment] 2017-12-17 18:07
I changed the recommendation from using Ctrl to using Shift because Ctrl + S would conflict with the keyboard shortcut for saving.

**Comment by Vafthrudnir** [comment] 2018-02-12 21:35
If PR #3097 gets merged, the list of banned shortcuts will also have to be modified with this issue.

**Closed** 2018-02-19 05:38 UTC
Labels: App - Cockatrice, UI / UX
