### ISSUE TITLE
Aggregate multiple token messages in chat

### ISSUE THREAD

**Issue by William-hayduk** [Cockatrice/Cockatrice#3409] opened 2018-10-16 12:10 UTC
Can you make it so instead of an output of the tokens made for it for each one made flooding the chat with tokens. You can make it like
Player created token 1/1 goblin [X#]

**Comment by Daenyth** [comment] 2018-10-16 12:43
This might be a larger change than you'd expect, so we'll see.

@ZeldaZach do you know how easy it would be to rewrite lines already written in the chat window? Might be able to do this client side if we just roll them up as they arrive

**Comment by William-hayduk** [comment] 2018-10-16 13:31
Im sorry, I really am but other than that it works, I kinda don't really
know behind the scenes of what happens in cockatrice.

**Comment by tooomm** [comment] 2018-10-16 20:30
Related https://github.com/Cockatrice/Cockatrice/issues/2620 & https://github.com/Cockatrice/Cockatrice/issues/3404

**Comment by Daenyth** [comment] 2018-10-16 21:44
@William-hayduk No need to be sorry, it's a very reasonable suggestion. Not your fault that our tech makes it difficult

**Comment by William-hayduk** [comment] 2018-10-16 23:43
Thank you I mean soon they may have it changed.

**Comment by ZeldaZach** [comment] 2020-09-28 20:28
Duplicate of #3404

**Closed by ZeldaZach** 2020-09-28 20:29 UTC
Labels: App - Cockatrice, App - Protocol / API, App - Servatrice
