### ISSUE TITLE
Card Display Name Immutable

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2330] opened 2016-12-30 17:33 UTC
English card name is the identifying information for protocol.  It should be a hidden ID field and card name should be translatable.

**Comment by Daenyth** [comment] 2016-12-30 23:20
I don't understand what this ticket is asking for. Can you be more specific?

**Comment by ZeldaZach** [comment] 2016-12-31 18:09
I think he's thinking about something in the xml
```
        <card>
            <name>EL GATO</name>
            <name_en>Cat</name_en>
            <set muId="111">CAT</set>
            <color>G</color>
        </card>
```

**Comment by tritoch** [comment] 2017-01-03 14:16
> ZeldaZach commented 3 days ago
I think he's thinking about something in the xml

This is correct.  If a card name is changed in XML to a foreign name (or nickname), it is no longer understood by the server.  In game, cards should be passed to server with something like `en_name`, `server_name` or similar, so clients can use whatever name they want (and of course server falls back to `name` if no `en_name/server_name`)

**Comment by poixen** [comment] 2017-01-04 14:39
@tritoch even if you were to add an `en_name` that would still be mutable and editable. What benefit do you get from changing the original card name in the first place? Arent cards translated?

**Comment by tritoch** [comment] 2017-01-04 14:50
If you choose `Card Language: German (Deutsch)` in settings, your `Forest` changes name on your client to `Wald` in Deck Editor, Deck List, Library, Hand, Sideboard, Exile, Battlefield, Card Information, Chat.  Other players who can see those zones and have `Card Language: English` in settings still see `Forest` in all those zones.  If you save the deck to file, it saves as `Forest`.  If you search in deck editor `Forest` or `Wald` for card name, it brings up `Wald`.

**Comment by poixen** [comment] 2017-01-04 14:54
So the issue is with the saved deck files?

**Comment by tritoch** [comment] 2017-01-04 14:57
>So the issue is with the saved deck files?

Nope.  Issue is in Game.  A player who wants to play localized cards cannot have their card names localized and play against people who do not also have their card names to the same locale.

**Comment by poixen** [comment] 2017-01-04 15:01
So when you save your deck it looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_deck version="1">
    <deckname>Deck Name</deckname>
    <comments></comments>
    <zone name="main">
        <card number="1" price="0" name="Forest"/>
    </zone>
</cockatrice_deck>
```

or this:
```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_deck version="1">
    <deckname>Deck Name</deckname>
    <comments></comments>
    <zone name="main">
        <card number="1" price="0" name="Wald"/>
    </zone>
</cockatrice_deck>
```

**Comment by tritoch** [comment] 2017-01-04 15:05
Saved deck would still use `name="Forest"` for compatibility.  Not sure how that would then be converted to a server name.

**Comment by poixen** [comment] 2017-01-04 15:06
What does _your_ decklist look look when you save it.

**Comment by tritoch** [comment] 2017-01-04 15:09
```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_deck version="1">
    <deckname>Deck Name</deckname>
    <comments></comments>
    <zone name="main">
        <card number="1" price="0" name="Forest"/>
    </zone>
</cockatrice_deck>
```

But why wouldn't it?  I'm running vanilla release.

**Comment by poixen** [comment] 2017-01-04 15:10
Why are you changing card names in the xml?

**Comment by tritoch** [comment] 2017-01-04 15:10
>Why are you changing card names in the xml?

So I can understand what the card is called if I'm not an English speaker...

**Comment by poixen** [comment] 2017-01-04 15:11
In the client its translated.

**Comment by tritoch** [comment] 2017-01-04 15:13
>[09:12:51] tritoch bringt Forest von ihrer Hand ins Spiel.

**Comment by poixen** [comment] 2017-01-04 15:24
Now I understand the issue. 

Based on the action we create a string with empty arguments:
`finalStr = tr("%1 puts %2 into play tapped%3.");`
The above has `tr` performed on it, which will find the above for you in your language.

We then use the incoming request to append the XML data from the other player into the already translated string.
`appendHtmlServerMessage(finalStr.arg(sanitizeHtml(attributes.player->getName())).arg(cardStr).arg(fromStr).arg(attributes.newX));`

This seems like a simple fix. If you are able to use the vanilla XML and see card names in German then whatever process is used to translate that can be used here. 

_It also seems like areas are currently not translated as demonstrated by the use of "Hand" in your last comment_.

**Comment by tritoch** [comment] 2017-01-04 15:27
That would require a transifex entry for every card.

**Comment by poixen** [comment] 2017-01-04 15:33
Current solutions are:

+ transifex card names for each language (lots of work, tight coupling, legal problems?)
+ cards.xml for each language (lots of work unless scripted)
+ allow users to make local modifications to XML file and use a different id (simple fix would be `multiverseid`)

**Comment by woogerboy21** [comment] 2017-01-04 15:35
> That would require a transifex entry for every card, and wouldn't handle the card name on the battlefield, in hand, or any zone other than chat.

Sadly that is how things are done now ....

**Comment by tritoch** [comment] 2017-01-04 15:36
>allow users to make local modifications to XML file and use a different id (simple fix would be multiverseid)

This, please.  But `multiverseid` is not a great `id`.

**Comment by Nightfirecat** [comment] 2017-01-04 17:01
I believe that MTGJSON provides translations of card names where provided by WotC; this won't include all languages that Transifex does, but it would include a fair number of them.

**Comment by woogerboy21** [comment] 2017-01-04 20:43
@tritoch 
Are you simply wanting to display the foreignNames field of the mtgjson information?  Or are you trying to implement something that allows you to customize an xml and have users else were receive / use those customization through the application?

**Comment by tritoch** [comment] 2017-01-04 20:51
If I were a non-english speaker, I'd want my battlefield to look like the below, pardon the terrible MSPaint.
![foreigncards](https://cloud.githubusercontent.com/assets/3866018/21658677/20fcdd76-d28d-11e6-92f9-cb38c3bc988b.png)

But if I change the name of `Forest` to `Wald` in my xml, my opponent will see a blank card.  My opponent should still see `Forest`.  I should see `Wald`.

**Comment by tooomm** [comment] 2017-01-04 21:05
The xml hack is not a good workaround for everybody.
We should try to find a way to support different languages for card names and art for all users.
Mtgjson has some foreign data on names and Oracle could write it to the xml, it's part of the extended allsets.json with extras.

From the mtgjson documentation:
```
foreignNames
Foreign language names for the card, if this card in this set was printed in another language. An array of objects, each object having 'language', 'name' and 'multiverseid' keys. Not available for all sets.
```

**Comment by tritoch** [comment] 2017-01-04 21:12
I don't want to force all clients to carry all translation data in their xml.  

Each card should have an ID field that it uses to communicate with proto.  Then you can change the card name to whatever you want in your XML.  In the future, we can modify Oracle to have a language selector that will let you download the extra allsets and overwrite your card names or append them.  But the first step, I believe, is to have proto separate the card's name from its identification.

**Comment by tooomm** [comment] 2017-01-04 21:42
>I don't want to force all clients to carry all translation data in their xml.

Why not? It shouldn't be too much data.
And it looks to me like the only easy way to accomplish simple card language support for all users.

Anyway, we just need to ask in Oracle:
"In which languages do you want to display cards?" --> list of available printed languages (~6?)
This should end up with just 1 additional line per card per languages (mostly just one). Since every card has already plenty of them, the cards.xml would just increase about like 10% in size maybe.

Here is an example of a random creature card:
```
        <card>
            <name>Aven Riftwatcher</name>
            <set rarity="Common" muId="413543" num="1">EMA</set>
            <set rarity="Common" muId="108899" num="1">PLC</set>
            <color>W</color>
            <manacost>2W</manacost>
            <cmc>3</cmc>
            <type>Creature — Bird Rebel Soldier</type>
            <pt>2/3</pt>
            <tablerow>2</tablerow>
            <text>Flying
Vanishing 3 (This creature enters the battlefield with three time counters on it. At the beginning of your upkeep, remove a time counter from it. When the last is removed, sacrifice it.)
When Aven Riftwatcher enters the battlefield or leaves the battlefield, you gain 2 life.</text>
        </card>
```
We would just add `<name_de>Avior-Rissbeobachter</name_de>` for example.
<br>

But passing an ID to the server instead a clear name might still be valid, to hide card names or prevent cheating - don't know.

**Comment by Nightfirecat** [comment] 2017-01-04 21:55
Not all sets were printed in all languages that modern sets are; current sets are printed in the following:

* English
* Simplified Chinese
* Traditional Chinese
* French
* German
* Italian
* Japanese
* Korean
* Portuguese
* Russian
* Spanish

However, older sets did not include each of these languages, and supplemental product is in a similar situation. (ex. EMA was printed only in English, Japanese, and Simplified Chinese) It seems to me like it would be easier to simply store cards.xml with multiple tags where translations are present, and add some kind of tag, like `<name lang="de">Avior-Rissbeobachter</name>`

**Comment by tritoch** [comment] 2017-01-04 22:13
>We would just add <name_de>Avior-Rissbeobachter</name_de> for example.

>and add some kind of tag, like <name lang="de">Avior-Rissbeobachter</name>

That only covers `name`.  Cards also carry a bunch of other fields that should be translated, including card `text`, which can carry a large amount of data.

**Comment by ZeldaZach** [comment] 2017-01-13 15:20
I do like the idea of the lang option for the name tag.

**Comment by ZeldaZach** [comment] 2020-10-04 19:45
Dupe of #2545 (i know, that's newer)

**Closed by ZeldaZach** 2020-10-04 19:45 UTC
Labels: App - Cockatrice, Suggestion
