### ISSUE TITLE
Image Scaling (for High Resolution Monitors)

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2329] opened 2016-12-30 17:18 UTC
On high resolution monitors, cards are small (at least in `view deck` and probably on battlefield)

**Comment by skwerlman** [comment] 2016-12-31 00:50
related: #1937 #1426

**Comment by ZeldaZach** [comment] 2020-10-06 21:52
Calling it a dupe of #1426 as linked

**Closed by ZeldaZach** 2020-10-06 21:52 UTC
Labels: App - Cockatrice, Defect - Basic
