### ISSUE TITLE
+ & -  no longer usable bind keys due to auto-chat implementation

### ISSUE THREAD

**Issue by kwjohnstone** [Cockatrice/Cockatrice#2261] opened 2016-11-02 08:34 UTC
<b>OS:</b>
windows 10

<b>Cockatrice version:</b>
newest version/build of cockatrice

___
<br>

Previously (2 builds ago) you could bind + & -  on their own. I've since noticed that the chat dialog is constantly active, so when you press any key by itself, it automatically goes to the chat box - including plus and minus.

num pad plus and minus is the fastest way to add and remove counters on cockatrice. As it stands, the alternative is to right click, click add, click remove etc... It's very sluggish and not practical for speed.

HOWEVER, if you bind plus or minus ALONG WITH shift, control, or alt... it works fine... Unfortunately those binds are best used for plus/minus of power and toughness.

So as it stands, the problem is either being unable to bind JUST plus and minus, OR, the "auto chat" feature you guys implemented 2 patches ago. 

If you could please REMOVE plus and minus from going to auto text when set to key binds, that would be GREATLY appreciated.

I pay $10-$20 every 6 months, and this is the first request I have made... Thanks so much! =)

**Comment by Nightfirecat** [comment] 2016-11-02 09:17
Duplicate of #1902.

**Comment by Daenyth** [comment] 2016-11-02 12:02
> I pay $10-$20 every 6 months, and this is the first request I have made

Just to make it totally clear: The software project itself doesn't accept donations. I'm assuming you're donating to woogerworks, which does accept donations because hosting the server costs money. This isn't a suggestion to stop - we really appreciate anyone helping the community. I just want to make clear that woogerworks is separate from the project itself.

You can read our full stance on donations here: https://github.com/Cockatrice/Cockatrice/wiki/Donations

---

Closing as dupe

**Closed by Daenyth** 2016-11-02 12:02 UTC
