### ISSUE TITLE
"giant killer" count as an instant

### ISSUE THREAD

**Issue by adrienrapper** [Cockatrice/Cockatrice#4313] opened 2021-04-15 03:18 UTC
Hello dear cockatrice developer!

At the moment the "giant killer" is count as an instant instead of as an creature.

Thanks much!
Regard!
Adrien Estevez

**Comment by tooomm** [comment] 2021-04-15 07:27
What version of Cockatrice are you running?
Can you please update your card data to the most recent version as well?
(Both in the `Help` menu)

Should look like this:
![giantk](https://user-images.githubusercontent.com/9874850/114830606-ac079780-9dcc-11eb-9958-705b0b3630d4.png)

**Comment by adrienrapper** [comment] 2021-04-15 10:30
![cockatrice issue](https://user-images.githubusercontent.com/78217728/114855418-3ad4de00-9de6-11eb-89cb-6fe6d4475eab.jpg)

i had updated card/client and the issue still there.
as u can see it make confuse when deckbuilding.
Thanks!

**Comment by tooomm** [comment] 2021-04-15 10:47
As you may realised my screen only addressed the card details in the **description** or **both** tab of the card info widget.

What does it display there for you?

**Comment by adrienrapper** [comment] 2021-04-15 10:50
oh sorry!
this
![cockatrice issue](https://user-images.githubusercontent.com/78217728/114857917-1e867080-9de9-11eb-9084-f572a9d4b248.jpg)

**Comment by ebbit1q** [comment] 2021-04-15 13:50
duplicate of https://github.com/Cockatrice/Cockatrice/issues/4241
fixed in  #4244

**Closed by ebbit1q** 2021-04-15 13:50 UTC
Labels: Bug

**Comment by tooomm** [comment] 2021-04-15 15:52
@adrienrapper The mentioned fix is not yet in the beta channel.
Make sure to switch in your settings to `Beta Releases` and check for updates from time to time to receive it quicker!

Thanks for the report though.

**Comment by adrienrapper** [comment] 2021-04-16 01:32
> @adrienrapper The mentioned fix is not yet in the beta channel.
> Make sure to switch in your settings to `Beta Releases` and check for updates from time to time to receive it quicker!
> 
> Thanks for the report though.

okay
you're welcome!

**Comment by adrienrapper** [comment] 2022-07-01 01:35
the issue still there in the stable release with giant killer
but it is fixed with beanstalk giant

thanks you!

**Comment by ebbit1q** [comment] 2022-07-01 12:16
that's because this change still isn't in the stable release, 2.8.0 is from 2021-01-26
