### ISSUE TITLE
personal messaging an offline user

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#1935] opened 2016-04-11 19:21 UTC
When you pm a user who is online and are typing, but they leave nothing tells you so. Instead you finish typing and press enter to see you words vanish but not appear in the message box.... When you are actively chatting and  the other party leaves you get that message "so and so has left server"  I think we should be able to receive this message whenever a user we are currently typing to goes offline.

**Comment by Nightfirecat** [comment] 2016-04-11 20:26
Duplicate of #1744?

**Comment by Jinxstands4Jinx** [comment] 2016-04-11 21:10
no, He was trying to message people offline. I mean people who go offline before you finish typing

**Comment by skwerlman** [comment] 2016-04-11 21:21
both cases would be solved the same way, so its a dupe

**Comment by Jinxstands4Jinx** [comment] 2016-04-11 21:25
they are 2 separate things though. 1 is trying to pm users who are offline. 2. is pming users online but they leave before you finish typing.

**Comment by Nightfirecat** [comment] 2016-04-11 21:42
But if you were able to send PMs to offline users, would that solve the issue?

**Comment by Jinxstands4Jinx** [comment] 2016-04-11 21:45
well at this time we cannot even pm a offline user as the option is not present. But can pm a user and if they leave the server while we are still typing, we have no clue. That was what I was getting at. I was unaware of the other issue brought up.

**Comment by ZeldaZach** [comment] 2017-03-04 08:02
Upon review I consider this a dupe. will look into this at some point

**Closed by ZeldaZach** 2017-03-04 08:02 UTC
