### ISSUE TITLE
"Invalid username" -.-

### ISSUE THREAD

**Issue by TheAller** [Cockatrice/Cockatrice#1170] opened 2015-06-25 23:49 UTC
Hi,

I can't log in on Cockatrice as I'm told my username is invalid. My username is "Aller" and I've been using it for ages. As you can see, there's no special character in my username, just letters. 

How is this possible and what can I do? I had to play for an online tournament so I'm a bit frustrated.

**Comment by Daenyth** [comment] 2015-06-25 23:59
cc @poixen @woogerboy21 @ZeldaZach

**Comment by Daenyth** [comment] 2015-06-25 23:59
Can you post a screenshot? What server is this on, woogerworks?

**Comment by ZeldaZach** [comment] 2015-06-26 00:00
In client sign-ins aren't my business directly, but I'll be more then happy to assist with this issue.

**Comment by Daenyth** [comment] 2015-06-26 00:05
Sorry, I thought I remembered you working on the username configuration lately. It probably depends what version is deployed on the server and how they have it configured.

**Comment by TheAller** [comment] 2015-06-26 00:13
Here are the screenshots!


![screenshot 01](https://cloud.githubusercontent.com/assets/13056875/8368314/e7f7cec4-1ba8-11e5-99bd-6e67c34c1b33.jpg)
![screenshot 02](https://cloud.githubusercontent.com/assets/13056875/8368315/e7fbf350-1ba8-11e5-893a-4a607359878b.jpg)

**Comment by Daenyth** [comment] 2015-06-26 00:15
Strange hunch, can you try copy/pasting the following text for your username: `Aller`

Then try to reconnect.

**Comment by TheAller** [comment] 2015-06-26 00:20
I tried but the result is the same.

Anyway thank you guys, even in case you won't be able to help me, I have to say I didn't expect you to be so efficient! You answered very quickly.

**Comment by Daenyth** [comment] 2015-06-26 00:30
I think we might need @woogerboy21 to chime in with the current server configuration or commit version. Username permissions have changed a lot recently

**Comment by woogerboy21** [comment] 2015-06-26 00:36
Instead of using the server name cockatrice.woogerworks.com can you attempt to log in dedi001.woogerworks.com and dedi002.woogerworks.com and let me know the results of both connection attempts?

**Comment by TheAller** [comment] 2015-06-26 00:48
Tried both. And the result is..."Invalid username". :D

**Comment by ian-fox** [comment] 2015-06-26 00:58
Getting the same thing with username "Zavec". 

Also tried dedi001 and dedi002.

**Comment by ian-fox** [comment] 2015-06-26 01:05
Was able to log in with unregistered username "Testing." 

Tried changing my password when attempting to login as "Zavec" to an incorrect password, still got the dialog about the username. 

Registered a new account, that one worked as expected.

**Comment by woogerboy21** [comment] 2015-06-26 01:27
So the issue is that the value's that @poixen defined in the .ini do not match what was hard coded in the server code before the name restrictions were moved out to the .ini file.  The minimum character length is set 6 in the INI file were as it wasnt restricted to that minimum of a character set when hard coded.

**Comment by woogerboy21** [comment] 2015-06-26 01:28
it will take a server restart for me to change things and it take affect (as far as im aware).  Unless @ctrlaltca has any magic i dont know about to re-read the .ini settings for user name restrictions

**Comment by TheAller** [comment] 2015-06-26 01:30
So, tell me if I'm right, the issue is the username's lenght? Aller is 5 letters and I would need at least 6, is that right?

**Comment by woogerboy21** [comment] 2015-06-26 01:31
With the current settings yes, i've reduced the config to require 4 but the changes wont take affect till i restart the server which will need scheduled at this point.

**Comment by TheAller** [comment] 2015-06-26 01:33
Right. And do you have an idea about when the server will be restarted?

**Comment by ian-fox** [comment] 2015-06-26 01:33
Thanks for sorting this out so quickly, Wooger!

**Comment by woogerboy21** [comment] 2015-06-26 01:34
once i get some other things in place I will issue the server restart shutdown timer. Maybe by morning

**Comment by woogerboy21** [comment] 2015-06-26 02:49
Try logging into the cockatriceeu.woogerworks.com server now and see if it lets you in.

**Comment by ArbiterLam** [comment] 2015-06-26 02:49
This issue actually affects me too. My username is only 3 characters long.

**Comment by woogerboy21** [comment] 2015-06-26 02:50
Yup, try to log into the EU server and verify you can get in.

**Comment by ArbiterLam** [comment] 2015-06-26 02:51
Verified. I can sign on cockatriceeu.woogerworks.com

**Comment by woogerboy21** [comment] 2015-06-26 03:21
A restart on our US server is scheduled for midnight EST time.  You guys should be able to log in about 5-10 minutes after that.  Any users with names less than 3 characters will require a name change going forward.

**Comment by ArbiterLam** [comment] 2015-06-26 03:23
Thanks for the update. I'm glad the minimum was changed to 3 characters.

**Comment by woogerboy21** [comment] 2015-06-26 04:00
Both sites should be fixed now.

**Comment by ArbiterLam** [comment] 2015-06-26 04:05
Confirmed. I can log in. Thanks!

**Closed** 2015-06-26 04:10 UTC
Labels: Servatrice, Troubleshooting

**Comment by Daenyth** [comment] 2015-06-26 13:40
I'm not sure why the minimum isn't 1 character, but eh *shrugs*

**Comment by woogerboy21** [comment] 2015-06-26 13:44
I don't like the idea of a single character username. Honestly I thought about a 4 character minimum and a more restrictive maximum. Later on I may change the restrictions. I know it can be a pain for précis ting users though.
