### ISSUE TITLE
Issue with viewing top cards of library.

### ISSUE THREAD

**Issue by NicholasRHammond** [Cockatrice/Cockatrice#4228] opened 2021-01-26 21:09 UTC
<b>System Information:</b>
  

Client Version: 2.7.2 (2019-08-31)
addCounter: "Player 1" 0 "life"
addCounter: "Player 1" 1 "w"
addCounter: "Player 1" 2 "u"
addCounter: "Player 1" 3 "b"
addCounter: "Player 1" 4 "r"
addCounter: "Player 1" 5 "g"
addCounter: "Player 1" 6 "x"
addCounter: "Player 1" 7 "storm"
PictureLoader: cache fail for "_trice_card_back_158223"
QPixmap::scaled: Pixmap is a null pixmap
QGraphicsLinearLayout::insertItem: cannot insert null item
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
QGraphicsLinearLayout::insertItem: cannot insert null item
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 2 cols= 2
reorganizeCards: rows= 3 cols= 2
reorganizeCards: rows= 3 cols= 2
ZoneViewZone destructor
CardZone destructor:  "deck"
ZoneViewZone destructor
CardZone destructor:  "deck"
Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 1
Server_CardZone destructor: "deck"
Server_CardZone destructor: "grave"
Server_CardZone destructor: "hand"
Server_CardZone destructor: "rfg"
Server_CardZone destructor: "sb"
Server_CardZone destructor: "stack"
Server_CardZone destructor: "table"
Server_Game destructor: gameId= 1
Player destructor: "Player 1"
GameScene::removePlayer name= "Player 1"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Server::removeClient: name= "Player 1"
closed session id: 0
Server::removeClient: removed 0x2cdbb186840 ; 0 clients;  0 users left
Server_Room destructor
PictureLoader: cache fail for "_trice_card_back_226458"

  
_______________________________________________________________________________________

  

To reproduce the bug:
Create a Cockatrice game, local or online.
Look at the top 1 card of your library using CTRL+W, or right clicking.
Without closing this window, now use CTRL+W or right click to look at the top 2+ cards of your library.
When you manipulate the cards in the window, it causes the following bugs:

- Cards that are removed from this window are not visually removed from the window.
- Rearranging cards in this window does rearrange the cards (according to the chat log), but does not visually rearrange the cards inside the window.
- If you remove a card from this window, the deck order updates, but the cards do not, this results in the ability to take cards out of your library deeper than you looked. (For example, taking the 2nd card and then taking the 2nd card again will give you cards in positions 2, and 3 in your library. This will leave card in position 1 on top). This interaction is documented in the chat as "Player 1 put a card from their library into their hand".
- Spectators and replays cannot see the new, larger window. This means verifying player actions is impossible.

Suggested fix:

Current functionality says that if you have a window of size 1, and try to open another window of size 1, it closes. I would recommend making it so that any time you try to open a window of any size, it will close the window instead of trying to jump to a new window size. It seems that the "check for already open window" only applies if you have a window of the same size already open.

**Comment by ebbit1q** [comment] 2021-01-26 22:20
I noticed your version is out of date (2.7.2, see latest version here https://github.com/Cockatrice/Cockatrice/releases)
I cannot reproduce your issue on the latest version or on version 2.7.2, could you provide your log on startup that includes the details about your system configuration?

**Comment by NicholasRHammond** [comment] 2021-01-26 23:49
I've reproduced the bug on 2.7.5 using the same steps listed above.

Below is a copy of the startup log.  Let me know how else I can be of assistance.
_______________________________________________________________________________________
Client Version: 2.7.5 (2020-08-23)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "VelvetMarble"
SoundEngine: enabling sound
Sound theme changed: "Default"
SoundEngine: enabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_226178"
PictureLoader: cache fail for "_trice_card_back_226180"
Spoiler Service Online
Data Hash = "\xCE\xE5\xB7\x17\xCE\b\beT\xCA\xAB\xD0\xDC\xD6\xC0{"
File Hash = "\xCE\xE5\xB7\x17\xCE\b\beT\xCA\xAB\xD0\xDC\xD6\xC0{"
Spoilers Up to Date
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 21696 Sets= 517
[CockatriceXml4Parser] Trying to parse:  "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 22194 Sets= 518
[CockatriceXml4Parser] Trying to parse:  "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 22497 Sets= 519
[CockatriceXml4Parser] Trying to parse:  "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/customsets/ExpandedKingdoms.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/customsets/ExpandedKingdoms.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nicho/AppData/Local/Cockatrice/Cockatrice/customsets/ExpandedKingdoms.xml" Status = 0 Cards = 22549 Sets= 521
CardDatabase::loadCardDatabases success

**Comment by ebbit1q** [comment] 2021-01-30 22:16
after reading your report again I managed to recreate the issue, after disabling the automatic closing of views it shows that it'll only ever update the most recent one while the old views can still be interacted with.
this shows that there is a bug that causes views to not update after they are opened and closed at the same time like in this case.
if we were to use your fix of just not reopening them we'd just make the chance of it happening smaller but still present.

**Comment by ebbit1q** [comment] 2021-01-30 22:20
also, it does not resize the window but it destroys and reopens it, related code is here https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/gamescene.cpp#L150

**Comment by ebbit1q** [comment] 2021-02-20 21:35
@NicholasRHammond would you be able to test if this change fixes your issue? https://github.com/Cockatrice/Cockatrice/actions/runs/583220516

you can find the downloads under "artifacts", this version is compatible with online play

**Comment by NicholasRHammond** [comment] 2021-02-20 22:48
By my tests, this resolves the issue. While all windows are open, I was unable to find any bugs. When you close one of the windows, there is a bug (albeit minor) that I found.

Reproduction steps:

1. Open a window of size 1.
2. Open a window of size 2.
3. Close one of the two windows.
4. Play a card from the remaining window face down.
5. Return that card to the window.
6. It is now face down inside the window.

If you open another window, this bug is eliminated. It only exists after you have closed a window and there is still more than one window open. Even if you open four windows, close two, and open one more, the bug is eliminated until you close one window. It only exists in the state immediately after closing one of the library windows.

**Closed** 2021-03-13 19:43 UTC
Labels: Bug, Defect - Basic, Low Priority
