### ISSUE TITLE
Add a Button to Flip/Rotate Cards like in Archidekt

### ISSUE THREAD

**Issue by issa-puppi** [Cockatrice/Cockatrice#5256] opened 2024-12-17 05:42 UTC
Would be nice if similar to "view related cards" we had a button to rotate battles and rooms sideways for easier reading

Would be nice if it would be both in card info and in deck editor.

**Comment by BruebachL** [comment] 2024-12-18 18:09
Duplicate of [#479](https://github.com/Cockatrice/Cockatrice/issues/479) but will be added very soon with PR [#5264](https://github.com/Cockatrice/Cockatrice/pull/5264).

**Closed** 2024-12-22 01:44 UTC
Labels: Feature Request
