### ISSUE TITLE
Remember last-used text in token creation form

### ISSUE THREAD

**Issue by mcandre** [Cockatrice/Cockatrice#447] opened 2014-11-19 19:19 UTC
I play a lot of decks with Human tokens, so it would be helpful if Cockatrice pre-populated the Token generation form with the last values I used for each part.

**Comment by ZeldaZach** [comment] 2015-07-08 04:42
This is a dupe of #413 for sure. using `CTRL + G` will copy the last token.

**Closed by ZeldaZach** 2015-07-08 04:42 UTC
