### ISSUE TITLE
Token Stacking Positions Bug

### ISSUE THREAD

**Issue by jonidcrushfire** [Cockatrice/Cockatrice#4546] opened 2022-01-29 15:34 UTC
I am trying to move a token into a position between two other cards, but it keeps stacking to one card or the other and will not go into the open slot. Please see the screenshot.

I am running this on Windows 11 with a fresh install of Cockatrice. I believe it is the current client (I used the Help->Check For Client Updates menu option).

I looked through the open issues page, and saw that there was a bug for the cards in a previous version, but this is specifically tokens I am having the issue with.

Please let me know what you need to check this.
![Token Position Bug](https://user-images.githubusercontent.com/69694379/151666940-31fa00a7-333a-403b-8a87-a975f01908c4.png)

**Comment by jonidcrushfire** [comment] 2022-01-29 15:37
Update: It seems like I have to move the token an extra empty position to the right of where I want it to go to get it to move into the first open space. Also, when it is stacked with a card, moving the card moves the token as if it is attached.

**Comment by ebbit1q** [comment] 2022-01-29 16:52
duplicate of https://github.com/Cockatrice/Cockatrice/issues/4235 fixed in https://github.com/Cockatrice/Cockatrice/pull/4236

this bug is only present in local games, please use the beta version if you'd like to use a version that includes this fix

**Closed by ebbit1q** 2022-01-29 16:52 UTC
