### ISSUE TITLE
Improve theme handling 

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2123] opened 2016-08-05 20:18 UTC
<b>OS:</b>
Win 7 SP1

<b>Cockatrice version:</b>
~~Why is it still impossible to load anything in the about menu into clipboard. Why does it behave like an extra window when using alt+tab, yet doesn't pop up on the taskbar. Sigh~~ fixed
277d7e2

---

Firstly, when updating the Themes folder (which I keep in the install directory along with all other folders) gets deleted. I've had a backup of everything cockatrice-related aside from the actual application for years now, but I can easily see it ruining a day or two. 

Secondly, why is a "themes" option not present in the settings under paths anyway? Could it be implemented?
~~PS: Is "filter buddies only" a feature not yet available or am I doing something wrong.~~ fixed

**Comment by Daenyth** [comment] 2016-08-05 21:03
> Why is it still impossible to load anything in the about menu into clipboard. 

Works for me on osx. It must be something windows specific.

> Firstly, when updating the Themes folder (which I keep in the install directory along with all other folders) gets deleted.
The one in Program Files? This is intentional - users aren't supposed to put anything in there, it's for the bundled default themes.

> Secondly, why is a "themes" option not present in the settings under paths anyway? Could it be implemented?
Yes, this is completely reasonable.

> PS: Is "filter buddies only" a feature not yet available or am I doing something wrong.
Could you be more specific? Maybe in a new ticket?

**Comment by ctrlaltca** [comment] 2016-08-06 10:40
> Secondly, why is a "themes" option not present in the settings under paths anyway? Could it be implemented?

From the actual documentation available at https://github.com/Cockatrice/Cockatrice/wiki/Themes:

> Non-default themes should be placed in the following locations. Create this directory if it doesn't exist.

> Windows: C:\Users\USERNAME\AppData\Local\Cockatrice\Cockatrice\themes
> Linux: ~/.local/share/data/Cockatrice/Cockatrice/themes
> Mac OSX: ~/Library/Application Support/Cockatrice/Cockatrice/themes

**Comment by tooomm** [comment] 2016-08-06 20:45
>>Why is it still impossible to load anything in the about menu into clipboard.

>Works for me on osx. It must be something windows specific.

That's very nasty and has been around for ages on windows. :(
Same problem with the card info widget for example, it's not possible to select the name of a card there!

**Comment by Daenyth** [comment] 2016-08-07 10:28
Maybe it's a Qt thing?

**Comment by LethalPigeon7** [comment] 2016-08-08 14:59
> More generally, what do we gain from letting the user change the path for folders like "themes", "decks", etc.. instead of putting the files in the correct place inside the cockatrice profile?

I mean, much like a notable portion of any UI in general, it makes things simpler to learn and easier to use.

**Comment by LethalPigeon7** [comment] 2016-08-08 15:05
> Could you be more specific? Maybe in a new ticket?

Well, I'm on the version I quoted and I don't have the buddies only filter available. I'd downloaded what I'd thought to be the newest version of cockatrice off the official download site. I haven't made a new ticket since I assumed the feature either isn't on the public version, or I'd simply messed up along the way.

**Comment by ctrlaltca** [comment] 2016-08-09 09:21
> Why is it still impossible to load anything in the about menu into clipboard. Why does it behave like an extra window when using alt+tab, yet doesn't pop up on the taskbar.
> Sigh

Reported in #1762, hopefully fixed in #2125

**Comment by ctrlaltca** [comment] 2016-08-09 09:25
> I have decks in a folder which can be accessed with one click

I fail to understand how it's simpler to put the folder on the desktop and than having to enter cockatrice settings and make it point to that specific folder, when you can just have cockatrice handle the decks folder for you and just add a link to it on the desktop, if you care about accessing it with a file manager.

**Comment by Daenyth** [comment] 2016-08-09 11:09
We can support a config for it. It's not simpler but it is more user
friendly. I can see wanting to put such a thing in Dropbox for multiple
computers

**Comment by tooomm** [comment] 2016-08-09 11:46
>I haven't made a new ticket since I assumed the feature either isn't on the public version, or I'd simply messed up along the way.
If buddies only are supposed to be included in Archivist Madness, and that is the newest version I'll be happy to make an individual ticket

It's not present yet in the newest main release. You need to use a development version.
You can find it here: https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/0.0.1%7Egit20160809.ac841ee#files
But don't be too excited, it *just* filters for the flag `buddies only`, i doesn't consider your personal buddy list. But it'll still help you a lot if you're looking for such a game since there are just a few at a time.

**Comment by LethalPigeon7** [comment] 2016-08-12 12:16
Thanks tooomm, a dev version was precisely what I was hoping for, once I confirm it isn't a bug. I think the complete buddies only flag is releasable. Considering a personal buddy list sounds complicated (but what do I know - not sarcasm, I honestly dont know how hard it is to implement) and more importantly ultimately useless. If I want to play with a buddy I usually right click their name anyway. Not saying it shouldn't be implemented, just that the global filter seems more than sufficient.

**Comment by ZeldaZach** [comment] 2020-10-06 22:39
Dupe of #4087

**Closed by ZeldaZach** 2020-10-06 22:39 UTC
Labels: OS - Windows, Troubleshooting
