### ISSUE TITLE
Arrows are causing my Cockatrice games to crash.

### ISSUE THREAD

**Issue by elbenji** [Cockatrice/Cockatrice#1925] opened 2016-04-09 14:35 UTC
<b>OS:</b>
OSX 10.8.5

<b>Cockatrice version:</b>
Version 8d67c75 (2016-04-08)

___
<br>

Anytime someone points or draws an arrow, my Cockatrice application crashes. Can't get a bug report, but it just stops working and wont start working again until the game I was in ends.

**Comment by leematos** [comment] 2016-04-09 15:02
Thanks! This is a dupe of https://github.com/Cockatrice/Cockatrice/issues/1857 Which in short, our new builds don't support 10.8.5. You can read through that ticket for more information.

**Closed** 2016-04-09 16:46 UTC
