### ISSUE TITLE
Replays crash the applicatio

### ISSUE THREAD

**Issue by joca-bt** [Cockatrice/Cockatrice#1508] opened 2015-09-12 21:19 UTC
Whenever I try to watch a replay the application crashes. I'm running version 60ed9fb of 2015-09-03 on Windows 8.1 x64.

**Comment by ctrlaltca** [comment] 2015-09-12 21:23
Duplicate of #1464. We already fixed this, please wait until the new version is out. Thank you.

**Comment by joca-bt** [comment] 2015-09-12 21:23
Sorry and thanks!

**Closed by ctrlaltca** 2015-09-12 21:23 UTC
