### ISSUE TITLE
Opening library bug

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#908] opened 2015-04-03 19:34 UTC
Press F3 to open your library, then quickly press escape (before the card images have shown up). After doing this, some of the library manipulation commands won't work. F3 to open your library will just produce an empty box, as will crtl-W. Attempting to draw cards or undo draws will have no effect. Current workaround: if you spam enough commands (alternate pressing draw and undo draw 3 times), the bug will go away.

**Comment by ZeldaZach** [comment] 2015-04-03 20:07
I just tried replicating and I was hit by the flood warning. Maybe you're not on the newest client and you're not being informed of the flood notice?

Try updating and lets see what happens :)

**Comment by poixen** [comment] 2015-04-03 20:39
I cant reproduce this either.

**Comment by anoda9** [comment] 2015-04-07 03:50
After updating, I get the flood warning as well. However, the bug still occurs. I'm on mac, maybe that matters?

**Comment by Daenyth** [comment] 2015-04-07 13:09
I suspect what happens is the client opens the window when you send the
command and populates it when it gets the answer, but now the answer is
flood protection instead of cards

**Comment by poixen** [comment] 2015-04-12 15:55
I have looked into this.

It is like @Daenyth has said, when you perform to many commands, flood protection kicks in and stops you from viewing your deck, drawing cards, and alot more actions. 

This behaviour is as intended. 

Solution: dont spam requests :+1: 
Closing issue.

**Closed** 2015-04-12 15:55 UTC
Labels: Cockatrice, Troubleshooting
