### ISSUE TITLE
Save game list columns states

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1911] opened 2016-04-06 18:20 UTC
@ctrlaltca fixed the card database view in https://github.com/Cockatrice/Cockatrice/pull/1900.

Should be the same behavior for the game list column states!

**Comment by Daenyth** [comment] 2016-09-26 19:20
Closing this as a dupe of #2152 since that has more clear details

**Closed by Daenyth** 2016-09-26 19:20 UTC
