### ISSUE TITLE
Files (mostly themes) not deleted on uninstall.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1546] opened 2015-09-21 06:24 UTC
On uninstall, the Cockatrice directory remained. It still contained:

* libmysql.dll
* themes\
* themes\Default
* themes\Fabric
* themes\Leather
* themes\Plasma
* themes\VelvetMarble

If these are customisable, they shouldn't be in the application directory. They should be in user space with decks.

**Comment by woogerboy21** [comment] 2015-09-21 10:28
I believe leaving the themes folder is by design sp themes in general are not removed between uninstall/installl. I know I wouldnt want themes Ive created destroyed.

**Comment by Daenyth** [comment] 2015-09-21 10:59
We should remove the dll and default theme folders but not user configured
themes

**Comment by ctrlaltca** [comment] 2015-09-21 13:05
Yup, this needs to be fixed in the nsis script

**Comment by Psithief** [comment] 2015-09-21 15:30
This still leaves the problem that themes are in an admin-only directory `Program Files (x86)\Cockatrice`. They need to be in `%localappdata%` with decks, replays, `cards.xml`, etc.

**Comment by Daenyth** [comment] 2015-09-21 15:34
The themes we distribute aren't intended to be modified, they're
intended to be copied into the user local data folders and changed
there.

**Comment by Psithief** [comment] 2015-09-21 15:39
Okay. I see the issue now: I haven't updated my application settings in a while so I don't have a blank themes directory.
:+1:

**Closed** 2016-03-30 20:55 UTC
Labels: App - Cockatrice, Cleanup
