### ISSUE TITLE
problems with card database

### ISSUE THREAD

**Issue by julilluss** [Cockatrice/Cockatrice#4066] opened 2020-08-15 17:21 UTC
Hi, I uploaded cockatrice and oracle database, using the following link:
for oracle: https://www.mtgjson.com/files/AllPrintings.json.xz

but this link doesn't contain some sets like Urza's saga, Urza's legacy, shodowmoon, and others..

I tried to search another link that contains those sets but i failed..

Is there some way to load ALL the existing sets?, I don't know when this problems starts, but I noticed when I searched for a specific card (necrotic ooze).

Many thanks for your help.

Regards
<img width="647" alt="Captura de Pantalla 2020-08-15 a la(s) 13 19 56" src="https://user-images.githubusercontent.com/69728693/90317845-332d0480-defa-11ea-9abd-d46d2486e3fe.png">
<img width="488" alt="Captura de Pantalla 2020-08-15 a la(s) 13 20 25" src="https://user-images.githubusercontent.com/69728693/90317848-36c08b80-defa-11ea-9371-573c6a724105.png">
![Captura de Pantalla 2020-08-15 a la(s) 13 20 47](https://user-images.githubusercontent.com/69728693/90317850-3b853f80-defa-11ea-8ffa-d22282e64560.png)

**Comment by tooomm** [comment] 2020-08-15 17:56
Duplicate of https://github.com/Cockatrice/Cockatrice/issues/4065?

**Closed** 2020-08-15 22:15 UTC

**Comment by julilluss** [comment] 2020-08-15 23:59
Yes, didn't notice that there was another case opened.. So, is there a fix for that?

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tooomm** [comment] 2020-08-16 07:15
Try rerunning Oracle.
I think the mtgjson file is fixed.

**Comment by julilluss** [comment] 2020-08-17 13:11
Many thanks, the problem is fixed now.

Regards
[Banner]<http://firma.sixbell.com/Transformate/%7BbannerURL%7D>
[Logo]<http://firma.sixbell.com/Transformate/%7BlogoURL%7D>
Julio Reyes Pulgar
Ingeniero Especialista CC       T: +56 2 2200 1200
<tel:5552463289>M: +56 9 6300 7336
<tel:5554385034>@: julio.reyes@sixbell.com
<mailto:itzel.moyano@sixbell.com>       [Facebook icon] <https://www.facebook.com/sixbell.cl/>  [LinkedIn icon] <https://www.linkedin.com/company/sixbell>  [Twitter icon] <https://twitter.com/sixbell_corp>  [Youtube icon] <https://www.youtube.com/user/sixbellnekotec>  [Instagram icon] <https://www.instagram.com/sixbellcorporativo>
[X]www.sixbell.com<https://www.sixbell.com/>

“El presente mensaje es confidencial, dirigido únicamente para el o los destinatarios.
Si usted no es el destinatario, no deberá copiarlo, revelarlo o distribuirlo.
Cualquier acción realizada en este sentido, será ilegal.
Si por error recibe el presente mensaje, por favor notifique al remitente.

This communication is confidential and intended only for the addressee.
If you are not the intended recipient, you shall not copy, disclose
or distribute this message toanyone else any such actions may be unlawful.
If you have received this communication in error, please contact the sender
of the message to inform him or her of the error.”

El 16-08-2020, a las 03:16, tooomm <notifications@github.com<mailto:notifications@github.com>> escribió:



Try rerunning Oracle.
I think the mtgjson file is fixed.
