### ISSUE TITLE
pop-up window jumps around in single player when dragged around the screen

### ISSUE THREAD

**Issue by hashbert** [Cockatrice/Cockatrice#5000] opened 2024-02-13 02:03 UTC
**System Information:**

Microsoft Windows 11 Home
_______________________________________________________________________________________

Any 
https://github.com/Cockatrice/Cockatrice/assets/58117985/19e88837-af26-4662-a189-d27f3afb3a25

_______________________________________________________________________________________

**Steps to reproduce:**

View hand, view library, view sideboard, view graveyard, or view exile in single player. Drag the pop-up window around the screen. Witness bugginess.

**Comment by ebbit1q** [comment] 2024-02-19 23:17
duplicate of https://github.com/Cockatrice/Cockatrice/issues/2707 please comment on existing tickets before opening new ones

**Closed by ebbit1q** 2024-02-19 23:17 UTC
Labels: Bug
