### ISSUE TITLE
Tokens not showing up

### ISSUE THREAD

**Issue by mark6574** [Cockatrice/Cockatrice#1801] opened 2016-02-08 21:02 UTC
I downloaded the separate tokens.xml file and put it in the default place (C:\Users\Me\AppData\Local\Cockatrice) but they are not showing up at all.  Not sure what I am doing wrong.  I don't see any tokens, emblems, etc.  When I am in the Deck Editor and I try to Edit Tokens under the Card Database tab, nothing is there.  When I first installed the program they were all there, but after one of the latest updates they are missing.

**Comment by ctrlaltca** [comment] 2016-02-09 07:42
Oracle can download the file for you and place it in the right place, can you try giving oracle a run?
Can you also check the "token" path from the cockatrice settings?

**Comment by mark6574** [comment] 2016-02-10 20:42
I did use the automatic updater to let Oracle download it...  It was saved
to the default folder: C:\Users\Me\AppData\Local\Cockatrice\tokens.xml

It's in the same folder as the cards.xml and all the cards show up just
fine.  At some point, the tokens stopped working and I don't know when.  I
haven't played with any of the settings.

I tried the updater against and it still isn't showing up.  Opening up the
.xml file shows that the correct data is listed.

**Comment by ctrlaltca** [comment] 2016-02-11 07:12
Can you try from the deck editor: menu "card database" -> "edit sets", search the "TK" set (dummy set containing tokens), try to enable it

**Comment by Gianluca90** [comment] 2016-03-03 21:44
I had the same problem, so I checked and see that I was using an old version of Cockatrice. I installed the latest version and the token worked again!

**Comment by tooomm** [comment] 2016-03-08 15:46
@mark6574 
What's the state of this? Do you still encounter problems?
Did you try to check if the `TK` dummy token set is enabled as ctrlatlca described in his last reply?

You also did not reply if the location which Oracle saves the `token.xml` file to is the same as in you settings:
![token db](https://cloud.githubusercontent.com/assets/9874850/13606657/18468cb4-e54d-11e5-9454-2874a7f151f5.png)

We would be happy investigate further and help you out, or to close this issue in case it's solved... Please let us know!

**Comment by Daenyth** [comment] 2016-03-13 01:27
I think this is a duplicate of #1810

**Closed by Daenyth** 2016-03-13 01:27 UTC
Labels: Troubleshooting
