### ISSUE TITLE
Deck builder should delete filters by pressing delete

### ISSUE THREAD

**Issue by JoshuaLamusga** [Cockatrice/Cockatrice#2950] opened 2017-12-12 21:37 UTC
It would be nice if filters in the deck builder could be removed by pressing delete. It would be more consistent with the behavior of the deck list, which allows the user to press delete to remove a card.

Interestingly, if a card in the deck list is selected and the user clicks a filter and presses delete to remove it, the highlighted card is deleted. Someone may need to remove focus from the deck list when the filter list gains focus (and vice versa).

**Comment by tooomm** [comment] 2017-12-18 17:10
#2959 added delete filter on `Backspace` 👍 

Not exactly what this issue asks for (delete on `Delete`), also leaving out the mentioned problem:
>It would be nice if filters in the deck builder could be removed by pressing delete. It would be more consistent with the behavior of the deck list, which allows the user to press delete to remove a card.
>
>Interestingly, if a card in the deck list is selected and the user clicks a filter and presses delete to remove it, the highlighted card is deleted.

**Comment by Daenyth** [comment] 2017-12-18 23:01
apple hardware labels the backspace key as 'delete', so perhaps that's some
of the confusion.

**Comment by ZeldaZach** [comment] 2017-12-18 23:02
Correct, so this PR would only work for the backspace key. I'm fine with it as is.

**Comment by tooomm** [comment] 2017-12-18 23:09
>apple hardware labels the backspace key as 'delete', so perhaps that's some of the confusion.

Good call. Maybe!

But the problem still persists @ZeldaZach, if I hit `Delete` on windows (not backspace...) it deletes cards out of the deck list even if I select a filter... Exactly how @JoshuaLamusga describes in his issue that leads to the request.
Even if the initial issue was from a mac user and it's fixed for him now, it's still an issue for 90%+ of users now. On windows nobody uses backspace to delete selections. We are all set on the proper delete key. ;)

@JoshuaLamusga what system are you running?

**Comment by JoshuaLamusga** [comment] 2017-12-19 02:19
@tooomm Windows 10 Home 64-bit (same as you, right?)

**Comment by tooomm** [comment] 2017-12-19 13:00
@JoshuaLamusga it's "Professional" for me, but yes.

While #2959 is a solution for macOS, this turns into a Windows only issue now.

**Comment by Vafthrudnir** [comment] 2018-02-08 00:24
The problem was trickier than I thought: the default shortcut for removing cards from the deck on windows is the `del` key, which gets processed before the appropriate `eventFilter` call. This causes the `onDelete()` signal to never trigger.
Changing or removing this shortcut in the settings menu solves the problem: pressing the delete key removes filters when that's the focus, or cards when the focus is on the deck list widget.

As a long-term solution I think we should make it impossible to set up shortcuts for such inconvenient keys (this should probably include arrow-keys as well).

**Comment by Daenyth** [comment] 2018-02-08 01:12
That's a good solution

**Comment by tooomm** [comment] 2018-02-08 13:21
Oh wow, really?
The solution is to remove the pre-added shortcut for `Delete card`, which is assigned to <kbd>DEL</kbd>...?

On windows I can confirm that it works then.
If you remove that shortcut on mac, will it still work for filter *and* deck list?

**Comment by Vafthrudnir** [comment] 2018-02-08 13:44
Yes, it should work on Mac as well, because `delete` and `backspace` key-events are handled in both the deckbuilder's and filter's eventfilter functions as well.
The shortcut is actually hooked to the action that is called when you press the `Remove row` button. So when you use it to remove a card it does the same thing, but since shortcuts have priority above eventfilter functions, it can never reach the filter widget's removal mechanism - even if that widget has focus.

Right now I'm working on a checker that only lets you set up shortcuts that are not handled in these eventfilters - that should help us avoid such problems in the future.
Or should only the defaults be changed, and let the users set up any shortcuts they want, even if it messes with other implemented features?

**Comment by Daenyth** [comment] 2018-02-08 20:28
If it's easy to prevent them and you know how to add it, go for it. I feel
like it's not evil to let it break if they put in something with conflicts,
given the limited dev bandwidth we have to make changes. If it's hard to
add the checker, the time may be more valuably spent elsewhere.

**Closed** 2018-02-13 07:51 UTC
Labels: App - Cockatrice, OS - Windows, UI / UX
