### ISSUE TITLE
Support mechanics like Perpetually with permanent annotations

### ISSUE THREAD

**Issue by stengah1** [Cockatrice/Cockatrice#5218] opened 2024-12-02 14:37 UTC
Allow for a toggle that gives either regular cards or tokens to be able to keep their annotations between zone changes to support mechanics from alchemy like perpetually.

**Comment by ebbit1q** [comment] 2024-12-02 17:49
duplicate of https://github.com/Cockatrice/Cockatrice/issues/4404
please leave a comment on exisiting issues instead of opening new ones

**Closed by ebbit1q** 2024-12-02 17:49 UTC
Labels: Feature Request
