### ISSUE TITLE
Impossibile to switch a card from main deck to sideboard by double clicking it in deckeditor

### ISSUE THREAD

**Issue by Locix** [Cockatrice/Cockatrice#2139] opened 2016-08-22 21:38 UTC
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
277d7e2 (2016-06-30)

---

<br>

Hi, as in the title me and my other two friends are having this same problem.

**Comment by Daenyth** [comment] 2016-08-22 23:20
Has this ever worked? I don't recall whether or not that was a feature. Is this a suggestion?

**Comment by Locix** [comment] 2016-08-22 23:47
Sure! I have always used this to quick switching cards from the main deck to the sideboard in the editor, it was really helpful for me, so i can keep track of the cards i want to change in a deck.

**Comment by Locix** [comment] 2016-08-23 02:55
I noticed now that in this version the double click from sideboard to main deck works, but not from main deck to side.

**Comment by tooomm** [comment] 2016-08-23 07:44
You mean the deck list? When you double click on  a card in sideboard it switches to main and vice versa?
Works for me on windows 10...

I'm using a development version though. But there haven't been huge changes in that area.

**Comment by Daenyth** [comment] 2016-08-23 11:27
Can you include the specific version string where it works and doesn't work?

**Comment by Locix** [comment] 2016-08-23 13:02
I installed the version that tooomm suggested, the doubleclick from side to main works, but if I try to doubleclick on a card in main the only thing it does is higlighting the card below that one.

PS: my friends that have this same problem have win 10 like me.

**Comment by ziobbe** [comment] 2017-08-21 16:11
Hi, I want to notify that this is present on different builds I tried (Cockatrice-2.3.17;Cockatrice-2.3.18;Cockatrice-2.3.18-beta004) on my ubuntu gnome 17.04:
When I try to edit a deck and shift cards from the main board to the sideboard (that's a thing I do a lot while building my commander decks) the cursor just skips on the next card or the previous in case it's the last one of a card type, this happens even if i try to use the "s" keyboard shortcut instead of double clicking.
This makes deckbuilding very frustrating to me, if there is a workaround or a software version without this issue I would really like to know.
Thanks for your work and interest.

**Comment by ziobbe** [comment] 2017-08-28 17:05
Since the beaviour happens both while doubleclicking and while pressing the keyboard shortcut :"s" maybe the title of the issue should be change to have a more general meaning.
It seems that all the methods to put a card in the sideboard from the main deck in the deck editor are broken.

**Comment by ziobbe** [comment] 2017-08-28 21:13
2016-06-30-release have this bug
2016-02-03 release "gatewatchers" dont: double clicking regularly takes cards from main to sideboard.

**Comment by Daenyth** [comment] 2017-08-31 11:33
Thanks, that should make it easy to track down exactly when this changed.

**Comment by ziobbe** [comment] 2017-09-04 09:07
=) I have some experience with university level c, can you point me to the files where this function should be so that i can make myself an idea of a real life project and of object oriented programming languages?
I probably won't be able to solve the problem tho XD.

**Comment by ZeldaZach** [comment] 2017-09-07 01:54
@ziobbe A good starting place might be somewhere in the `cockatrice/src/tab_deck_editor`

**Comment by Daenyth** [comment] 2017-09-07 19:36
@ziobbe If you'd like to take a swing at it, I recommend

- Get your dev environment set up so you can compile the code and run what you built. This shouldn't require any knowledge, just following instructions on the wiki.
- Use `git bisect` to find the change we made that introduced the bug. You can use the release tags as the `good` and `bad` starting points. See here for some info on that. http://webchick.net/node/99
- Once we know what commit broke things, we can examine the diff and see if anything jumps out at us as a likely culprit.

**Comment by ziobbe** [comment] 2017-09-14 09:26
I'm still wrapping my head around c++ for now it seems it's ahead of my skills, I will learn more, if I git gud I will surely contribute.
I hope this bug will get solved soon anyway.
For now, thanks for your time and thanks for the assistence!

**Comment by Locix** [comment] 2018-03-25 13:13
Nothing new?

**Comment by Xatrith** [comment] 2018-03-26 15:46
The problem still happens with the 2.5.0.
The last version i used that did'nt have the bug is All Hallows Eve

**Comment by Daenyth** [comment] 2018-03-26 20:16
cc @Vafthrudnir perhaps you might be interested in investigating this?

**Comment by Vafthrudnir** [comment] 2018-03-27 06:40
The feature works fine with version 2.5.0 on my win10. I'll look into the commits between the working and the not working versions, maybe I'll find something.
Though it would simplify the problem if someone who has the bug would use bisect to find the exact commit that caused this.

**Comment by ctrlaltca** [comment] 2018-03-27 07:15
Works for me on both macOS and Windows7.

**Comment by tooomm** [comment] 2018-03-27 09:10
Never understood the problem here. Worked on Win 10 for me all the time basically.
With 2.5.0 I can switch any cards between deck and sideboard via double clicking a card in the `Deck` widget.

No idea what you run into on your Windows 10 @Locix.
@ziobbe only saw it on Linux... Which system do you run Cockatrice on @Xatrith?

**Comment by Locix** [comment] 2018-03-27 09:27
Probably it was me that explained badly, it's simple, when i try to build a deck (not sideboarding while in a match) if i have a card in the sideboard zone and i doubleclick it it swaps to mainboard, but, if that card is in mainboard and i try to doubleclick it it doesn't swap, it just highlights the card below, it was a feature in past version, now it's gone. Sorry again if my english wasn't perfect

**Comment by Vafthrudnir** [comment] 2018-03-27 09:47
I think you explained it clearly enough, but the strange thing is that this feature still works on my computer. Are you using the installed version of cockatrice or the portable one?

**Comment by Locix** [comment] 2018-03-27 09:50
Installed, updated on Win 10 updated, it works all fine but for this one thing.
Even my friends have the same problem

**Comment by tooomm** [comment] 2018-03-27 10:29
>With 2.5.0 I can switch any cards between deck and sideboard via double clicking a card in the `Deck` widget.

The deck widget only exists in the `Deck Editor` and is not available during games or "sideboarding":
![swap](https://user-images.githubusercontent.com/9874850/37961939-ecfe49d2-31b9-11e8-8cdc-e44a3944280e.png)

I think we all understand it correctly and it works for all of us. 😕 
In my example above, if I double click the "Air Elemental" in maindeck, it'll decrease from 3 to 2 and increase from 1 to 2 in the sideboard. Or the other way around.
It won't do nothing or only highlight the Brontodon beneath it as you describe it. I mean... sure, if I move the last Air Elemental that way to my sideboard it'll highlight the next card in the list which is the Brontodon. But that's expected behavior and only happens for the last card in the maindeck. Also, it still moves that last card as it should.

**Comment by Locix** [comment] 2018-03-27 10:40
That's what i forgot to say, i only play commander, so I only have x1 of every card in my deck, maybe this can be useful, but really, it was possible to pass the card from main to side and viceversa only by doubleclicking a x1 card.

**Comment by tooomm** [comment] 2018-03-27 10:45
>it **was possible** to pass the card from main to side and viceversa only by doubleclicking a x1 card.

It **still is** for us, even for single copies of cards (x1). The card moves to sideboard or maindeck and the next one in the list (the one beneath obviously) is highlighted. It should work like that.
Maybe you try it with just a few cards in a deck so that you see that it actually moves. In a commander decks you might just loose track of the card. 😉

**Comment by Xatrith** [comment] 2018-03-27 10:47
For me it's Windows 7 and installed in a non-portative way. I don't know what bisect is but if it does not requiers too much knowledge i can try to do it.

**Comment by Locix** [comment] 2018-03-27 10:52
I just uninstalled, cleaned up and reinstalled, the problem is still here.

**Comment by Locix** [comment] 2018-03-27 11:26
The release before i wrote this issue was working fine

**Comment by Xatrith** [comment] 2018-03-27 11:40
I did not download each release, i have : 
Gatewatchers
Archivist Madness
All Hallows Eve
Decked Out

I suppose i used All Hallows Eve since i downloaded Decked out. I'll uninstall and try to install All Hallows Eve instead to see if the bug is there.

**Comment by Xatrith** [comment] 2018-03-27 11:44
So, did the installing/uninstalling : All Hallows Eve works fine and Decked out still have the bug. An other thing i note is that when i double click a card in Decked out (and that does nothing) and then close the soft, he ask me if i want to save the changes.

**Comment by Vafthrudnir** [comment] 2018-03-27 12:44
Thanks for the info!
So to sum everything up:
- both @Locix and @ziobbe encountered this bug changing from The Shadows (2016-05-08) to Archivist Madness (2016-06-30)
- @Xatrith doesn't encounter the error in either All Hallows Eve (2016-10-30), Archivist Madness (2016-06-30) or Gatewatchers (2016-02-03), but finds it in Decked Out (2018-03-02)
- for @tooomm , @ctrlaltca and me the feature works even in Decked Out
- the bug seems to be OS indifferent: it was encountered on Windows 7, 10 and Ubuntu, but there are examples of the feature working properly on both Windows 7 & 10

I think there could actually be two separate bugs at work: one that was implemented in All Hallows Eve, and one somewhere after that. For some reason both of these only affect a part of the userbase.
I'll check the commits between The Shadows and the Archivist Madness releases, maybe if I can find one of these bugs we'll be able to solve the other one as well.

**Comment by Xatrith** [comment] 2018-03-27 13:14
Ok so i downloaded all the releases since All Hallows Eve and the bugs appears between All Hallow's Eve, Revision 2 and Thopter Pie Network (this last one has the bug)

**Comment by Vafthrudnir** [comment] 2018-03-28 08:20
@Xatrith: you mentioned that the program asks to save changes, which gave me an idea. Could you try the following process with the Decked Out release:
- Load a deck
- Double click a card in mainboard
- Save the changes
- Close and reopen the program
- Load the saved deck
- Check whether the card you double clicked have been moved to the sideboard

**Comment by Locix** [comment] 2018-03-28 08:57
Done it with 2.5.0, nothing changed in the deck.

**Comment by Xatrith** [comment] 2018-03-28 09:43
Same here, no change in the list. But the double click seems to trigger something. At the very least it does something like this : 
If number of the card = 1 select the next card in the deck
If number of the card > 1 select the same card as before

**Comment by Locix** [comment] 2018-03-28 21:05
I just noticed that right and left keys don't add or remove cards anymore

**Comment by Vafthrudnir** [comment] 2018-03-29 04:57
Yeah, in the new release the hotkeys for that have been changed to shift+left and shift+right as requested by issue #2937.

**Comment by ZeldaZach** [comment] 2018-04-01 08:20
While this is an issue that spans across multiple OS's, a prime target for fixes, it doesn't seem like we can do much here.

What we can evaluate is how is it working on the latest version and go from there. Since there's conflicting stories here with it working and it not working, I feel as if there's internal config issues on different systems. Ex: library versions, compilers, system environments, etc.

As such, I'm unfortunately closing this as a **no-fix**.

If anyone has any future plans or ideas on how to better address this, please feel free to. I'd like to thank everyone for contributing towards this project and I hope you keep reporting and/or fixing bugs in the future!

**Comment by Xatrith** [comment] 2018-04-01 10:36
@ZeldaZach Got something ! It's a language problem ! I thought of asking a portable version installed by you. So i did one myself to see if it solve the problem ... and it did ! But when i reloaded it after parameters were set it did'nt work again. Finally , it works in English, but not in french. And i tested : does'nt work either in german, spanish, italian, japanese, korean, portuguese, brazilian portuguese, russian and chinese simplified. That could explain why the bug appears in different versions, it's probably because languages are not updated at the same rate.

**Comment by Locix** [comment] 2018-04-02 22:03
Totally confirm! If i switch to english the problem disappears!

**Comment by Vafthrudnir** [comment] 2018-04-02 22:34
Thanks @Xatrith, that's a great find! With this I could identify the code that causes the problem, working on the solution right now. I expect to be done in the next few days.

**Closed** 2018-04-03 03:04 UTC
Labels: App - Cockatrice, Defect - Regression, UI / UX
