### ISSUE TITLE
Gray box of Obscurity

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2302] opened 2016-12-07 02:30 UTC
<b>OS: macOS 10.12.1</b>

<b>Cockatrice version: 3498b16 (2016-10-30)</b>
___
<br>

How to recreate: Get in a 2 player+ game put some popout windows way over to the right and then do some stuff in game to add to the game log and eventually you'll get a gray box blocking out some of the game log.

![screen shot 2016-12-06 at 9 26 41 pm](https://cloud.githubusercontent.com/assets/6514656/20952551/4a3642e8-bbfb-11e6-85cd-38af13b5adaf.png)

**Comment by Nightfirecat** [comment] 2016-12-07 05:32
Isn't this just a duplicate of your other ticket #2264?

**Comment by ZeldaZach** [comment] 2016-12-07 05:37
Looks like it @Nightfirecat

**Closed by ZeldaZach** 2016-12-07 05:37 UTC
