### ISSUE TITLE
Startup maximized window draws of the screen

### ISSUE THREAD

**Issue by joshuabengal** [Cockatrice/Cockatrice#2151] opened 2016-08-29 01:17 UTC
<b>OS:</b>
Window 7 Pro

__
<img src="http://www.joshuabengal.com/hosted/clip.png">

This is a screenshot of the lower corner of the screen to illustrate. On startup, the app is maximized to a height and width larger than the max resolution of the the screen. Un maximizing and then re maximizing scales the app correctly.  I am on a laptop with a 1024x768 screen res.

**Comment by ZeldaZach** [comment] 2016-08-29 03:49
This is a problem on Macs as well as I've noticed, I just never reported it. Thanks for this!

**Comment by tooomm** [comment] 2016-08-29 08:21
@ZeldaZach: But somebody else did already. :P

Good to know, that it's the same on Mac with Retina display and basically all Windows versions since 7.

**Comment by Daenyth** [comment] 2016-08-29 20:04
I'm pretty sure this is a duplicate ticket. I'm on my phone atm so if
someone can find that to reference is appreciate it. Pretty sure it's
tagged with easy change

**Comment by Daenyth** [comment] 2016-08-29 23:37
Dupe of #1904

**Closed by Daenyth** 2016-08-29 23:37 UTC
Labels: App - Cockatrice, Defect - Basic, OS - OSX, OS - Windows, UI / UX
