### ISSUE TITLE
Jittering search windows on high-end display.

### ISSUE THREAD

**Issue by BigIsBig453** [Cockatrice/Cockatrice#4611] opened 2022-04-30 01:33 UTC
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Portable

_______________________________________________________________________________________

In any search window that is a part of the client, such as when searching a library or graveyard, it spawns in fine, but attempting to move or resize it in any way makes it unusable as it hides on the borders of the game area. I have two monitors, one works at 1440p 144Hz and the other at 1080p 60 Hz. On the 144Hz monitor, the search boxes are glitchy, even if the rest of the game and app is perfectly playable. On my 60Hz monitor, there are no issues to speak of.

Video of bug found below.
[https://streamable.com/fswxl1](url)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Open the game on a high refresh rate monitor
 - Enter or create a lobby
 - Search your library, graveyard, exile, or sideboard while in game
 - Attempt to move or resize the search window

**Comment by ebbit1q** [comment] 2022-05-01 18:40
duplicate of #3386 please comment on existing issues instead of opening new ones

**Closed by ebbit1q** 2022-05-01 18:40 UTC
Labels: Bug
