### ISSUE TITLE
Search hasn't been updated for mana value.

### ISSUE THREAD

**Issue by Skagra42** [Cockatrice/Cockatrice#4644] opened 2022-06-26 06:34 UTC
**System Information:**

Client Version: 2.8.0 (2021-01-26)
PictureLoader: [card:  "Asham, God of Morality"  set:  "ATB" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/ATB/2bmythic rare.jpg - server replied: Not Found"
PictureLoader: [card:  "Asham, God of Morality"  set:  "ATB" ]: Possible picture at  "http://mse-modern.com/msem2/images/ATB/2bmythic rare.jpg"  could not be loaded
PictureLoader: [card:  "Asham, God of Morality"  set:  "ATB" ]: Trying to load picture
PictureLoader: [card:  "Asham, God of Morality"  set:  "ATB" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Asham, God of Morality"  set:  "ATB" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/ATB/2b.jpg"
PictureLoader: [card:  "Asham, God of Morality"  set:  "ATB" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/ATB/2b.jpg"
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Trying to load picture
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/GHQ/162bcommon.jpg"
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/GHQ/162bcommon.jpg - server replied: Not Found"
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Possible picture at  "http://mse-modern.com/msem2/images/GHQ/162bcommon.jpg"  could not be loaded
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Trying to load picture
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/GHQ/162b.jpg"
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Trying to load picture
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Malicious Thoughts"  set:  "GHQ" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/GHQ/162b.jpg"
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/GHQ/137buncommon.jpg"
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/GHQ/137buncommon.jpg - server replied: Not Found"
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Possible picture at  "http://mse-modern.com/msem2/images/GHQ/137buncommon.jpg"  could not be loaded
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Trying to load picture
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/GHQ/137b.jpg"
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Trying to load picture
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Betrayer's Mantle"  set:  "GHQ" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/GHQ/137b.jpg"
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/PFP/48rare.jpg"
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/PFP/48rare.jpg - server replied: Not Found"
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Possible picture at  "http://mse-modern.com/msem2/images/PFP/48rare.jpg"  could not be loaded
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Trying to load picture
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/PFP/48.jpg"
PictureLoader: [card:  "Resource Management"  set:  "PFP" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/PFP/48.jpg"
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Trying to load picture
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Picture found on disk.
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Trying to load picture
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/QRB/88buncommon.jpg"
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/QRB/88buncommon.jpg - server replied: Not Found"
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Possible picture at  "http://mse-modern.com/msem2/images/QRB/88buncommon.jpg"  could not be loaded
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Trying to load picture
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/QRB/88b.jpg"
PictureLoader: [card:  "Corrupted Mount"  set:  "QRB" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/QRB/88b.jpg"
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Trying to load picture
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/QRB/192bcommon.jpg"
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/QRB/192bcommon.jpg - server replied: Not Found"
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Possible picture at  "http://mse-modern.com/msem2/images/QRB/192bcommon.jpg"  could not be loaded
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Trying to load picture
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/QRB/192b.jpg"
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Trying to load picture
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Elven Mount"  set:  "QRB" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/QRB/192b.jpg"
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/GHQ/180bcommon.jpg"
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/GHQ/180bcommon.jpg - server replied: Not Found"
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Possible picture at  "http://mse-modern.com/msem2/images/GHQ/180bcommon.jpg"  could not be loaded
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Trying to load picture
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/GHQ/180b.jpg"
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/GHQ/180b.jpg"
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Trying to load picture
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/TWR/160brare.jpg"
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/TWR/160brare.jpg - server replied: Not Found"
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Possible picture at  "http://mse-modern.com/msem2/images/TWR/160brare.jpg"  could not be loaded
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Trying to load picture
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/TWR/160b.jpg"
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/TWR/160b.jpg"
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Trying to load picture
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/LAW/97common.jpg"
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]:  Download failed: "Error transferring http://mse-modern.com/msem2/images/LAW/97common.jpg - server replied: Not Found"
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Possible picture at  "http://mse-modern.com/msem2/images/LAW/97common.jpg"  could not be loaded
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Trying to load picture
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Trying to download picture from url: "http://mse-modern.com/msem2/images/LAW/97.jpg"
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Image successfully downloaded from  "http://mse-modern.com/msem2/images/LAW/97.jpg"
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Trying to load picture
PictureLoader: [card:  "Sabne, God of Harvest"  set:  "ATB" ]: Picture found on disk.
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Trying to load picture
PictureLoader: [card:  "Ascetic's Journey"  set:  "TWR" ]: Picture found on disk.
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Trying to load picture
PictureLoader: [card:  "Moved by Instinct"  set:  "LAW" ]: Picture found on disk.
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Trying to load picture
PictureLoader: [card:  "Command Respect"  set:  "GHQ" ]: Picture found on disk.
_______________________________________________________________________________________

When searching through cards, "cmc" is still the only way to filter by mana value, and it's referred to as converted mana cost in Search Help.

![image](https://user-images.githubusercontent.com/72851315/175802549-7a73d5eb-2f01-413f-a7db-5dcd9741487e.png)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Open Search Help.

**Comment by ebbit1q** [comment] 2022-06-26 10:47
duplicate of #4316 resolved by #4388 

the beta versions from our release page include this change, please check if your issue exists before opening a new ticket

**Closed** 2022-06-26 10:47 UTC
Labels: Bug
