### ISSUE TITLE
UI breaks when connected to server

### ISSUE THREAD

**Issue by warronbebster** [Cockatrice/Cockatrice#4970] opened 2023-12-21 22:38 UTC
Client Version: 2.9.0 (2023-09-14)
PictureLoader: [card: "Ent-Draught Basin" set: "LTR"]: following cached redirect to "https://cards.scryfall.io/large/front/1/5/1500126f-fbe4-4c39-bb06-1a36e2c4682f.jpg?1686970148"
PictureLoader: [card: "Ent-Draught Basin" set: "LTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/1/5/1500126f-fbe4-4c39-bb06-1a36e2c4682f.jpg?1686970148"
PictureLoader: [card: "Plant Token" set: "NEC"]: Trying to fetch picture from url "https://c1.scryfall.com/file/scryfall-cards/large/front/0/d/0dfac8bc-2b81-4577-a69c-8edbdbcc84aa.jpg?1644543501"
PictureLoader: [card: "Plant Token" set: "NEC"]: following redirect to "https://cards.scryfall.io/large/front/0/d/0dfac8bc-2b81-4577-a69c-8edbdbcc84aa.jpg?1644543501"
PictureLoader: [card: "Plant Token" set: "NEC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/0/d/0dfac8bc-2b81-4577-a69c-8edbdbcc84aa.jpg?1644543501"
PictureLoader: [card: "Arwen, Weaver of Hope" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/4d4f4d41-232d-4377-be69-de590b880edb?format=image&face=front"
PictureLoader: [card: "Arwen, Weaver of Hope" set: "LTC"]: following cached redirect to "https://cards.scryfall.io/large/front/4/d/4d4f4d41-232d-4377-be69-de590b880edb.jpg?1686964026"
PictureLoader: [card: "Arwen, Weaver of Hope" set: "LTC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/4/d/4d4f4d41-232d-4377-be69-de590b880edb.jpg?1686964026"
PictureLoader: [card: "Kogla, the Titan Ape" set: "IKO"]: Trying to fetch picture from url "https://api.scryfall.com/cards/3c35ca79-eb72-427a-a8ed-404b2214389a?format=image&face=front"
PictureLoader: [card: "Kogla, the Titan Ape" set: "IKO"]: following cached redirect to "https://cards.scryfall.io/large/front/3/c/3c35ca79-eb72-427a-a8ed-404b2214389a.jpg?1591227737"
PictureLoader: [card: "Kogla, the Titan Ape" set: "IKO"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/3/c/3c35ca79-eb72-427a-a8ed-404b2214389a.jpg?1591227737"
PictureLoader: [card: "Ilysian Caryatid" set: "CMM"]: Trying to fetch picture from url "https://api.scryfall.com/cards/3db65137-c9d6-4352-b7a0-f3968b167233?format=image&face=front"
PictureLoader: [card: "Ilysian Caryatid" set: "CMM"]: following cached redirect to "https://cards.scryfall.io/large/front/3/d/3db65137-c9d6-4352-b7a0-f3968b167233.jpg?1689998605"
PictureLoader: [card: "Ilysian Caryatid" set: "CMM"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/3/d/3db65137-c9d6-4352-b7a0-f3968b167233.jpg?1689998605"
PictureLoader: [card: "Gandalf the White" set: "PLTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/2aaf6c5b-9cba-4552-8409-8b280cd6e210?format=image&face=front"
PictureLoader: [card: "Gandalf the White" set: "PLTR"]: following cached redirect to "https://cards.scryfall.io/large/front/2/a/2aaf6c5b-9cba-4552-8409-8b280cd6e210.jpg?1687888128"
PictureLoader: [card: "Gandalf the White" set: "PLTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/2/a/2aaf6c5b-9cba-4552-8409-8b280cd6e210.jpg?1687888128"
PictureLoader: [card: "Lotus Blossom" set: "USG"]: Trying to fetch picture from url "https://api.scryfall.com/cards/46d17e0a-5407-4fde-8eb0-8f580eab5565?format=image&face=front"
PictureLoader: [card: "Lotus Blossom" set: "USG"]: following cached redirect to "https://cards.scryfall.io/large/front/4/6/46d17e0a-5407-4fde-8eb0-8f580eab5565.jpg?1562909657"
PictureLoader: [card: "Lotus Blossom" set: "USG"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/4/6/46d17e0a-5407-4fde-8eb0-8f580eab5565.jpg?1562909657"
PictureLoader: [card: "Jungle Shrine" set: "LCC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/13c45b1e-dfa4-4318-96e8-aa5e3e74ca27?format=image&face=front"
PictureLoader: [card: "Jungle Shrine" set: "LCC"]: following cached redirect to "https://cards.scryfall.io/large/front/1/3/13c45b1e-dfa4-4318-96e8-aa5e3e74ca27.jpg?1698988595"
PictureLoader: [card: "Jungle Shrine" set: "LCC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/1/3/13c45b1e-dfa4-4318-96e8-aa5e3e74ca27.jpg?1698988595"
PictureLoader: [card: "Rockfall Vale" set: "WHO"]: Trying to fetch picture from url "https://api.scryfall.com/cards/b782ea91-d31f-4862-8ec0-6e24ef40545c?format=image&face=front"
PictureLoader: [card: "Rockfall Vale" set: "WHO"]: following cached redirect to "https://cards.scryfall.io/large/front/b/7/b782ea91-d31f-4862-8ec0-6e24ef40545c.jpg?1696637096"
PictureLoader: [card: "Rockfall Vale" set: "WHO"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/b/7/b782ea91-d31f-4862-8ec0-6e24ef40545c.jpg?1696637096"
PictureLoader: [card: "WickedCursed" set: "WOE"]: Trying to fetch picture from url "https://cards.scryfall.io/large/front/a/9/a9b7040e-cd24-42cc-b043-9af8c557da6a.jpg?1692904193"
PictureLoader: [card: "Wicked // Cursed" set: "WOE"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/a/9/a9b7040e-cd24-42cc-b043-9af8c557da6a.jpg?1692904193"
PictureLoader: [card: "Beanstalk GiantFertile Footsteps" set: "CMM"]: Trying to fetch picture from url "https://api.scryfall.com/cards/dfd6b4bc-70da-4d93-bdf7-78ba176a764f?format=image&face=front"
PictureLoader: [card: "Beanstalk Giant // Fertile Footsteps" set: "CMM"]: following cached redirect to "https://cards.scryfall.io/large/front/d/f/dfd6b4bc-70da-4d93-bdf7-78ba176a764f.jpg?1691058368"
PictureLoader: [card: "Beanstalk Giant // Fertile Footsteps" set: "CMM"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/d/f/dfd6b4bc-70da-4d93-bdf7-78ba176a764f.jpg?1691058368"
PictureLoader: [card: "Karn's Bastion" set: "LCC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/9134181a-55a0-4c92-b3db-0e21df6719c9?format=image&face=front"
PictureLoader: [card: "Karn's Bastion" set: "LCC"]: following cached redirect to "https://cards.scryfall.io/large/front/9/1/9134181a-55a0-4c92-b3db-0e21df6719c9.jpg?1698988595"
PictureLoader: [card: "Karn's Bastion" set: "LCC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/9/1/9134181a-55a0-4c92-b3db-0e21df6719c9.jpg?1698988595"
PictureLoader: [card: "Legolas, Master Archer" set: "PLTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/239f0955-28e1-49e8-8b3c-b79f7fdbc5b3?format=image&face=front"
PictureLoader: [card: "Legolas, Master Archer" set: "PLTR"]: following cached redirect to "https://cards.scryfall.io/large/front/2/3/239f0955-28e1-49e8-8b3c-b79f7fdbc5b3.jpg?1687887752"
PictureLoader: [card: "Legolas, Master Archer" set: "PLTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/2/3/239f0955-28e1-49e8-8b3c-b79f7fdbc5b3.jpg?1687887752"
PictureLoader: [card: "Knight Token" set: "WOE"]: Trying to fetch picture from url "https://cards.scryfall.io/large/front/f/4/f4035134-a162-4651-86c5-ae006b6e0e20.jpg?1692880673"
PictureLoader: [card: "Knight Token" set: "WOE"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/f/4/f4035134-a162-4651-86c5-ae006b6e0e20.jpg?1692880673"
PictureLoader: [card: "Tireless Provisioner" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/995938ee-3ba7-42c9-9e0f-76b4a105f55e?format=image&face=front"
PictureLoader: [card: "Tireless Provisioner" set: "LTC"]: following cached redirect to "https://cards.scryfall.io/large/front/9/9/995938ee-3ba7-42c9-9e0f-76b4a105f55e.jpg?1686966201"
PictureLoader: [card: "Tireless Provisioner" set: "LTC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/9/9/995938ee-3ba7-42c9-9e0f-76b4a105f55e.jpg?1686966201"
PictureLoader: [card: "Wood Elves" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/7e6efd6b-6815-4308-9cca-948dd43a0424?format=image&face=front"
PictureLoader: [card: "Wood Elves" set: "LTC"]: following cached redirect to "https://cards.scryfall.io/large/front/7/e/7e6efd6b-6815-4308-9cca-948dd43a0424.jpg?1686966210"
PictureLoader: [card: "Wood Elves" set: "LTC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/7/e/7e6efd6b-6815-4308-9cca-948dd43a0424.jpg?1686966210"
PictureLoader: [card: "Wose Pathfinder" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/6589b339-9067-4e9b-bfdb-c49f8b3ef2d4?format=image&face=front"
PictureLoader: [card: "Wose Pathfinder" set: "LTR"]: following cached redirect to "https://cards.scryfall.io/large/front/6/5/6589b339-9067-4e9b-bfdb-c49f8b3ef2d4.jpg?1686969622"
PictureLoader: [card: "Wose Pathfinder" set: "LTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/6/5/6589b339-9067-4e9b-bfdb-c49f8b3ef2d4.jpg?1686969622"
PictureLoader: [card: "Friendly Rivalry" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/24076763-88ba-4dee-b548-9c27bd34fdb7?format=image&face=front"
PictureLoader: [card: "Friendly Rivalry" set: "LTR"]: following cached redirect to "https://cards.scryfall.io/large/front/2/4/24076763-88ba-4dee-b548-9c27bd34fdb7.jpg?1686969776"
PictureLoader: [card: "Friendly Rivalry" set: "LTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/2/4/24076763-88ba-4dee-b548-9c27bd34fdb7.jpg?1686969776"
PictureLoader: [card: "Aurelia, the Warleader" set: "MUL"]: Trying to fetch picture from url "https://api.scryfall.com/cards/1e7c2afb-e04e-4012-b8a2-7a7273b52136?format=image&face=front"
PictureLoader: [card: "Aurelia, the Warleader" set: "MUL"]: following cached redirect to "https://cards.scryfall.io/large/front/1/e/1e7c2afb-e04e-4012-b8a2-7a7273b52136.jpg?1682200633"
PictureLoader: [card: "Aurelia, the Warleader" set: "MUL"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/1/e/1e7c2afb-e04e-4012-b8a2-7a7273b52136.jpg?1682200633"
PictureLoader: [card: "Revive the Shire" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/46b7f493-1b57-4b07-8510-30703282f879?format=image&face=front"
PictureLoader: [card: "Revive the Shire" set: "LTR"]: following cached redirect to "https://cards.scryfall.io/large/front/4/6/46b7f493-1b57-4b07-8510-30703282f879.jpg?1686969568"
PictureLoader: [card: "Revive the Shire" set: "LTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/4/6/46b7f493-1b57-4b07-8510-30703282f879.jpg?1686969568"
PictureLoader: [card: "Together Forever" set: "MOC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/2b22e344-97ae-4e25-9bf9-004ac30c2fd6?format=image&face=front"
PictureLoader: [card: "Together Forever" set: "MOC"]: following cached redirect to "https://cards.scryfall.io/large/front/2/b/2b22e344-97ae-4e25-9bf9-004ac30c2fd6.jpg?1682208663"
PictureLoader: [card: "Together Forever" set: "MOC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/2/b/2b22e344-97ae-4e25-9bf9-004ac30c2fd6.jpg?1682208663"
PictureLoader: [card: "Ajani Steadfast Emblem" set: "CMM"]: Trying to fetch picture from url "https://cards.scryfall.io/large/front/e/9/e9f9aebc-6eb8-4325-801f-ad2fbbf391b2.jpg?1689710331"
PictureLoader: [card: "Ajani Steadfast Emblem" set: "CMM"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/9/e9f9aebc-6eb8-4325-801f-ad2fbbf391b2.jpg?1689710331"
PictureLoader: [card: "Andúril, Narsil Reforged" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/b33c91d2-020e-45a1-aef6-187484a7cb51?format=image&face=front"
PictureLoader: [card: "Andúril, Narsil Reforged" set: "LTC"]: following redirect to "https://cards.scryfall.io/large/front/b/3/b33c91d2-020e-45a1-aef6-187484a7cb51.jpg?1695346449"
PictureLoader: [card: "Andúril, Narsil Reforged" set: "LTC"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/b/3/b33c91d2-020e-45a1-aef6-187484a7cb51.jpg?1695346449"
PictureLoader: [card: "Legolas's Quick Reflexes" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/851c0167-04ba-4d15-b0fa-c211bd8826f1?format=image&face=front"
PictureLoader: [card: "Legolas's Quick Reflexes" set: "LTC"]: following cached redirect to "https://cards.scryfall.io/large/front/8/5/851c0167-04ba-4d15-b0fa-c211bd8826f1.jpg?1695346458"
PictureLoader: [card: "Legolas's Quick Reflexes" set: "LTC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/8/5/851c0167-04ba-4d15-b0fa-c211bd8826f1.jpg?1695346458"
PictureLoader: [card: "Savageborn Hydra" set: "DGM"]: Trying to fetch picture from url "https://api.scryfall.com/cards/2f2b73cd-6179-4885-9d92-1782d0b492c1?format=image&face=front"
PictureLoader: [card: "Savageborn Hydra" set: "DGM"]: following cached redirect to "https://cards.scryfall.io/large/front/2/f/2f2b73cd-6179-4885-9d92-1782d0b492c1.jpg?1562903702"
PictureLoader: [card: "Savageborn Hydra" set: "DGM"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/2/f/2f2b73cd-6179-4885-9d92-1782d0b492c1.jpg?1562903702"
PictureLoader: [card: "Sunbird Standard" set: "LCI"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e0b6d40a-fded-4625-b03c-765c88d75766?format=image&face=front"
PictureLoader: [card: "Sunbird Standard" set: "LCI"]: following cached redirect to "https://cards.scryfall.io/large/front/e/0/e0b6d40a-fded-4625-b03c-765c88d75766.jpg?1699044640"
PictureLoader: [card: "Sunbird Standard" set: "LCI"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/0/e0b6d40a-fded-4625-b03c-765c88d75766.jpg?1699044640"
PictureLoader: [card: "Radiant Grove" set: "DMU"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e0f9dca6-e5ae-4714-8a59-2ef1d8f1e82d?format=image&face=front"
PictureLoader: [card: "Radiant Grove" set: "DMU"]: following cached redirect to "https://cards.scryfall.io/large/front/e/0/e0f9dca6-e5ae-4714-8a59-2ef1d8f1e82d.jpg?1673308352"
PictureLoader: [card: "Radiant Grove" set: "DMU"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/0/e0f9dca6-e5ae-4714-8a59-2ef1d8f1e82d.jpg?1673308352"
PictureLoader: [card: "Urban Daggertooth" set: "MH2"]: Trying to fetch picture from url "https://api.scryfall.com/cards/4ab83a39-d90d-403e-b74d-fe99c8b2aacd?format=image&face=front"
PictureLoader: [card: "Urban Daggertooth" set: "MH2"]: following cached redirect to "https://cards.scryfall.io/large/front/4/a/4ab83a39-d90d-403e-b74d-fe99c8b2aacd.jpg?1626097969"
PictureLoader: [card: "Urban Daggertooth" set: "MH2"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/4/a/4ab83a39-d90d-403e-b74d-fe99c8b2aacd.jpg?1626097969"
PictureLoader: [card: "Wooded Ridgeline" set: "DMU"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e8e31184-dca4-48b1-be9d-581247c41d99?format=image&face=front"
PictureLoader: [card: "Wooded Ridgeline" set: "DMU"]: following cached redirect to "https://cards.scryfall.io/large/front/e/8/e8e31184-dca4-48b1-be9d-581247c41d99.jpg?1673308403"
PictureLoader: [card: "Wooded Ridgeline" set: "DMU"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/8/e8e31184-dca4-48b1-be9d-581247c41d99.jpg?1673308403"
PictureLoader: [card: "Sungrass Prairie" set: "WHO"]: Trying to fetch picture from url "https://api.scryfall.com/cards/db4a9124-a692-4086-8f22-574fdcd81ae2?format=image&face=front"
PictureLoader: [card: "Sungrass Prairie" set: "WHO"]: following cached redirect to "https://cards.scryfall.io/large/front/d/b/db4a9124-a692-4086-8f22-574fdcd81ae2.jpg?1696637129"
PictureLoader: [card: "Sungrass Prairie" set: "WHO"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/d/b/db4a9124-a692-4086-8f22-574fdcd81ae2.jpg?1696637129"
PictureLoader: [card: "Beanstalk WurmPlant Beans" set: "WOE"]: Trying to fetch picture from url "https://api.scryfall.com/cards/19f20c0a-22be-4a9c-96ce-4047f7a2d424?format=image&face=front"
PictureLoader: [card: "Beanstalk Wurm // Plant Beans" set: "WOE"]: following cached redirect to "https://cards.scryfall.io/large/front/1/9/19f20c0a-22be-4a9c-96ce-4047f7a2d424.jpg?1693078399"
PictureLoader: [card: "Beanstalk Wurm // Plant Beans" set: "WOE"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/1/9/19f20c0a-22be-4a9c-96ce-4047f7a2d424.jpg?1693078399"
PictureLoader: [card: "Sword of Truth and Justice" set: "H1R"]: Trying to fetch picture from url "https://api.scryfall.com/cards/f714386f-607a-41fd-ae72-f2d2641841aa?format=image&face=front"
PictureLoader: [card: "Sword of Truth and Justice" set: "H1R"]: following cached redirect to "https://cards.scryfall.io/large/front/f/7/f714386f-607a-41fd-ae72-f2d2641841aa.jpg?1630617024"
PictureLoader: [card: "Sword of Truth and Justice" set: "H1R"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/f/7/f714386f-607a-41fd-ae72-f2d2641841aa.jpg?1630617024"
PictureLoader: [card: "Emeria Shepherd" set: "PAGL"]: Trying to fetch picture from url "https://api.scryfall.com/cards/52d1a2a8-9b3e-4dae-84d7-5a3e34228063?format=image&face=front"
PictureLoader: [card: "Emeria Shepherd" set: "PAGL"]: following cached redirect to "https://cards.scryfall.io/large/front/5/2/52d1a2a8-9b3e-4dae-84d7-5a3e34228063.jpg?1693263815"
PictureLoader: [card: "Emeria Shepherd" set: "PAGL"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/5/2/52d1a2a8-9b3e-4dae-84d7-5a3e34228063.jpg?1693263815"
PictureLoader: [card: "Chaos Warp" set: "LCC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/73ca9629-b1e3-49d6-ae10-908b9e4e67ce?format=image&face=front"
PictureLoader: [card: "Chaos Warp" set: "LCC"]: following cached redirect to "https://cards.scryfall.io/large/front/7/3/73ca9629-b1e3-49d6-ae10-908b9e4e67ce.jpg?1698988311"
PictureLoader: [card: "Chaos Warp" set: "LCC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/7/3/73ca9629-b1e3-49d6-ae10-908b9e4e67ce.jpg?1698988311"
PictureLoader: [card: "Earthquake" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/f1030c6d-e6f4-42e0-84d3-d3916d7f397c?format=image&face=front"
PictureLoader: [card: "Earthquake" set: "LTC"]: following cached redirect to "https://cards.scryfall.io/large/front/f/1/f1030c6d-e6f4-42e0-84d3-d3916d7f397c.jpg?1686965756"
PictureLoader: [card: "Earthquake" set: "LTC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/f/1/f1030c6d-e6f4-42e0-84d3-d3916d7f397c.jpg?1686965756"
PictureLoader: [card: "Delighted Halfling" set: "PLTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e65be588-4209-4ad7-9bdc-d601fdc0e8f6?format=image&face=front"
PictureLoader: [card: "Delighted Halfling" set: "PLTR"]: following cached redirect to "https://cards.scryfall.io/large/front/e/6/e65be588-4209-4ad7-9bdc-d601fdc0e8f6.jpg?1689143202"
PictureLoader: [card: "Delighted Halfling" set: "PLTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/6/e65be588-4209-4ad7-9bdc-d601fdc0e8f6.jpg?1689143202"
PictureLoader: [card: "Sovereign Okinec Ahau" set: "LCI"]: Trying to fetch picture from url "https://api.scryfall.com/cards/70c75aa7-e2f9-4a69-8086-c982019ca714?format=image&face=front"
PictureLoader: [card: "Sovereign Okinec Ahau" set: "LCI"]: following cached redirect to "https://cards.scryfall.io/large/front/7/0/70c75aa7-e2f9-4a69-8086-c982019ca714.jpg?1699044573"
PictureLoader: [card: "Sovereign Okinec Ahau" set: "LCI"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/7/0/70c75aa7-e2f9-4a69-8086-c982019ca714.jpg?1699044573"
PictureLoader: [card: "Nature's Claim" set: "WWK"]: Trying to fetch picture from url "https://api.scryfall.com/cards/64ae5a91-ac54-4222-832e-d7a740a3f7cb?format=image&face=front"
PictureLoader: [card: "Nature's Claim" set: "WWK"]: following cached redirect to "https://cards.scryfall.io/large/front/6/4/64ae5a91-ac54-4222-832e-d7a740a3f7cb.jpg?1562288512"
PictureLoader: [card: "Nature's Claim" set: "WWK"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/6/4/64ae5a91-ac54-4222-832e-d7a740a3f7cb.jpg?1562288512"
PictureLoader: [card: "Rogue's Passage" set: "LCC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/a7dc75a8-c500-4b50-aff9-32ce36566104?format=image&face=front"
PictureLoader: [card: "Rogue's Passage" set: "LCC"]: following cached redirect to "https://cards.scryfall.io/large/front/a/7/a7dc75a8-c500-4b50-aff9-32ce36566104.jpg?1698988621"
PictureLoader: [card: "Rogue's Passage" set: "LCC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/a/7/a7dc75a8-c500-4b50-aff9-32ce36566104.jpg?1698988621"
PictureLoader: [card: "Selfless Squire" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/f5f2bffc-4a56-4558-91b4-d2d6a98b8d05?format=image&face=front"
PictureLoader: [card: "Selfless Squire" set: "LTC"]: following redirect to "https://cards.scryfall.io/large/front/f/5/f5f2bffc-4a56-4558-91b4-d2d6a98b8d05.jpg?1686965388"
PictureLoader: [card: "Selfless Squire" set: "LTC"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/f/5/f5f2bffc-4a56-4558-91b4-d2d6a98b8d05.jpg?1686965388"
PictureLoader: [card: "Food Token" set: "WHO"]: Trying to fetch picture from url "https://cards.scryfall.io/large/front/8/8/883a8ba9-6a3c-4f3b-876e-ec47a08dbb8a.jpg?1696625047"
PictureLoader: [card: "Food Token" set: "WHO"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/8/8/883a8ba9-6a3c-4f3b-876e-ec47a08dbb8a.jpg?1696625047"
PictureLoader: [card: "Chord of Calling" set: "RAV"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e064174b-8f07-4fea-9eef-c3b5d0220b1a?format=image&face=front"
PictureLoader: [card: "Chord of Calling" set: "RAV"]: following cached redirect to "https://cards.scryfall.io/large/front/e/0/e064174b-8f07-4fea-9eef-c3b5d0220b1a.jpg?1598916101"
PictureLoader: [card: "Chord of Calling" set: "RAV"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/0/e064174b-8f07-4fea-9eef-c3b5d0220b1a.jpg?1598916101"
PictureLoader: [card: "Cursed Mirror" set: "WHO"]: Trying to fetch picture from url "https://api.scryfall.com/cards/efb9aadf-a50e-4542-82e8-6d8cbc2ea350?format=image&face=front"
PictureLoader: [card: "Cursed Mirror" set: "WHO"]: following cached redirect to "https://cards.scryfall.io/large/front/e/f/efb9aadf-a50e-4542-82e8-6d8cbc2ea350.jpg?1696636923"
PictureLoader: [card: "Cursed Mirror" set: "WHO"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/f/efb9aadf-a50e-4542-82e8-6d8cbc2ea350.jpg?1696636923"
PictureLoader: [card: "Path to Exile" set: "LCC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/7e9c2a58-4a1c-454c-b72d-faecaea105fb?format=image&face=front"
PictureLoader: [card: "Path to Exile" set: "LCC"]: following redirect to "https://cards.scryfall.io/large/front/7/e/7e9c2a58-4a1c-454c-b72d-faecaea105fb.jpg?1698988102"
PictureLoader: [card: "Path to Exile" set: "LCC"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/7/e/7e9c2a58-4a1c-454c-b72d-faecaea105fb.jpg?1698988102"
ACT SHOW POPUP

**System Information:**
<img width="277" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/8211247/1bf7eb22-d459-42e9-bba1-827ba6e0887a">

_______________________________________________________________________________________

Once I connect to a server

<img width="1526" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/8211247/57baa49a-75a5-48da-9ece-bf13cbff2f5d">

_______________________________________________________________________________________

**Steps to reproduce:**
Open Cockatrice
Actions > Connect
Choose Magic and UI just breaks

**Comment by jaaacck** [comment] 2023-12-22 17:17
I'm experiencing the exact same thing on a brand new install. Client Version: 2.9.0 (2023-09-14).
I've done nothing other than download the card database and connect to Rooster Ranger server



<img width="180" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/7045733/4e9bf66f-4bb6-4608-b6d0-a6d9eb855954">

<img width="1798" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/7045733/b41b904a-67d4-41d3-a4a4-26878f44e3a9">

**Comment by ebbit1q** [comment] 2023-12-24 17:18
is this a duplicate of https://github.com/Cockatrice/Cockatrice/issues/4936 ?

**Comment by warronbebster** [comment] 2023-12-25 19:55
> is this a duplicate of #4936 ?

Perhaps, but this computer is not on Sonoma, it's on Monterrey

**Comment by ebbit1q** [comment] 2024-01-02 17:34
is it fixed by the same solution as in that ticket?

**Closed** 2024-05-21 15:35 UTC
Labels: Bug
