### ISSUE TITLE
TLS initialization failed

### ISSUE THREAD

**Issue by sophria** [Cockatrice/Cockatrice#4509] opened 2022-01-02 20:28 UTC
**System Information:**

Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 32-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

I just installed Cockatrice, the 64 bit version did not work for my computer despite being a 64 bit build; I was receiving several missing .dll errors. I uninstalled it and installed the 32 bit version, Cockatrice now opens and tries to import the card library and I am met with this error. With the 32 bit version I don't receive any other errors and I can't find a thread that is only the "TLS initialization failed" not followed with any other errors. I am connected to the internet and everything else seems to run fine as far as network connections.

![oracle error](https://user-images.githubusercontent.com/96997651/147888495-21981634-cc52-4ff6-8a0d-bc964559d601.png)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Launch Cockatrice
 - unable to load the card database. update? select yes
 - Language selection: english version 2.8.0 (2021-01-26) select next
 - Source selection default download url: https://www.mtgjson.com/api/v5/AllPrintings.json.xz   select next
 - Network error: TLS initialization failed

**Comment by ebbit1q** [comment] 2022-01-02 21:31
this is a duplicate of https://github.com/Cockatrice/Cockatrice/issues/4233 please see this ticket for possible workarounds

**Closed by ebbit1q** 2022-01-02 21:31 UTC
Labels: Bug
