### ISSUE TITLE
Install issues on Ubuntu 19.10

### ISSUE THREAD

**Issue by Paul-E** [Cockatrice/Cockatrice#3955] opened 2020-04-14 05:40 UTC
I'm on Ubuntu, when I try to install Cockatrice I get the following results:

```
$ sudo dpkg -i Cockatrice-Dawn_of_Hope_Revision_1-2.7.4-UbuntuBionic.deb 
[sudo] password for paul: 
Selecting previously unselected package cockatrice.
(Reading database ... 477206 files and directories currently installed.)
Preparing to unpack Cockatrice-Dawn_of_Hope_Revision_1-2.7.4-UbuntuBionic.deb ...
Unpacking cockatrice (2.7.4) ...
dpkg: dependency problems prevent configuration of cockatrice:
 cockatrice depends on libqt5multimedia5-plugins; however:
  Package libqt5multimedia5-plugins is not installed.
 cockatrice depends on libprotobuf10; however:
  Package libprotobuf10 is not installed.
 cockatrice depends on libqt5multimedia5 (>= 5.6.0~beta); however:
  Package libqt5multimedia5 is not installed.
 cockatrice depends on libqt5websockets5 (>= 5.6.0); however:
  Package libqt5websockets5 is not installed.

dpkg: error processing package cockatrice (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.24-1ubuntu1) ...
Processing triggers for mime-support (3.63ubuntu1) ...
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 cockatrice
$ sudo apt autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 cockatrice : Depends: libqt5multimedia5-plugins but it is not installed
              Depends: libprotobuf10 but it is not installable
              Depends: libqt5multimedia5 (>= 5.6.0~beta) but it is not installed
              Depends: libqt5websockets5 (>= 5.6.0) but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Running `apt --fix-broken install` uninstalls the broken cockatrice install. It appears libprotobuf10 is not available for Ubuntu 19.10; the version available in the Ubuntu repositories is libprotobuf17. This seems similar to #2867.

Is it best to just install the flatpack in the [unofficial](https://github.com/Cockatrice/Cockatrice/wiki/Unofficial-Developer-Builds) build on newer versions of Ubuntu?

**Comment by ctrlaltca** [comment] 2020-04-14 07:49
This sounds like a duplicate of #3899
You can try using the package for Debian 10 "Buster", that is linking against libprotobuf17.

**Comment by ebbit1q** [comment] 2020-04-14 15:51
The package we provide is only for ubuntu 18.04, the debian buster package however is compatible with ubuntu 19.10.

**Closed** 2020-04-14 16:03 UTC
Labels: Bug
