### ISSUE TITLE
Replay timeline navigation not working beyond 25%.

### ISSUE THREAD

**Issue by omen124** [Cockatrice/Cockatrice#4529] opened 2022-01-18 04:22 UTC
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_GB
Install Mode: Portable
_______________________________________________________________________________________

**Issue Description:**
When using a replay you can click somewhere on the timeline to jump to it but somewhere after the 25%-30% mark, the replay snaps back to 0% or 100% (becomes unresponsive) and you can't quickly jump anywhere past the 25-30% position without just letting the play run normally.
_______________________________________________________________________________________

**Steps to reproduce:**
 - Open a replay
 - Click somewhere on the timeline further than 30% along

**Comment by skwerlman** [comment] 2022-01-18 08:13
seems like a duplicate of #3941; should already be fixed in the newest betas.

Can you check if the issue still occurs for you with this version: https://github.com/Cockatrice/Cockatrice/releases/tag/2022-01-17-Development-2.8.1-beta.6

If it does, please let us know.

**Comment by tooomm** [comment] 2022-01-18 11:17
You can also go to the settings in the Cockatrice app and switch to the `Beta` release channel.
If you then search for Updates via `Help --> Check for Client Updates`, Cockatrice will pull the most recent beta version on its own.

Please report back if it works for you after the update!

**Comment by omen124** [comment] 2022-01-18 15:55
I can confirm that the beta version has fixed the issue.

**Comment by tooomm** [comment] 2022-01-18 15:57
Awesome, thanks for letting us know!
The next stable release will include this fix as well. There is no release date scheduled yet though.

**Closed by tooomm** 2022-01-18 15:57 UTC
Labels: Bug
