### ISSUE TITLE
"reg. users only" games not showing up in Woogerworks Main room after most recent update

### ISSUE THREAD

**Issue by MaximumUnicorn** [Cockatrice/Cockatrice#2578] opened 2017-04-07 22:39 UTC
<b>OS: Windows 10 Home 64-bit</b>

<b>Cockatrice version: ef7670a (2017-3-31)</b>

__________

This is largely a repost of my [Reddit thread](https://www.reddit.com/r/Cockatrice/comments/6430g3/reg_users_only_games_not_showing_up_in/) on /r/cockatrice as requested by Daenyth.

When I updated my version of Cockatrice to ef7670a, open games for registered users weren't displayed for me in the Main room, despite having registered my account (username MaximumUnicorn) several years ago. Those games do show up if I enable the "Show unavailable games" filter, but not otherwise. I can still join available "reg. users only" games with no trouble if I have that filter enabled. My usual filters are Vintage, Legacy, Modern, Limited.

I tried uninstalling Cockatrice, keeping no files, and then downloading and installing ef7670a (2017-3-31) from scratch. I also re-entered the required registration information via "Edit" in the Account tab. Neither action fixed the problem.

I apologize for the blandness of my writing. I am trying to be as clear as I can be.

Thank you

**Comment by Daenyth** [comment] 2017-04-07 23:14
I probably broke this in #2501

**Comment by Daenyth** [comment] 2017-04-07 23:17
yep @ZeldaZach https://github.com/Cockatrice/Cockatrice/pull/2501/files#diff-63ab9dff27cc3fba27b6e19b98a9734cR611 same casting problem

**Comment by Daenyth** [comment] 2017-04-07 23:18
Oh this might be fixed in #2564 - it's the same root cause as #2560 

@MaximumUnicorn Can you change your updater settings to use the development release channel instead of stable release channel and see if that fixes the issue?

**Comment by SlomoSapien** [comment] 2017-04-12 04:35
@Daenyth How would one go about doing that?  I have the same problem as @MaximumUnicorn re: the games not showing up.  Additionally,  I cannot make changes to my buddy or ignore list. 
(same vers, same win10)

**Closed** 2017-04-12 11:00 UTC
Labels: Troubleshooting
