### ISSUE TITLE
Treat DFC's properly

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3033] opened 2018-01-20 01:20 UTC
Right now we use the related cards feature to connect both halves of a double-faced card.
The user has to right click and select the back side in the `Token` section. Then the other side will get created and the original card is attached to it.
That is very wonky and has several downsides. Particularly, conflicts arise with werewolf cards that you are likely to repeatedly turn over back and forth. It doesn't work as one might expect and keeps creating more and more unneeded cards. :)
Also, normal card handling like moving a turned over DFC to the graveyard because it died or got destroyed/exiled etc. doesn't work as it should.

My suggestion to keep things very general, game independent and intuitive is:

- **Kamigawa flip card suggestion moved to separate issue --> #3094**

- Handle DFC's different than normal cards.
Such cards should show their related/connected double-faced back side on `Turn over` instead the default card back.

Maybe remove "attach" from `<related>` for DFC's, and introduce something like "layout" instead?
```
        <card>
            <name>Search for Azcanta</name>
            <set rarity="Rare" muId="435226" num="74a">XLN</set>
            <color>U</color>
            <related layout="double-faced">Azcanta, the Sunken Ruin</related>
            <manacost>1U</manacost>
            <cmc>2</cmc>
            <type>Legendary Enchantment</type>
            <tablerow>1</tablerow>
            <text>At the beginning of your upkeep, look at the top card of your library. You may put it into your graveyard. Then if you have seven or more cards in your graveyard, you may transform Search for Azcanta.</text>
        </card>
    ...
        <card>
            <name>Azcanta, the Sunken Ruin</name>
            <set rarity="Rare" muId="435227" num="74b">XLN</set>
            <related layout="double-faced">Search for Azcanta</related>
            <manacost></manacost>
            <cmc>2</cmc>
            <type>Legendary Land</type>
            <tablerow>0</tablerow>
            <text>(Transforms from Search for Azcanta.)
    {T}: Add {U} to your mana pool.
    {2}{U}, {T}: Look at the top four cards of your library. You may reveal a noncreature, nonland card from     among them and put it into your hand. Put the rest on the bottom of your library in any order.</text>
        </card>
```

<br>

`Meld` cards should be considered here as well, since they still might need a bit different handling.
For now, they could keep working like they do with "attach". But I'm open for improvement ideas here.

I hope we can put away all the awkwardness for related connections for DFCs and especially the attach mess that destroys normal card handling!
I also assume wizards is going to print DFC's more regularly now...

@Psithief What are your thoughts/ideas on this?

**Comment by Psithief** [comment] 2018-01-21 07:45
I think the general solution here is a "`Swap with`" command. It replaces the card, but keeps all the states that card is in, such as:
* What's attached to it
* What it's attached to
* Counters on it
* Orientation (tapped/untaped)
* Manual adjustments for power / toughness relative to the card's base?
etc.

Of course, that's only applicable for cards that transform in place. Some are exiled, then come back transformed. That will probably need some sort of flag on the relationship.

The other complication is that, with `Meld`, there are pairs that require swapping that's not one-to-one.

**Comment by Daenyth** [comment] 2018-03-01 13:03
What happens when the swapped thing leaves the table? This adds a lot of complication. For transform/flip cards, the original needs to go to graveyard. I don't like how that makes things more complex. Hmm

**Comment by Psithief** [comment] 2018-03-03 05:50
Yes, it is inherently complicated. It needs a proper design write-up to be reviewed before any code gets written.

* These card replacements would keep the same state
  * Kamigawa flip cards
  * Most transform cards
* These card replacements would not keep the same state
  * Magic Origins planeswalkers
  * Conqueror's Galleon
  * Cards with Meld

Thanks to `Conqueror's Galleon`, we already have a parsing problem, though one we would only need to run it over the set of cards already flagged as transformable by mtgjson.

`/exile (it|them|~), then (meld|return (it|him|her) to the battlefield transformed)/`
*(`~` = card name)*

I can't see this really working properly without a protocol upgrade.

**Comment by Daenyth** [comment] 2018-03-04 00:05
I agree we can't/shouldn't implement this as it stands today

**Comment by ZeldaZach** [comment] 2020-10-01 22:14
Dupe of #4081  (Yes I know this is older, but we're working backwards)

**Closed by ZeldaZach** 2020-10-01 22:14 UTC
Labels: App - Cockatrice
