### ISSUE TITLE
Gonti Problem

### ISSUE THREAD

**Issue by LarryBushido** [Cockatrice/Cockatrice#2188] opened 2016-09-25 09:46 UTC
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

___
<br>

*Explain your Issue/Request/Suggestion in detail here!*
So if there is already a way to do this and i dont know how please explain.
but i have tired every thing with a friend to find out how to use lord Gonti .
so my question / suggestion: is there a way to get a card from an opponents deck with out them knowing what it is and with gonti's player being able to see it?

**Comment by Daenyth** [comment] 2016-09-25 11:25
This is a duplicate of #625.

Unfortunately there's not a good solution to this problem at the moment.

For a very painful workaround, you could turn off sorting in the deck view panel so that you see the cards in the order they currently are in. Then you tell your opp to move X number of cards from top of the deck to the bottom of the deck by shift+dragging to the field and right click -> move to bottom. Then the last card they shift drag to the field and give you control over, you can peek to make sure you got the right one. If they make a mistake though you'd need to start over and repeat the process.

If I think of a workaround that's less shit I'll comment it on the other ticket.

**Closed by Daenyth** 2016-09-25 11:25 UTC
