### ISSUE TITLE
Ignored Users' Chat Messages Are Viewable in the Backlog Upon Login

### ISSUE THREAD

**Issue by Maalarius** [Cockatrice/Cockatrice#4044] opened 2020-07-10 17:45 UTC
<b>System Information:</b>Ubuntu Linux: 20.04, Beta Release

When live chat is active ignored users' chats are not visible, but once you log out, and then log back in again, you can see their messages in the backlog of the chat.

**Comment by ebbit1q** [comment] 2020-07-10 17:48
duplicate of https://github.com/Cockatrice/Cockatrice/issues/2278

**Closed by ebbit1q** 2020-07-10 17:48 UTC
Labels: Bug
