### ISSUE TITLE
Allow revealing your hand to yourself

### ISSUE THREAD

**Issue by reem** [Cockatrice/Cockatrice#2941] opened 2017-12-05 09:23 UTC
This is useful when you have a lot of cards in your hand and it becomes very difficult to use an unsorted view. The reveal window sorts cards and shows larger images which makes it much easier to manage.

**Comment by Daenyth** [comment] 2017-12-05 11:44
This shouldn't be a "reveal to" option since that doesn't make sense - this can be 100% client side since it doesn't affect anything on the server.

**Comment by reem** [comment] 2017-12-05 19:19
You are right, I just figured that’s the easiest way to explain the
feature. An option like “expand hand” or something could work.

**Comment by dev-id** [comment] 2017-12-23 17:24
Great suggestion. If the pop out hand has all the regular hand options, I could see people preferring the “floating” hand to either of the two current options.

**Comment by ebbit1q** [comment] 2020-05-13 14:44
duplicate of https://github.com/Cockatrice/Cockatrice/issues/3720
fixed by https://github.com/Cockatrice/Cockatrice/pull/3731

**Closed by ebbit1q** 2020-05-13 14:44 UTC
Labels: App - Cockatrice, Suggestion, UI / UX
