### ISSUE TITLE
w10 stables releases adventure creature confusing

### ISSUE THREAD

**Issue by adrienrapper** [Cockatrice/Cockatrice#4604] opened 2022-04-10 06:34 UTC
Hello dear cockatrice programmer.

On w10 stable releases adventure creature is count as instant/sorcery during the deck building it is confusing.

Regard.
Adrien Estevez.
![cockatrice issue](https://user-images.githubusercontent.com/78217728/162605614-a94857a1-5c5a-43ee-925f-b298a715ef47.jpg)

**Comment by ebbit1q** [comment] 2022-04-10 12:29
duplicate of #4394 please keep discussion of a problem to a single thread

**Closed by ebbit1q** 2022-04-10 12:29 UTC
Labels: Bug

**Comment by adrienrapper** [comment] 2022-04-11 11:35
> duplicate of #4394 please keep discussion of a problem to a single thread

ah okay sorry!
