### ISSUE TITLE
Support profiles to play different game with the one cockatrice installation

### ISSUE THREAD

**Issue by olegshtch** [Cockatrice/Cockatrice#4050] opened 2020-07-22 07:38 UTC
**Similar Requests**

**Description of New Feature**

In order to support different games it's need to choose different card databases.

**Additional Context**

Currently only one card database could be set in the installation.

**Comment by ebbit1q** [comment] 2020-07-22 10:39
While it is not possible to easily disable or enable a predefined subset of sets in the sets manager it is most certainly possible to use multiple card databases at the same time, see https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets

One problem that remains is name conflicts with custom cards, if the proposed workaround of adding extra characters to create unique names is undesirable it'd be required to disable the sets provided by oracle in the sets manager, leading to inconvenience switching between them.

**Comment by tooomm** [comment] 2020-07-31 21:13
Having various profiles for certain games might not be that different to game plug-ins: https://github.com/Cockatrice/Cockatrice/issues/1740

**Comment by ZeldaZach** [comment] 2020-09-13 22:11
I'd consider this a dupe of #1740

**Closed by ZeldaZach** 2020-09-13 22:11 UTC
Labels: Feature Request

**Comment by olegshtch** [comment] 2020-09-14 04:01
No, it was about to support multiple options like card databases.

**Comment by tooomm** [comment] 2020-09-24 08:31
Can you explain more in detail what your idea is about @olegshtch? And why it's that different from game plug-ins?

You need to select a game plug-in in e.g. settings to enable it.
The same as you need to select the desired card database option for a certain game to load that cards (that's how I understand your suggestion). Game profiles just allow for more than a linked card database. It could be a complete profile that changes sounds and themes to fit the other game better as well for example.

**Comment by olegshtch** [comment] 2020-09-24 09:50
Yes, I mean other options as well so it will be possible to switch between them to play different games.

**Comment by tooomm** [comment] 2020-09-24 11:55
Exactly. You would go to e.g. setting (or wherever it is placed) and instead selecting your card database for a different game to switch to that and play it, you select a profile/plug-in for a different game to archive the same (and more). Same same, but better. 👍 

Make sure to comment/subscribe to the mentioned issue to stay updated. But don't expect any changes soon.

**Comment by ebbit1q** [comment] 2020-09-24 12:14
I'd be up for splitting these tasks so they can be implemented one by one.

**Comment by tooomm** [comment] 2020-09-24 13:18
Why not... I mean allowing to load different databases, manage and easily switch between them would be the first step obviously.

The idea in #1740 is broader and changes the concept, too. This request could be the start in the direction and allow for better multi-game support way sooner.

How could we start?
We would need an area in settings to link several databases and allow to name them. At best several databases can be grouped/named together to still allow spoiler, token or several connected sets in independent card files to be loaded at once.
It would then be convenient to switch between the named "databases/profiles/games" right from a menu option or the settings page.
Would you suggest to do it differently @ebbit1q?

**Comment by ebbit1q** [comment] 2020-09-24 13:21
first step would be easy switching for databases, I propose adding an attribute to the xml that specifies the game in order to facilitate switching
