### ISSUE TITLE
libssl-1_1.dll

### ISSUE THREAD

**Issue by satirobcn** [Cockatrice/Cockatrice#4237] opened 2021-01-31 06:52 UTC
windows 7
  
when i click in "next" of oracle instalation:  error of net: TLS initialization failed

when i begin cockatrice or when i begin oracle in cockatrice folder:  libssl-1_1.dll It is not designed to run on windows or it contains an error. Please try to install the program again using the original installation media, or contact your system administrator or software manufacturer for assistance.

when i try of update client:  cockatrice was not built with SSL support, so updates cannot be downloaded automatically. Please visit the download page to update it manually

sorry for the inconvenience but it is the first time I write here ... I do not know if it is the right place and I do not know if I have raised the problem correctly ... Also I do not know English and I am doing all this with google translate, so no I know if it will be well translated.
The problem is that I get an error when entering cockatrice, in principle it is not a problem because the program works well, but later I can neither update the sets nor update the client. There seems to be a problem with the dll file and I don't know how to fix it.
Thank you very much for your time and sorry for the inconvenience.

**Comment by tooomm** [comment] 2021-01-31 13:39
Hey @satirobcn. That's no problem.

Do you use Portable Mode?
32bit or 64bit version of Cockatrice?

Maybe it's similar to https://github.com/Cockatrice/Cockatrice/issues/4233...

**Comment by ZeldaZach** [comment] 2021-01-31 19:29
This is a dupe of #4233

**Closed by ZeldaZach** 2021-01-31 19:29 UTC
Labels: Bug

**Comment by satirobcn** [comment] 2021-02-05 22:45
sorry, i forgot add version... Cockatrice (32-bit)
Versión 2.8.0 (2021-01-26)... same problem

**Comment by satirobcn** [comment] 2021-02-05 22:47
sorry zeldazach a dupe? :/

**Comment by satirobcn** [comment] 2021-02-05 22:50
thanks @tooomm

**Comment by satirobcn** [comment] 2021-02-05 22:50
sorry @ZeldaZach ... a dupe??

**Comment by tooomm** [comment] 2021-02-05 22:53
Just make sure to go to the other issue and follow there. It's about the same problem and we want track them in a single issue ticket.

If you comment there or hit the `Subscribe` button on the right you'll get notifications once there are new comments or any updates.

There is no fix for this problem yet. :(

**Comment by satirobcn** [comment] 2021-02-05 22:58
thanks @tooomm  for your patience... im new here, first time i enter in GitHub.

**Comment by satirobcn** [comment] 2021-02-05 23:00
who is "portable version" ? how i can view this?

**Comment by tooomm** [comment] 2021-02-05 23:19
When you run the setup file in order to install Cockatrice... it asks you.

`Normal installation` or `Portable Mode`

Which did you try?
