### ISSUE TITLE
Apply new code style to all files

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3027] opened 2018-01-19 15:04 UTC
After #3009 is merged now, all files should get updated to have a solid, clean starting point to apply and enforce the new rules more easily in the future.

A consistent code base would be way more friendly to new contributors who want to look into the project to get started.

**Comment by Daenyth** [comment] 2018-01-19 15:06
dupe of #2183 more or less. With a clang-format config set, it would accomplish this.

**Closed by Daenyth** 2018-01-19 15:06 UTC
