### ISSUE TITLE
Dragging face-down cards to library reveals them to all players.

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Cockatrice/Cockatrice#909] opened 2015-04-04 09:49 UTC
This seems to have changed into the latest version.
When dragging a face-down card to a hidden zone, it is revealed to all players.

While this is as it should be for permanents, this feature is also used for things like Vampiric Tutor, and mulligans in EDH. Unless a way is created to handle those other functions, this change isn't good.

**Comment by ctrlaltca** [comment] 2015-04-04 10:06
duplicate of #884

**Closed by ctrlaltca** 2015-04-04 10:06 UTC
