### ISSUE TITLE
Card database error

### ISSUE THREAD

**Issue by kphil61** [Cockatrice/Cockatrice#2355] opened 2017-01-10 03:18 UTC
<b>OS:</b>
OS X 10.11.6

<b>Cockatrice version:</b>
3498b16
___
<br>

I'm not sure if this is the right place to report this, but I would like to report a problem with the card database I downloaded from the default link in Cockatrice. The problem is with Kamigawa flip cards. I'll use "Rune-Tail, Kitsune Ascendant" as an example. Only the flip side, "Rune-Tail's Essence", shows up in the card database and the text for the card only includes text from this side.

**Comment by Nightfirecat** [comment] 2017-01-10 03:28
Duplicate of #2207; this is a known issue with MTGJSON: mtgjson/mtgjson#240.

**Closed** 2017-01-10 16:20 UTC
