### ISSUE TITLE
Windows scalining on 4k monitor

### ISSUE THREAD

**Issue by ummshsh** [Cockatrice/Cockatrice#4780] opened 2023-03-26 21:21 UTC
1. Set scaling in windows
2. Open app
3. Everything not scaled and on 4k screen everything is too small

With this compatibility scaling setting, scaling is working, but all text is super blurry (with any setting on this screen really)
![image](https://user-images.githubusercontent.com/14292399/227805668-63de667d-3eda-4802-8ba7-0e9b7b99d19c.png)

Also, cards are super small not even on 4k screen, can we make card size adjustable there?

**Comment by ebbit1q** [comment] 2023-03-27 08:18
duplicate of https://github.com/Cockatrice/Cockatrice/issues/1937 please leave a comment on existing tickets instead of opening a new one

**Closed by ebbit1q** 2023-03-27 08:18 UTC
Labels: Bug
