### ISSUE TITLE
Settings Screen overflows Vertical Resolution

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2153] opened 2016-08-29 23:38 UTC
Ubuntu Trusty
1024x600 resolution

Settings window cuts off below Card database, even maximized window.  No vertical scroll.

**Comment by Daenyth** [comment] 2016-08-29 23:39
Related to but not duplicate of #1904 - there's some fixed pixel sizes in the layout.

**Comment by tcjiang9** [comment] 2016-10-30 01:44
@Daenyth @tritoch Hi, I'd like to pick up this issue. Could you point me at where in the codebase to look?

**Comment by ZeldaZach** [comment] 2016-10-30 02:22
Hey @tcjiang9 I recommend you look in the tabs/windows files at `cockatrice/cockatrice/src/`. If you come onto our gitter chat, we can probably help you further!

**Comment by Daenyth** [comment] 2016-10-30 12:38
I'd start with DlgSettings (or named similarly) and go from there to see what it instantiates.

In general the fix is probably going to involve removing fixed pixels and seeing if there's a way to do a bit more responsive layout with percentages.

If you want to get ambitious and make this not easy, I'd also be open to the idea of using QML to completely rewrite portions of the UI.

**Comment by tcjiang9** [comment] 2016-11-01 02:55
@Daenyth I think I'll roll with the easy one for my first ticket. I'll have a bunch of free time after work on Wednesday so I'll try to take a crack at it then.

**Comment by ZeldaZach** [comment] 2020-10-06 22:29
If this is still an issue on the latest ubuntu please reopen

**Closed by ZeldaZach** 2020-10-06 22:29 UTC
Labels: App - Cockatrice, Defect - Basic, Good first issue, Hacktoberfest, UI / UX

**Comment by ebbit1q** [comment] 2020-10-07 14:38
linking https://github.com/Cockatrice/Cockatrice/issues/4114
