### ISSUE TITLE
Casting Portent targeting an opponent

### ISSUE THREAD

**Issue by isleep2late** [Cockatrice/Cockatrice#2748] opened 2017-06-03 00:06 UTC
<b>OS: N/A</b>
<b>Cockatrice version: N/A</b>
__________
A user recently PM'd me regarding the card Portent, which is now starting to see play in Legacy. For reference, here is the effect of the card:

"Look at the top three cards of target player's library, then put them back in any order. You may have that player shuffle his or her library.
Draw a card at the beginning of the next turn's upkeep."

I brought up the issue of targeting your opponent with this card, which is something that you may want to do. It becomes difficult and tedious, even if it is possible. Daenyth suggested the following sequence:

"@Daenyth 19:59
A casts Portent on B
B reveals top 3 cards to A
A tells B order by number
B shift+drags cards face down to table then back to deck to reorder
B doesn't learn what any cards are
Like I said, playable but awkward"

I was wondering if this can be made a lot more reasonable in a future version of Cockatrice. I would imagine if this card did start to see play regularly in a format, users may want to have this sequence happen frequently. Is there anything that can be done about this?

**Comment by ZeldaZach** [comment] 2017-06-03 03:42
Looking at this, I really want to look at reverting the view library method for other players and working on a solution to ensure that it is closed before game play continues... An idea could be that we attach a timer to it and after X time, it goes from editable to not, so it won't get updates from the game playing. That's my best idea currently. Any suggestions on this?

**Comment by tooomm** [comment] 2017-06-03 14:10
No idea what the `view library method for other players` is...
<br>

>An idea could be that we attach a timer to it and after X time, it goes from editable to not

Freeze the window on next phase change as an alternative? The timer will never have a good value.
But both sounds not great to me.

**Comment by ZeldaZach** [comment] 2017-06-03 17:41
> Freeze the window on next phase change as an alternative? 

That's an idea that could probably work. @Daenyth opinion?

**Comment by ShrewMaster** [comment] 2017-06-04 09:37
Can a common solution be found between this issue, #428 and #625 ? Maybe even merge all of them together in the same issue? From what I've been reading on Github about this problem, I believe not giving players write access to their opponents' libraries has caused more problems than it solved.

Also, why not simply post a message in the chat when the library is closed? That way, players don't need to draw cards or perform other actions until their opponent has finished resolving their effects on their libraries.

**Comment by Daenyth** [comment] 2017-06-05 11:20
> has caused more problems than it solved.

It solved the problem of players being able to know every card their opponent draws

**Comment by tooomm** [comment] 2017-06-05 11:33
The initial change was needed I guess, but

>simply post a message in the chat when the library is closed

might also do the trick.

**Comment by Daenyth** [comment] 2017-06-05 11:42
The solution I proposed before should work for this too:
When a player reveals part of their deck, the person it's revealed to should get a snapshot, not a live updating view. They should have the ability to modify the deck as of that snapshot, but any changes to the deck made by anyone else should reset the snapshot. It would work with 'reveal top' as well, they'd just get a new snapshot each time they move a card

**Comment by isleep2late** [comment] 2017-06-06 19:36
Some of the members I've talked to have also mentioned the card Praetor's Grasp as almost impossible to do on Cockatrice. (Search target opponent's library for a card and exile it face down. Then that player shuffles his or her library. You may look at and play that card for as long as it remains exiled.) So maybe the open library thing could be the way to go.

**Comment by Daenyth** [comment] 2017-06-06 23:57
#625

**Comment by ZeldaZach** [comment] 2020-10-04 18:42
Dupe of #625

**Closed by ZeldaZach** 2020-10-04 18:42 UTC
Labels: App - Protocol / API, UI / UX
