### ISSUE TITLE
Kamigawa Flip Cards Not Working

### ISSUE THREAD

**Issue by redcrow87** [Cockatrice/Cockatrice#2257] opened 2016-11-01 20:08 UTC
<b>OS:</b>
WINDOWS 10

<b>Cockatrice version:</b>
277d7e2 (2016-06-30)

___
<br>

My Issue is that, since I've updated to the new Cockatrice version and update the card database, many of the Kamigawa Flip Cards such as "Erayo, Soratami Ascendant" do not appear in the database, BUT their flipped versions (in this case "Erayo's Essence") do appear.

Other examples are Nezumi Graverobber, Nezumi Shortfang, and Orochi Eggwatcher. All of which don't appear when searching the card database in Cockatrice, but all of which have their flipped versions appear.

Is anyone else experienced this issue? Help would be appreciated.

Thanks

**Comment by Nightfirecat** [comment] 2016-11-01 20:23
Pretty sure this is caused by mtgjson/mtgjson#240, not a fault of Cockatrice itself.

**Comment by Nightfirecat** [comment] 2016-11-01 20:23
Actually, this issue is a duplicate of #2207.

**Closed** 2016-11-01 20:28 UTC
