### ISSUE TITLE
add turn counter and life to log

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#957] opened 2015-04-12 20:08 UTC
[XMage](https://github.com/magefree/mage) shows which turn you are in right now (#66) + both life total values.

I kinda like that idea!

```
9:59 AM: a attacks with 0 creatures
9:59 AM: Turn 5 b (20 - 20)
9:59 AM: b draws a revealed card (Arbor Colossus)
9:59 AM: b plays Forest
```

`a` and `b` being player names

**Comment by ZeldaZach** [comment] 2015-04-12 20:50
I'm a fan of the turn counter, but there's no real reason for a life result in chat unless a life change occurs

**Comment by poixen** [comment] 2015-04-12 22:22
Turn counter would be good. Its on my list already. Been thinking about ways to handle it. Thing with Xmage is that the rules system manages turns. We have so many cases where turns can be wrong.

**Comment by tooomm** [comment] 2015-04-12 22:46
I'm always wondering why everybody at any given time can interact with his opponents turn and just hit pass for example?
If pass could just be hit by your opponent (not by you at all) IF you enter the end phase before, there should be less confusing miss clicks etc. and the counter could go up one by one.

**Comment by ZeldaZach** [comment] 2015-04-12 22:47
@tooomm I'm a fan of greying out "pass" except for the next player in the line and (maybe?) the room creator to speed the game along.

A discussion for another ticket for sure.

**Comment by Daenyth** [comment] 2015-04-12 23:15
I dislike that a lot. A very common play style has to going to your end
step and then the other player hitting pass. Turn counters without rules
management are not useful; apprentice had them and they told you nothing.

We should find out the use case people want to address.

**Comment by woogerboy21** [comment] 2015-04-12 23:19
I like the idea of turn counters for gold fishing personally.  In game though... eh... might have a use.

**Comment by ZeldaZach** [comment] 2015-04-12 23:19
There's no card or format that relates to the number of turns, as far as I know

**Comment by tooomm** [comment] 2015-04-12 23:23
It would make the log more useful in general. It basically just adds information - you don't have to use them.

- You could make replays jump between turns for example (like chapters) or you could tell somebody that that weird thing happened in turn 8 or 9 and make him find things easier.
- You could check more easily if that 5th land in turn 4 is "legal" or if there was a misplay etc.
- You could check the extra round you are in more easily.
- ...

**Comment by Nightfirecat** [comment] 2015-04-13 00:13
@ZeldaZach [Serra Avenger](http://gatherer.wizards.com/Pages/Card/Details.aspx?name=serra%20avenger)

**Comment by ZeldaZach** [comment] 2015-04-13 00:14
@Nightfirecat Thanks for proving me wrong xDD

Still, I don't know if this turn counter thing is really helpful past that

**Comment by Nightfirecat** [comment] 2015-04-13 00:16
Probably not. It's usually not hard to count to 3 for that case.

**Comment by poixen** [comment] 2015-04-13 06:41
I don't think this idea will work. For it to work we either need a rules system, or to have the disabled pass until end is selected. 

The first will never happen, and the 2nd has too many problems. 

+ it slows down play.
+ dice rolls. If I lose a dice roll and pass, what then? The server should not decide the starting player from the die roll. 
+ after working with the replays I can tell you that we can't do any kind of jumps. The replay must have linear playback. Only the speed can change. 

Overall i think its a nice idea, though the effort to get a stable version working can be redirected into other features/issues.

**Comment by tooomm** [comment] 2015-04-13 20:38
Ok, no improvement for replays connected to this.
But I don't see why this should slow down play at all? As @Daenyth stated above players use the "end step" phase anyway and wait for their opponents to take over the turn if they don't want to play end of turn stuff first.

About dice rolls:
Hmm, this case needs further adjustments. Maybe no player should receive priority at first.
The player that hits "pass" or "untap" first is going to start the game and receives priority first --> turns start counting.
There could also be a check if there was some more action in this turn before (log), so if you just hit pass without drawing for example it won't count as turn.

There are some dependencies, I see.
We don't need to make it fail safe, though. People will get used to a working play style anyway. Or don't care about that feature (accurate turn counter), which should be fine as well.

**Comment by woogerboy21** [comment] 2015-04-14 14:14
seems like the turn counter request has been made multiple times and talked about before by the community.  might not be a bad thing to eventually work in. just my $0.02.  if people didn't find it useful they probably wouldn't have talked about it.

**Comment by ZeldaZach** [comment] 2015-04-14 15:16
Maybe we can make a "local" turn counter that people can maintain themselves throughout the game

**Comment by anoda9** [comment] 2015-04-15 16:27
One solution could be: the turn counter only starts after certain game actions are taken i.e. someone plays a card to the table or changes phases. Triggering on someone playing a card to the table would be problematic with certain pre-game actions (leylines, serum powder, moving your commander around in edh), so triggering on changing phases might be better. So as soon as a player moves to 1st main, the turn counter begins. Or as soon as someone clicks "end" or presses f10 - the current turn is marked as "turn 1". 

I definitely hate the idea of disabling certain controls for certain players/at certain times - that seems like it will just cause frustration/make the program harder to use.

**Comment by mpalmujoki** [comment] 2020-03-06 13:53
Sorry for digging this old issue up again. The local turn counter would be quite sufficient as a starter. 

I can't fathom of a way to automatically count it. Some decks, i.e. dredge, might not do anything on their first turn. How do you compare that starting player to swapping the turn to the starting player before the match starts?

Forcing to go to Main would be an option.. I think I'd support that. But say, it should only count the first time you go to first Main. Then again, after all, you don't force folks to go to Main even while they play. You can after all, do anything in the Draw phase, technically, but not gamewise. 

I think the best thing would be a manual counter, that would auto increment each time you get your turn, but you'd have to start manually, and that you could adjust if it went wrong.

**Comment by ZeldaZach** [comment] 2020-11-03 21:37
Gonna close as a dupe of #3905 since we're doing more tracking there nowadays.

**Closed by ZeldaZach** 2020-11-03 21:37 UTC
Labels: App - Cockatrice, Suggestion, UI / UX
