### ISSUE TITLE
XML Oversights and Filter Option

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1887] opened 2016-03-25 17:33 UTC
<b>OS: OSX 10.11.3</b>

<b>Cockatrice version: 323fc06</b>

___
<br>

-Chandra, Flamecaller doesn't have her elemental tokens set as a related card for her.

-Vesuva doesn't cipt

-Add a filter option to allow players to hide buddy only games.....Magic players do things out of habit more often than not these actions aren't checked against logic. Those buddy only games just end up cluttering up the list of games for people who aren't buddies with the room creator, which would be nearly all of the Cockatrice population.

**Comment by ctrlaltca** [comment] 2016-03-25 21:18
1. Chandra: tokens seems to be already present for chandra: https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml#L1111 , and after a quick test i've been able to confirm they seems to work.

2. Vesuva: ```You may have Vesuva enter the battlefield tapped as a copy of any land on the battlefield.``` we can add a check to oracle to add the cipt flag on cards with a similar text. I'd like to hear @Daenyth's opinion on this before implementing such a change.

3. By now Cockatrice knows the list of users that you decided to ignore or to add as a buddy, but has no knowledge of how other players flagged you. So, cockatrice is unable to know if you are in the buddy list of another player, and thus is not abel to know if you'll be able to join a buddy-only game or not, until you try. This would require a server-side change, making servatrice filter out games that you can't join before passing the game list to cockatrice.

**Comment by Daenyth** [comment] 2016-03-28 21:30
1) Reverse-related bugs should be filed on https://github.com/Cockatrice/Magic-Token (but it's fine that it's here).

2) This is probably reasonable 

3) is more simply handled by hiding all buddy-only games.

**Comment by Psithief** [comment] 2016-03-31 04:38
Vesuva already follows our unspoken rules of `cipt`. There's a player choice involved, and if it isn't made the card comes in untapped. The player has to spend some time to annotate the card to make it a copy of another card, so that's the time to tap it.

For the counter-example: 'Shock'lands have the cipt flag set because if the choice isn't made they come in tapped. In that case, the player untaps the land and loses 2 life at the same time.

We've already gone over this in #1082.

Many cards exist that make playing Vesuva untapped as itself make sense. 

Cards that change land types
* Blood Moon, Urborg, Tomb of Yawgmoth, Celestial Dawn, Stormtide Leviathan, Prismatic Omen

Cards that give lands mana abilities
* Chromatic Lantern, Joiner Adept, Riftstone Portal

**Comment by Nightfirecat** [comment] 2016-03-31 07:10
> Many cards exist that make playing Vesuva untapped as itself make sense.

> Cards that change land types

> * Blood Moon, Urborg, Tomb of Yawgmoth, Celestial Dawn, Stormtide Leviathan, Prismatic Omen

> Cards that give lands mana abilities

> * Chromatic Lantern, Joiner Adept, Riftstone Portal

None of these cards listed cause Vesuva not to etb tapped.

**Comment by ctrlaltca** [comment] 2016-03-31 07:20
I suppose that @Psithief means that if you play Vesuva and already have one of those cards in play, you probably won't chose to use Vesuva's ability.

**Comment by ctrlaltca** [comment] 2016-03-31 07:26
So, i think we can close this:
1. seems to already have been fixed in tokens.xml
2. it's probably correct to keep the current behavior, since Vesuva only becomes tapped if the player decides to trigger an ability
3. duplicate of #1823

**Closed** 2016-03-31 07:26 UTC
