### ISSUE TITLE
Feature request: resume game from replay

### ISSUE THREAD

**Issue by buenaventura01** [Cockatrice/Cockatrice#4296] opened 2021-03-25 15:11 UTC
Magic games often take quite a while (commander especially), and you might want to suspend a game and continue another day. I understand that a comprehensive replay file is generated once the last player leaves a game. Could this be used to make a feature where you can resume a game from replay? And then invite the other players who played and be able to put them in the right seat, of course. That would be great!

**Comment by ebbit1q** [comment] 2021-03-25 15:32
duplicate of https://github.com/Cockatrice/Cockatrice/issues/3939

> This is a no-fix because it enables access to private information during a match. I also don't see a possible implementation path on this as it would require a major overhaul of what the server is capable of, which I'm not comfortable with at this time.

https://github.com/Cockatrice/Cockatrice/issues/3939#issuecomment-699689867

**Closed by ebbit1q** 2021-03-25 15:32 UTC
