### ISSUE TITLE
"Enters the battlefield tapped" stopped working

### ISSUE THREAD

**Issue by CTimmerman** [Cockatrice/Cockatrice#5114] opened 2024-09-20 20:33 UTC
**System Information:**

Client Version: 2.9.0 (2023-09-14)
_______________________________________________________________________________________

Geothermal Bog "enters tapped", but doesn't because the code probably still looks for "enters the battlefield tapped".
_______________________________________________________________________________________

**Steps to reproduce:**
 - Play Geothermal Bog
 - Notice it is not tapped like it used to be before the wording change.

**Comment by ebbit1q** [comment] 2024-09-20 21:22
duplicate of #5093, fixed by #5094

**Closed by ebbit1q** 2024-09-20 21:22 UTC
Labels: Bug
