### ISSUE TITLE
Frankenstein Set - Combining Custom Cards + Existing Cards

### ISSUE THREAD

**Issue by StyrofoamKing** [Cockatrice/Cockatrice#4224] opened 2021-01-23 18:56 UTC
**Similar Requests**

**Description of New Feature**
So, as a fun exercise, I'm working on MtG set that's 90% existing cards, combined with about 30 custom cards. So far, I succeeded in creating the 30 custom cards (they show up in Deck Editor, art and all!)

Now, for the 250+ existing cards: is there a handy way to do one of the following:
1. Create a custom set xml that simple lists the existing card names, without having to type out the full xml tags for each card?

2. Add the custom set "tag" to an existing card? If I'm able to do this, can it be shared to others, so they can play cards "from my set?"

Thank you!

**Additional Context**

**Comment by ebbit1q** [comment] 2021-01-23 21:28
1 what you are looking for is called learning a scripting language to process text (or just a sophisticated text editor)

2 cards that are in your custom set will be shown as in that set, there is no property of a card that distinguishes it from being a custom card or vice versa (all cards are just cards that show up in sets).

2.1 your custom xml file can be shared with whoever you'd like. if you included the picurl property the cards will use that image. if you simply have a loose collection of images they will need to have the same filenames as your cards' names and be placed in the CUSTOM image directory separately from the xml. see https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-custom-sets-follow-these-steps

**Comment by skwerlman** [comment] 2021-01-25 05:22
related: #4040

**Comment by ZeldaZach** [comment] 2021-01-30 22:23
I'm gonna call this a dupe of #4040 and/or not relevant to the project.

**Closed by ZeldaZach** 2021-01-30 22:23 UTC
Labels: Troubleshooting
