### ISSUE TITLE
First run dialog trigger

### ISSUE THREAD

**Issue by camaroman86v6** [Cockatrice/Cockatrice#1118] opened 2015-05-31 03:15 UTC
As of a few weeks ago, the dialog box triggers every time I open the program asking me to update sets. I talked to ZeldaZach on cockatrice and he suggested I install Qt5, which I did.

I then built cockatrice with this:
cmake .. -DCMAKE_PREFIX_PATH=~/Qt/5.4/gcc_64 -DWITH_QT4=0
make
sudo make install

This makes cockatrice fail to run at all, giving me this if I run it from command line:
cockatrice: symbol lookup error: cockatrice: undefined symbol: _ZN6QDebugD1Ev

If I compile with qt4, it runs, but it always asks to update sets. I'm running Mint Cinnamon.

**Comment by ctrlaltca** [comment] 2015-05-31 13:28
> As of a few weeks ago, the dialog box triggers every time I open the program asking me to update sets

No dialog exists that asks you to update the sets, i suppose you meant it asked you if you want to enable some sets, so this would be a dupe of #1102.
Anyway, it's nice to know that the problem is probably specific to Qt4, so i'll try to test it to solve the issue.

> This makes cockatrice fail to run at all, giving me this if I run it from command line:
> cockatrice: symbol lookup error: cockatrice: undefined symbol: _ZN6QDebugD1Ev

Cockatrice is starting up loading a qt version different from the one that has been compiled with. If Qt5 is installed inside a subdirectory of your home folder, cockatrice won't be able to find it, so it's trying to load another copy of the library.
This can be solved installing qt5 globally on the system, or manually adding the "~/Qt/5.4/gcc_64" path to ld's configuration.

**Closed** 2015-05-31 14:33 UTC

**Comment by camaroman86v6** [comment] 2015-05-31 14:36
Apologies, I quit reading that dialog box closely a while ago because it was so annoying.

It seems I am unable to find complete instructions for how to use the Qt5 installer from their website to completely install the current version. It fails to update path variables on it's own and I haven't found anything saying what path variables to change.

Installing qt5 via the repositories seems to have fixed both problems, however,

**Comment by ctrlaltca** [comment] 2015-05-31 14:37
And if you compile an updated version of cockatrice, i've just fixed the issue a few minutes ago.
Thank you for reporting!
