### ISSUE TITLE
replay issues with 59da62d

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1525] opened 2015-09-17 02:14 UTC
In the 59da62d build:
- top card of the library displays a blank card back instead of the magic card back
- (unreproducible bug): sometimes graveyards and exiles are not viewable (can't double click to pop out). I think the situation that causes this to happen is when the replay is so long that the progress bar goes past the limit on the right side. Once it reaches that point, you can't view graveyards or exile anymore.
  Edit: actually, this doesn't seem to be the triggering factor. I encountered a bug once watching a long replay where I couldn't view the gy or exile, but I'm not sure what caused it. 

Additional suggestion:
When a replay is opened, it should start playing immediately. 99% of the time when I open a replay, the first thing I do is click play. Having replays start playing automatically would save effort in the vast majority of cases.

**Comment by ZeldaZach** [comment] 2015-09-17 02:32
> top card of the library displays a blank card back instead of the magic card back

Fixed in the newest build

> (unreproducible bug): sometimes graveyards and exiles are not viewable (can't double click to pop out). I think the situation that causes this to happen is when the replay is so long that the progress bar goes past the limit on the right side. Once it reaches that point, you can't view graveyards or exile anymore.

How can a replay go past the progress bar? That doesn't make sense as the bar is timed to the match length.

> When a replay is opened, it should start playing immediately. 99% of the time when I open a replay, the first thing I do is click play. Having replays start playing automatically would save effort in the vast majority of cases. 

Doable, but is it really that much effort for you to press the "play" and/or "fast forward" buttons?

**Comment by anoda9** [comment] 2015-09-17 03:59
> Doable, but is it really that much effort for you to press the "play" and/or "fast forward" buttons?

No, but it is tedious :) It's mostly the principle - if a user does the same sequence of actions 99% of the time, the client should just be helpful and do it for them. Same idea as for making the client autoconnect on startup - 99% of the time, that's the first thing people do, so you might as well automate it. 

>How can a replay go past the progress bar? That doesn't make sense as the bar is timed to the match length.

If you watch a really long replay, the progress indicator will go to the end of the bar, then it will disappear entirely (the green shading goes away, leaving just the black frequency graph behind).

**Comment by ctrlaltca** [comment] 2015-09-17 07:14
> When a replay is opened, it should start playing immediately

I think this is too much of a personal preference. If we make it to default autoplay, tomorrow someone will open up a ticket saying "yo crappy devs you broke my cockatrice replays" etc..
A setting could be fine.

> If you watch a really long replay, the progress indicator will go to the end of the bar, then it will disappear entirely (the green shading goes away, leaving just the black frequency graph behind).

This is indeed a bug. If you happen to find a replay file that triggers the bug, please attach it to the ticket.

**Comment by Nightfirecat** [comment] 2015-09-17 07:17
imo defaulting to autoplay (as a setting) would be fine. Seems to me that most people opening replays want to start watching it right away.

**Comment by Daenyth** [comment] 2015-09-17 10:43
I think defaulting to autoplay without a setting is fine. Settings aren't
free, it increases the code base and makes the client more confusing to use.

**Comment by tooomm** [comment] 2015-09-18 10:59
I'm not sure if I like autoplay.
I sometimes open several replays if I want to look special decks or my last draft games with the same deck against several opponents to view them later in a row and don't need to search my replays before watching the next one again.
Autoplay will break this behavior.

On another note... we are hopefully getting dragging in the timeline at some point in the future. With that functionality in the client I don't want my replays to start when I open them. I want to look for a right place to start the replay first or jump to a special action first.

**Comment by woogerboy21** [comment] 2015-09-19 00:12
>On another note... we are hopefully getting dragging in the timeline at some point in the future. With that functionality in the client I don't want my replays to start when I open them. I want to look for a right place to start the replay first or jump to a special action first.

I don't think anyone is working on this are they?  Last I remember looking this would take a rewrite of how replays are stored but would have to look into it again at this point as focus is else were.

**Comment by tooomm** [comment] 2015-09-19 10:33
Noone is afaik. But many people requested it and there was much interest in general. So I think we will try to implement it at some point because it finally makes replays really useful. :)

**Comment by Daenyth** [comment] 2015-09-20 13:20
It wouldn't take a rewrite of how they are stored but rather how we process
game events in the game view

**Comment by ctrlaltca** [comment] 2016-01-15 10:11
Sorry, didn't mean to close this, but github didn't get what i meant for "partially fixes #1525".

**Comment by ctrlaltca** [comment] 2016-01-15 10:16
By the way, what is this ticket about? Summing up, a lot of different things:
 * ~~top card of the library displays a blank card back instead of the magic card back~~ fixed
 * ~~replay progressbar problem on long replays~~ fixed
 * sometimes graveyards and exiles are not viewable (i've not been able to reproduce this yet)
 * replay autoplay on open (debated: yes/no/configurable)
 * drag on replay timeline to move to a specific moment in the replay
 * rewrite some code to make replays more easy to navigate within

**Comment by Nightfirecat** [comment] 2016-01-15 16:28
> * sometimes graveyards and exiles are not viewable (i've not been able to reproduce this yet)

Could be now that the progress bar doesn't overflow anymore, it can't be reproduced anymore.

**Comment by ctrlaltca** [comment] 2016-01-15 17:43
> Could be now that the progress bar doesn't overflow anymore, it can't be reproduced anymore.

I don't think so, the overflow was just limited to the calculation of the width of the "green rectangle" that we paint as a progress bar.

**Comment by ZeldaZach** [comment] 2020-10-23 20:01
Most of this doesn't seem relevant anymore, but if any parts are we can file new tickets.

**Closed by ZeldaZach** 2020-10-23 20:01 UTC
Labels: App - Cockatrice, Suggestion
