### ISSUE TITLE
32-bit builds / portables have incorrect CMake Bundle DLLs (Missing libssl-1_1.dll and libcrypto-1_1.dll)

### ISSUE THREAD

**Issue by supersardus** [Cockatrice/Cockatrice#4233] opened 2021-01-28 19:27 UTC
Cockatrice 2.8.0 32 bit (Portable Version)
Windows 7 Enterprise Service Pack 1 32 bit
_______________________________________________________________________________________

Hi all,

I used to play without any problems until last week with the previous version of Cockatrice, but today I had to upgrade to 2.8.0 version and it doesn't work.
As usually I choose Portable Version because I don't have administrator's rights on this computer. After the installation, I try to run Cockatrice and receive the error message attached. Sorry, it is in italian, it should sound something like "libssl-1_1.dll is not intended to be used with Windows or contains an error". I tried several times to delete the folder, restart pc and download again but this happens everytime.
Can you help me please?

**Comment by tooomm** [comment] 2021-01-28 20:21
For me, the portable version of Cockatrice 2.8.0 runs as fine as the installed version.

However, I realized that the 2.8.0 installation did install a more recent vcredist file. The portable version probably uses it as well. I can only assume your host computer where you try to run Cockatrice in portable mode doesn't have the appropriate vcredist file installed?

Note: I ran the 64bit version. Maybe it's an issue with the 32bit file?

**Comment by nandopando94** [comment] 2021-01-28 20:38
i've the same problems. i don't know how to fix this :(

> Cockatrice 2.8.0 32 bit (Portable Version)
> Windows 7 Enterprise Service Pack 1 32 bit
> 
> Hi all,
> 
> I used to play without any problems until last week with the previous version of Cockatrice, but today I had to upgrade to 2.8.0 version and it doesn't work.
> As usually I choose Portable Version because I don't have administrator's rights on this computer. After the installation, I try to run Cockatrice and receive the error message attached. Sorry, it is in italian, it should sound something like "libssl-1_1.dll is not intended to be used with Windows or contains an error". I tried several times to delete the folder, restart pc and download again but this happens everytime.
> Can you help me please?

**Comment by supersardus** [comment] 2021-01-29 16:12
Just a little update.
I tried to delete the 2.8.0 folder and installed the 2.7.5 Portable Version: I confirm that with the 2.7.5 I don't get any error during installation or run of Cockatrice.exe. Only when I try to connect to server I receive the message attached that says that the 2.8.0 is needed.
The new libssl-1_1.dll is different, because for 2.8.0 it's updated to 9 Dec 2020 while for 2.7.5 it's updated to 14 Aug 2020. I tried to overwrite this dll to "restore" the old one, but when I do that if I run Cockatrice I receive another error, this time for libcrypto-1_1.dll. I don't know if it's an "independent" error or if it is related to the replaced libssl.

I hope this can help! Thanks in advance

**Comment by Bogenholz** [comment] 2021-02-01 15:39
Hi everybody,

I've the same problem with the 32 bits portable version.

**Comment by ZeldaZach** [comment] 2021-02-03 20:13
Moving to high priority, as this is impacting a large number of users

**Comment by satirobcn** [comment] 2021-02-05 23:06
windows 7 Cockatrice (32 bit)
Version 2.8.0 (2021-01-26)

when i click "next" from oracle install: network error: TLS initialization failed

when I start with cockatrice or when I start with Oracle in the cockatrice folder: libssl-1_1.dll It is not designed to run on Windows or contains an error. Try installing the program again using the original installation media, or contact your system administrator or software manufacturer for assistance.

when I try to update the client: cockatrice was not created with SSL support so updates cannot be downloaded automatically. Visit the download page to update manually

sorry for my clumsiness and inconvenience but this is the first time I have written here ... I don't know if it is the right place and I don't know if I have posed the problem correctly ... Also, I don't know English and I'm doing all this with google translator , so I don't know if it will be well translated.
The problem is that I get an error when entering cockatrice, in principle it is not a problem because the program works well, but then I can neither update the sets nor update the client. There seems to be a problem with the dll file and I don't know how to fix it.
Thank you very much for your time and sorry for the inconvenience.

**Comment by Fenrirthviti** [comment] 2021-02-08 01:57
I had thought I wrote this down somewhere else, but just to log it here as well, the issue is that the 32bit version of the libssl library is not being copied, and for some reason it grabs the 64bit version instead (64bit is denoted by the `_1`). CI just needs to grab the correct 32bit file and this issue will be resolved. I've tested 32bit locally with manually providing the libssl deps and it works fine.

**Comment by ZeldaZach** [comment] 2021-02-08 01:59
Yeah that's the exact issue @Fenrirthviti, just GitHub actions seems to have issues finding that lib. We need to look into it, but if you'd like to review our action build code feel free to! Would be appreciated.

**Comment by Bogenholz** [comment] 2021-02-08 12:53
Hi everyone,

I've solved the issue replacing two dll files. First I've downloaded the **libssl-1_1.dll** for 32 bits and replaced for the one in the cockatrice folder. Then when I restart the program it shows me the same issue but with the **libcrypto-1_1.dll**, so I replaced that dll file too and then Cockatrice runs fine. 
I was able to update the cards database, connect to the server with no problem.

I hope this will be helpful.

Live Long and Prosper!

**Comment by tooomm** [comment] 2021-02-08 13:33
I assume this is not related to portable builds at all then?
It's a 32bit issue - no matter if you use portable mode or normal installation?

**Comment by Bogenholz** [comment] 2021-02-08 13:42
> I assume this is not related to portable builds at all then?
> It's a 32bit issue - no matter if you use portable mode or normal installation?

I think it's only in the 32 bits portable version, but really not sure.

**Comment by nandopando94** [comment] 2021-02-08 19:49
> Hi everyone,
> 
> I've solved the issue replacing two dll files. First I've downloaded the **libssl-1_1.dll** for 32 bits and replaced for the one in the cockatrice folder. Then when I restart the program it shows me the same issue but with the **libcrypto-1_1.dll**, so I replaced that dll file too and then Cockatrice runs fine.
> I was able to update the cards database, connect to the server with no problem.
> 
> I hope this will be helpful.
> 
> Live Long and Prosper!

IT WORKS! thank you <3

**Comment by hengarken** [comment] 2021-02-09 12:17
> Hi everyone,
> 
> I've solved the issue replacing two dll files. First I've downloaded the **libssl-1_1.dll** for 32 bits and replaced for the one in the cockatrice folder. Then when I restart the program it shows me the same issue but with the **libcrypto-1_1.dll**, so I replaced that dll file too and then Cockatrice runs fine.
> I was able to update the cards database, connect to the server with no problem.
> 
> I hope this will be helpful.
> 
> Live Long and Prosper!

Where did u download this files?

**Comment by Bogenholz** [comment] 2021-02-09 13:37
> > Hi everyone,
> > I've solved the issue replacing two dll files. First I've downloaded the **libssl-1_1.dll** for 32 bits and replaced for the one in the cockatrice folder. Then when I restart the program it shows me the same issue but with the **libcrypto-1_1.dll**, so I replaced that dll file too and then Cockatrice runs fine.
> > I was able to update the cards database, connect to the server with no problem.
> > I hope this will be helpful.
> > Live Long and Prosper!
> 
> Where did u download this files?

There are many sites, I just put the name of the dll file on Google and choose the first one. 

Greetings

**Comment by supersardus** [comment] 2021-02-09 15:03
Also from the previous version of Cockatrice (2.7.5) that you can find here:
https://github.com/Cockatrice/Cockatrice/releases/tag/2020-08-23-Release-2.7.5

**Comment by Fenrirthviti** [comment] 2021-02-09 15:57
> There are many sites, I just put the name of the dll file on Google and choose the first one.

To everyone coming across this thread and trying to fix the problem, please be EXTREMELY CAREFUL downloading random .dll files from the internet. Make sure you FULLY TRUST the source before you do that. Many websites host malicious and malware-ridden versions of those .dll files to trick you in to compromising your computer. As @supersardus mentions, the missing files can be found in the previous installer. You can simply open the installer .exe file with an archive program, such as 7zip, and extract the two missing files. This is much safer for anyone who is not willing to wait.

**Comment by satirobcn** [comment] 2021-02-13 06:00
> Hola a todos,
> 
> Resolví el problema reemplazando dos archivos dll. Primero descargué **libssl-1_1.dll** para 32 bits y lo reemplacé por el de la carpeta cockatrice. Luego, cuando reinicio el programa, me muestra el mismo problema pero con **libcrypto-1_1.dll** , así que reemplacé ese archivo dll también y luego Cockatrice funciona bien.
> Pude actualizar la base de datos de las tarjetas, conectarme al servidor sin problemas.
> 
> Espero que esto sea de ayuda.
> 
> ¡Viva mucho y prospere!

FUNCIONA! GRACIAS

**Comment by satirobcn** [comment] 2021-02-13 06:02
> > Hay muchos sitios, solo pongo el nombre del archivo dll en Google y elijo el primero.
> 
> Para todos los que se encuentren con este hilo y traten de solucionar el problema, tengan EXTREMADAMENTE CUIDADO al descargar archivos .dll aleatorios de Internet. Asegúrese de CONFIAR COMPLETAMENTE en la fuente antes de hacer eso. Muchos sitios web albergan versiones maliciosas y plagadas de malware de esos archivos .dll para engañarlo y comprometer su computadora. Como menciona @supersardus , los archivos que faltan se pueden encontrar en el instalador anterior. Simplemente puede abrir el archivo .exe del instalador con un programa de archivo, como 7zip, y extraer los dos archivos que faltan. Esto es mucho más seguro para cualquiera que no esté dispuesto a esperar

you have reason... that works perfect THANKS @Fenrirthviti

**Comment by ebbit1q** [comment] 2022-05-09 16:19
we have recently implemented a solution to the missing dlls in the 32 bit build, we'd appreciate you'd be able to help verify these new downloads from our recent beta: https://github.com/Cockatrice/Cockatrice/releases/tag/2022-05-09-Development-2.8.1-beta.8

**Comment by tooomm** [comment] 2024-02-10 15:09
A new version with this is released since a while (v2.9.0).
Will close this.

**Closed by tooomm** 2024-02-10 15:09 UTC
Labels: OS - Windows, Bug, High Priority
