### ISSUE TITLE
Adding set code to tokens.xml creates set list entry

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2712] opened 2017-05-12 05:01 UTC
If you add a set code to tokens.xml, an entry is created in set list and you are prompted with `New set detected. Do you want to enable it?`

This behavior is unexpected. During spoiler season, the token information is published considerably before gatherer is updated. A user will run oracle, be prompted if they want to enable the new set, say yes, and expect to see the new cards. In addition, when the set is finally added to gatherer/mtgjson (which can take 2 weeks after token information is published) and the user re-runs Oracle, the user is *not* prompted again to enable to new set, because they already added tokens.

**Comment by ZeldaZach** [comment] 2017-05-12 05:13
At the time, this is expected behavior.

I don't believe this is a regression, but it is an issue we must address and I"m not sure how it took so long to catch.

The issue stems that tokens are a card database and they do contain a set, so it make sense that it pops up with "new set detected"... Maybe we can add a count and if the # of cards in a set changes it alerts with "new set detected" dialog?

**Comment by tritoch** [comment] 2017-05-12 05:15
>Maybe we can add a count and if the # of cards in a set changes it alerts with "new set detected" dialog?

This would have consequences for those using spoiler custom sets and updating them frequently as new cards are added (I think.)

**Comment by ZeldaZach** [comment] 2017-05-12 05:15
Do you have any better suggestions?

**Comment by tritoch** [comment] 2017-05-12 05:16
Don't add a set to the set list for only tokens?

**Comment by tooomm** [comment] 2017-05-12 08:23
How do you display tokens then? Since that's also managed from the same edit sets list.
Just always display them no matter what? Or hide? Both is not great...

So simply not adding them to the set list brings other problems.

I suggest at first we just suppress the dialog if a new set is found in `tokens.xml`. (for other xml like spoiler or custom ones we still might want to show it - so i wouldn't limit it to cards.xml itself)
The "new set" found in the token file should be not enabled in edit sets automatically. So people can still use, create and see them if they play with spoiler but we don't annoy and confuse anybody else. If a user wants to enable manually, they can.
And 1-2 weeks later the msg will popup once `cards.xml` updates as well and they have both displayed in deck editor.

**Comment by Psithief** [comment] 2017-05-21 04:46
Please explain why this is unwanted behaviour. It is technically correct.

Do we have any actual reports of users being confused by this?

**Comment by Psithief** [comment] 2017-05-21 06:16
With all the supplemental sets that are released, I don't think it's expected that every time that message pops up there's a new Standard set release.

**Comment by tritoch** [comment] 2017-05-22 01:15
I've seen users say in chat  "I just ran `Oracle/Card Update` and added AKH, but I can't see any of the cards" if that's what you mean.  It was more noticeable (more chat comments in that line) with AKH because of the longer lag time between tokens and mtgjson.

Why would you run Oracle, open Cockatrice, it asks you if you want to add AKH, and expect to only have the tokens for the set?

**Comment by Psithief** [comment] 2017-05-22 05:00
The only way the user is going to see `AKH` is if they open the `Edit sets` window. Oracle does not indicate which new sets were imported.

I think it makes more sense to change the behaviour of the edit sets window. If a set doesn't have its full information, there should be default placeholder text instead of blanks. This should clear up the confusion better than messing up the internals.

**Comment by tritoch** [comment] 2017-05-22 05:15
Procedure: 
Edit local tokens.xml and change 2 set codes for a single token to `FAKESET` and `ONLYINTOKENSXML`. Start Cockatrice.

Result: 
![tokens](https://cloud.githubusercontent.com/assets/3866018/26293634/a5d9f0d0-3e83-11e7-9e7d-70ffb50b154f.png)

**Comment by Psithief** [comment] 2017-05-22 05:26
I guess I never noticed that. It was added a year ago, huh?

> Add set names to dialog
> https://github.com/Cockatrice/Cockatrice/commit/1ff98cfcb444d186cf46d42ad6b849b463bf4ba4

I don't like it. Maybe we can just remove it back how it was.

**Comment by tritoch** [comment] 2017-05-22 05:29
>I don't like it. Maybe we can just remove it back how it was.

If we go that route, there is still an issue that when the set is eventually added to mtgjson, if it was added first to tokens, it will not prompt.

Also if you're a daily user, and you get that prompt (minus the `Set code(s): X`a week before a new set is to be released, what would you assume it means?  If you wanted to see what it means, and go into set list, you'd still see the new set code, with no set name or date.

**Comment by Psithief** [comment] 2017-05-22 05:45
This is a bigger problem with the dialog itself not being very useful, but is this issue wanting a quick fix or a redesign of this prompt?

**Comment by Psithief** [comment] 2017-05-23 04:03
> The first has it's own group of <sets> with data regarding single sets, while the tokens.xml only have sets referenced to picture urls within <cards>.
> The Edit Sets dialog (and the popup!) could just care about new sets found in <sets> and ignore any other set data. @tritoch's spoiler xml also uses <set> at the beginning so it would work in this scenario.

@tooomm 
What do you mean when you say 'ignore' here? Does that mean sets without a `<set>` entry are automatically checked in the Edit Sets window?
Or that they don't get an entry in the Edit Sets window?
And if the latter, are they always shown in the deck editor, or never shown?

Out of those options, I think "does not appear in edit sets window" and "always shown" work with the least amount of problems, but probably the most code changes.

**Comment by tooomm** [comment] 2017-05-26 18:03
>What do you mean when you say 'ignore' here? Does that mean sets without a `<set>` entry are automatically checked in the Edit Sets window?
Or that they don't get an entry in the Edit Sets window?

The second. No entry in `edit sets` window.

>And if the latter, are they always shown in the deck editor, or never shown?

Actually, I thought at first that we don't have to show token in the CARD database. There is no need to add tokens to your deck any longer with reverse-related feature available.
But for completeness tokens could show up again once their corresponding set-info exists (because a spoiler or cards.xml have the `<set>` data and it shows up in the edit sets dialog.

Ergo: just show sets in edit sets which have `<set>` info & just show cards which have their `<set>` info set somewhere. Makes sense because otherwise you can't manage this cards in the edit sets dialog anyway, no?

**Comment by Psithief** [comment] 2017-05-28 11:26
That won't allow anyone to make custom token sets without a <set>, nor allow me to test my work under Cockatrice/Magic-Token before publishing.

**Comment by tooomm** [comment] 2017-05-28 11:54
Sure it allows to create custom tokens, you can even use them in every game. The user just don't sees them in the list of *cards* in the deck editor.
But anyway, in both cases you just need to add a simple `<set>` to the token file?
I guess the approach here is to make it as easy as possible for normal users, not-tech-savy users or even "luser".

If somebody has to to modify things or want to create custom stuff that's by no means the default user, and if he wants to customize he has to deal with reading a documentation or ask for help.
(We need to cover that in the wiki for sure then!)

What is your solution for solving the mess for an ordinary "first time" computer user?
I don't care if we display the tokens for new sets, but we need to surpress the new set found dialog for these for sure. Showing just proper `<set>` data in the `edit sets` dialog is just a logical extension and actually the right way to deal with things imo.
But if we just magically show new tokens people will wonder and ask where they come from and why they don't see the cards from that set as well...

**Comment by Psithief** [comment] 2017-05-28 12:43
> But if we just magically show new tokens people will wonder and ask where they come from and why they don't see the cards from that set as well...

There was the period before the sets were named in the popup. I don't think the issue was raised then, so I very much doubt it caused any significant problems for anyone.

Not displaying `<set>`-less tokens is going to cause problems for me, though. It also makes it completely pointless for me to release tokens before mtgjson releases an update, and I am going to get very slack if that happens. (Not out of spite, I just know my own weaknesses.)

**Comment by tooomm** [comment] 2017-05-28 13:28
>Not displaying `<set>`-less tokens is going to cause problems for me, though

I understand, it's more work to search and include that information. It's not much needed though, a basic 

```
<sets><set><name>HOU token test</name></set></sets>
```

should be enough. You just want to test it, no?
But yes, there could be a option in settings: `Display tokens of enabled sets in deck editor`

<br>

>It also makes it completely pointless for me to release tokens before mtgjson releases an update

Why? People want+need the tokens earlier. And they happily use them in every game they play/test with the new cards. Even more once there is the reverse-related update out.
But also before to simply create them from the create token dialog!

<br>

>There was the period before the sets were named in the popup. I don't think the issue was raised then, so I very much doubt it caused any significant problems for anyone.

I highly doubt if you display the set name or not changes too much.
The former `New sets are available, do you want to enable them?` causes the same problem. As long as you hit x/no/cancel the set won't get enabled and you don't see the tokens. Once mtgjson updates and oracle picks up the real cards you won't see the dialog again for the same reason: the set exists already in the `edit sets` dialog because cockatrice picks the set up from your token file, even if they don't have a `<set>` info. Which leads us back to the idea why we're talking about ignoring sets which don't use a <set> tag to get the popup shown only at the right time where it provides most value and is more helpful.
One other idea was to just suppress the dialog on any triggers coming from tokens.

**Comment by Psithief** [comment] 2017-05-28 13:50
I think we're talking across each other here, because I might have implied some details to the solution that weren't outright stated.

1. Automatically show any card in the card database that doesn't have a `<sets><set>` entry.
2. Automatically enable any set without a `<sets><set>` entry. Any set without one is a partial or custom set.
3. If, and only if a `<sets><set>` element is found when loading from Oracle, prompt the user. If the user answers No, the set is deactivated, instead of merely not being activated.
4. Encourage anyone making spoiler season sets to include the `<sets><set>` element.

Number 3 is the difficult part, because Cockatrice doesn't store whether a set is properly identified in preferences.

----

> > It also makes it completely pointless for me to release tokens before mtgjson releases an update
>
> Why? People want+need the tokens earlier.

How will people know they've downloaded new tokens, then? If new tokens arrive and won't be shown in the deck editor, the users are forced to create a game just to check the token dialog.

> But yes, there could be a option in settings: `Display tokens of enabled sets in deck editor`

If we've started talking about that depth of code changes, the solution above is probably a better use of a coder's time.

> It's not much needed though, a basic
> `<sets><set><name>HOU token test</name></set></sets>`
> should be enough. You just want to test it, no?

I understand the workaround, but the problems are 1. I'm using a workaround so I won't be testing the same data as everyone else, and 2. You're still just creating more work for people that are contributing to the project.

**Comment by tooomm** [comment] 2017-05-28 16:55
>    1. Automatically show any card in the card database that doesn't have a `<sets><set>` entry.
>    2. Automatically enable any set without a `<sets><set>` entry. Any set without one is a partial or custom set.
>    3. If, and only if a `<sets><set>` element is found when loading from Oracle, prompt the user. If the user answers No, the set is deactivated, instead of merely not being activated.
>    4. Encourage anyone making spoiler season sets to include the `<sets><set>` element.

That's a possible way to deal with things. It solves some, but leaves others out.
Not sure what the perfect way to deal with things is right now, that's why we have to elaborate.

Why should there be a need for set data in spoiler by the way?
You can argue the same: it's a partial/custom set which people added because they want to use it.

<br>

>How will people know they've downloaded new tokens, then? If new tokens arrive and won't be shown in the deck editor, the users are forced to create a game just to check the token dialog.

1. Player/users expect things just to work, they don't think too much because they don't understand/know about/care about the underlying concept. Many posts here and on reddit proved that several times.
They download spoilers and just play, they might be annoyed that they can't immediately right click and create tokens as always at first, but they will at least try to create manually and find them there. If not, at least in their 2nd game somebody will tell them to please use tokens.
I play a lot before releases to test for the limited events, and that's my experience how people deal with it.
2. Instead showing always the same dialog, there could be a different one for updates in the tokens file. so many options do deal with things. we need to find a solid solution regarding all aspects.

<br>

>Do we have any actual reports of users being confused by this?

Fresh one from yesterday: https://github.com/Cockatrice/Cockatrice/issues/2739 :)

**Comment by Psithief** [comment] 2017-05-28 19:47
I meant to make a distinction for 4, where the <set> element is included if the spoiler is for the complete set, instead of just a few preview cards.

I'm drawing a mental distinction between people with the early-adopter mentality that know what they're getting into, and those that just need their next standard set in Cockatrice "**right now**".

**Comment by Psithief** [comment] 2017-07-04 03:40
@tritoch @tooomm @ZeldaZach 
#2797 implements https://github.com/Cockatrice/Cockatrice/issues/2712#issuecomment-304516521

**Closed** 2017-07-07 04:45 UTC
Labels: App - Oracle, Defect - Basic
