### ISSUE TITLE
Fog incorrect legality in filter

### ISSUE THREAD

**Issue by Drachenbrand** [Cockatrice/Cockatrice#5030] opened 2024-05-12 08:18 UTC
**System Information:**

Client Version: 2.9.0 (2023-09-14)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.2
_______________________________________________________________________________________

While sorting commander format in the filters fog does not appear in the cards available.

*first image with filter on has fog absent*
![image](https://github.com/Cockatrice/Cockatrice/assets/8797737/8714ba95-3ed3-4266-9b32-0922cdd3c3cf)
*second image with filter off fog is present as if it were not legal in commander*
![image](https://github.com/Cockatrice/Cockatrice/assets/8797737/847a9cf2-97fe-488f-9091-f4aa077cb4d5)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Filter format by commander
 - Search for fog
 - Turn off filter to show it's the filter that is removing it from the available pool of cards

**Comment by ebbit1q** [comment] 2024-05-12 13:21
duplicate of https://github.com/Cockatrice/Cockatrice/issues/4783 please post on existing tickets instead of making a new one

**Closed by ebbit1q** 2024-05-12 13:21 UTC
Labels: Bug
