### ISSUE TITLE
Unable to Seek During Replays

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/Cockatrice#3941] opened 2020-04-04 15:43 UTC
<b>System Information:</b>
  
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
  
_______________________________________________________________________________________

  
I am unable to seek past about 25% during any replay that is long. If I try to seek any further, it moves it directly to the end or starts it back from the beginning. I don't know what the exact number of minutes is since I can't tell how long a replay is but anything that is more than an average 1v1 60 card deck game length seems to give the issue. Others have reported this issue as well and it's never affected me until yesterday when I had to watch a 4 player EDH game all the way.  Other users have reported this same issue. It feels like the Replay Timeline is off in terms of scaling. Anything short, I can click right on the timeline and it seeks to that point in the game no problem. As for the longer ones, I can only seem to get the Timeline to seek into various parts of the first ~25% or to the very end.

**Comment by n21lv** [comment] 2020-04-18 13:27
I can confirm this, happens with my replays all the time, regardless of how long I let them to run.

**Comment by tyler274** [comment] 2020-05-05 02:56
Quite literally all my replays are unseekable as described.

**Comment by ZeldaZach** [comment] 2020-09-27 21:18
This used to work, and I'm not sure what happened. This is a high priority to fix. Maybe @ctrlaltca or @ebbit1q ya'll have some ideas?

**Comment by ZeldaZach** [comment] 2020-10-28 05:15
We can't reproduce this issue on Mac or Linux, so I'm assuming it's a Windods limitation.

**Comment by tooomm** [comment] 2020-10-28 14:21
It works for me with the 2.7.5 release on Windows 10 64bit.

**Comment by n21lv** [comment] 2020-10-28 16:28
I just updated to 2.7.5 release on Windoes 10 64 bit and tried to play and old replay file, and it still has this issue. @tooomm can you can upload the one you were testing somewhere so I could check if it works for me? I'm not sure when I will get to play next time.

**Comment by tooomm** [comment] 2020-10-28 16:31
The two replay i tried were 3y old... probably somebody else should check with more recent files. :D

**Comment by pulverize** [comment] 2020-10-30 20:59
![d0d2af41-fa12-4b58-a568-bed059edde22](https://user-images.githubusercontent.com/3393014/97756427-35eacf00-1ad1-11eb-9c3c-8eb1e0acb7f6.gif)

Windows 10

**Comment by ebbit1q** [comment] 2020-11-02 22:59
can someone make one of these replays that are broken for them available here? I seem to be unable to reproduce this whatever I do.

**Comment by pulverize** [comment] 2020-11-03 01:24
https://drive.google.com/file/d/15S4LlkXbEi4FCgq083GlcQHrr_eN5NwO/view?usp=sharing

**Comment by n21lv** [comment] 2020-11-03 08:41
Here's mine as well. https://drive.google.com/file/d/16UD7BMr5BDkml-QwlR91CUNhhhml_xJ0/view?usp=sharing

**Comment by ebbit1q** [comment] 2020-11-03 21:00
thanks, this confirms that this is exclusive to windows, I was unfortunately unable to reproduce the issue, I accidentally however did notice a play error in @pulverize 's replay, at about 2/3rds of the game everyone draws 34 cards from grothama except only the controller of the damage should be the only one to draw :wink: 
![image](https://user-images.githubusercontent.com/36401181/98039812-95254800-1e1f-11eb-9923-f0e176e996ee.png)

**Comment by ZeldaZach** [comment] 2020-11-03 21:03
Both replays posted work as expected on my end, MacOS 10.15.7. Seems to be a Windows issue.

**Comment by tooomm** [comment] 2020-11-04 11:08
Can both provided replay files confirm broken on Windows.

**Comment by pulverize** [comment] 2020-11-05 03:21
@ebbit1q good catch, but I'm a bit disappointed you've revealed that glorious moment to have been a mistake...

@tooomm - replay posted by @n21lv is also exhibiting the issue for me, can't get past the first couple rounds. About the same percentage progress through the replay, so I can view about 15 minutes of mine and about 2 of his.

**Comment by n21lv** [comment] 2020-11-20 22:52
Tried again today with a replay recorded in v.2.7.5 and the issue seems to be gone. Here's the replay: https://drive.google.com/file/d/1imXCAYE70NDBYoVlT732ftyj_gT0HxkB/view?usp=sharing

**Comment by D0nV170** [comment] 2020-11-24 05:13
What about 

https://drive.google.com/file/d/1A_6BOImYJWCXr7T4t83XoPjsTOWS4SxT/view?usp=sharing

**Comment by n21lv** [comment] 2020-11-24 11:32
@D0nV170 I am unable to access the file without your approval. You should've received an email notification about this.

**Comment by D0nV170** [comment] 2020-11-24 14:28
Sorry, I think I fixed it. I don't ever use Drive.

**Comment by n21lv** [comment] 2020-11-24 23:42
@D0nV170 I can only seek that one up to this moment, then it skips to end or resets back to the beginning.
![image](https://user-images.githubusercontent.com/30559591/100163918-6995fa80-2ebf-11eb-8529-6721ba22a626.png)

**Comment by D0nV170** [comment] 2021-03-21 17:03
Users are still having issues with seeking. Is it maybe an issue with the scaling?

**Comment by n21lv** [comment] 2021-03-21 17:52
> Is it maybe an issue with the scaling?

I think this might actually be the case. I've noticed that if I'm undocking the seek bar from the bottom and either leave I undocked or dock it to the right, then seeking works properly.

**Comment by D0nV170** [comment] 2021-03-21 19:11
I've tried undocking the bar, moving it between monitors, resizing and even swapping monitors as well as using some of the compatability/high DPI mode but none of those worked for me. I've got one older monitor and a newer 4k one and I don't remember running into issues until I got the new monitor. I'll try docking it on the side when I get home and I'll post results of everything I try again.

**Comment by tooomm** [comment] 2022-01-09 10:21
Can somebody confirm that this issue is resolved with #4518?

**Comment by ebbit1q** [comment] 2022-01-09 12:37
can you?

**Comment by tooomm** [comment] 2022-01-09 13:06
I can not confirm or deny for now, hence the question.

**Comment by n21lv** [comment] 2022-01-10 08:13
Is there a release I can download to test this? I see that the last beta available is still 2.8.1 updated on 2020-12-20

**Comment by tooomm** [comment] 2022-01-10 09:07
> Is there a release I can download to test this? I see that the last beta available is still 2.8.1b5 updated on 2020-12-20

You can find the recent builds from master here: https://github.com/Cockatrice/Cockatrice/actions/runs/1672228687

**Comment by n21lv** [comment] 2022-01-10 09:18
Just downloaded the Windows-64bit-installer and installed as a portable installation. It doesn't seem like the issue is fixed. I have tried checking the debug log, but the application doesn't seem to post any log messages when you try to seek to an "invalid" position. Perhaps adding one for the seek action would help to root out the issue.

**Comment by ebbit1q** [comment] 2022-01-10 13:13
well we can at least say that the code is the same for all operating systems here now so it's not us that is doing something strange.

**Comment by ebbit1q** [comment] 2022-01-10 17:18
while saying that I realized that there are more ways that the code can be different for different operating systems

**Comment by n21lv** [comment] 2022-01-10 19:29
The latest build seems to have solved the issue for me.

**Comment by tooomm** [comment] 2022-01-10 19:42
Thanks for looking into it again, @ebbit1q 👌

**Closed** 2022-01-16 23:05 UTC
Labels: OS - Windows, Bug, High Priority
