### ISSUE TITLE
Add the ability to pick a secret number

### ISSUE THREAD

**Issue by Jdrawer** [Cockatrice/Cockatrice#4412] opened 2021-08-08 17:35 UTC
Wheel of Misfortune requires players to simultaneously choose secret numbers. I am requesting some sort of in-app feature that makes resolving this spell easier. Many thanks for looking at this ticket.

**Comment by mainman879** [comment] 2021-08-09 13:23
Duplicate of https://github.com/Cockatrice/Cockatrice/issues/3278

**Comment by ebbit1q** [comment] 2021-08-10 22:37
please leave a comment on existing tickets before opening new ones

**Closed by ebbit1q** 2021-08-10 22:37 UTC
Labels: Defect - Game Rules Compliance, App - Protocol / API, Feature Request

**Comment by Daenyth** [comment] 2021-08-11 12:17
> please leave a comment on existing tickets before opening new ones

I suggested they open it, didn't think to check first. Oops
