### ISSUE TITLE
An internal error has occurred, please try closing and reopening your client and try again. If the error persists try updating your client to the most recent build and if need be contact your software provider.

### ISSUE THREAD

**Issue by edd07** [Cockatrice/Cockatrice#1680] opened 2015-11-15 19:47 UTC
On trying to connect to any server, I get an error:

"An internal error has occurred, please try closing and reopening your client and try again. If the error persists try updating your client to the most recent build and if need be contact your software provider."

I'm using Ubuntu 15.10, building Cockatrice from source, commit 77b9aa7c36d815b85579206016f6403768731cb5

**Comment by Nightfirecat** [comment] 2015-11-15 19:54
Hm, odd... I'm only seeing that error on [line 345 of window_main.cpp](https://github.com/Cockatrice/Cockatrice/blob/9c4bd8ebed6a4efee1a96b80ee2e9e80044c5310/cockatrice/src/window_main.cpp#L345), and that file [doesn't seem to have changed since September 12th](https://github.com/Cockatrice/Cockatrice/commits/9c4bd8ebed6a4efee1a96b80ee2e9e80044c5310/cockatrice/src/window_main.cpp).

Have you noticed this error in the past, or has it only started recently?

**Comment by edd07** [comment] 2015-11-15 20:05
This is only the first time I've attempted to use Cockatrice.

**Comment by Daenyth** [comment] 2015-11-16 00:09
Run from console and paste the output?

**Comment by ctrlaltca** [comment] 2015-12-11 18:15
I think this is a duplicate of the issue described in #1693, #1694 and fixed in #1698

**Closed** 2015-12-11 18:15 UTC
