### ISSUE TITLE
[Feature request] Friend Groups, User Notes

### ISSUE THREAD

**Issue by MopDa** [Cockatrice/Cockatrice#3055] opened 2018-01-29 07:21 UTC
I guess I'll suggest nothing revolutionary in here. Would like to see Groups in Friend List implemented in cockatrice so I can easily distinguish who can I offer to test my new standard brew, and who is not interested, but is a great EDH player. Actually making it so one person can be in multiple groups simultaneously would be even better.

Likewise, for ignore list (or even for friend list as well) I would like to be able to make a User Notes to mark how unbearable the person was. Was it just a drunk spam, or was it unacceptable sort of things.

Thanks!

**Comment by Daenyth** [comment] 2018-01-30 13:26
I think this is basically a duplicate of #1957 

Tags are the thing I think we should add to cockatrice first. That would be usable for your groups idea, especially if we add a client side feature to filter your buddy list by tags

**Closed by Daenyth** 2018-01-30 13:27 UTC
Labels: Suggestion

**Comment by tooomm** [comment] 2018-01-30 22:26
I think this is more about https://github.com/Cockatrice/Cockatrice/issues/1384 instead.

The notes request issue is for in-game notes during a match, like the notes one player takes about which removal the opponent played.
