### ISSUE TITLE
Add buttons for common game chat actions

### ISSUE THREAD

**Issue by SunUppy** [Cockatrice/Cockatrice#1380] opened 2015-08-15 21:12 UTC
In the program, there should be a number of buttons to click such as

OK,    Thinking   and   Wait 

This makes it easier to play instead of stopping to write each time something happens.

**Comment by tooomm** [comment] 2015-08-15 22:19
We have message macros with shortcuts...

But I still like the idea to have buttons for the most basic ~3 chat situations (on top/below the chat field for example) because many don't know about macros or don't like them... buttons are easy and would increase the gaming experience because people end up using them more often/at all! People use the mouse to click and drag things around most of the time, if they can keep clicking with the mouse for a short command instead switching to the keyboard they will more likely use it!
Imagine the interaction in-game... with less waiting time and better priority and phases handling.

**Comment by Daenyth** [comment] 2015-08-15 23:04
We could potentially add buttons for the existing chat macros

**Comment by tooomm** [comment] 2015-08-16 00:03
You mean several buttons for all the custom created ones?
That would eat up quite some space in most cases... :)

Or one button that opens a list with all the configured macros?
(like right click on the battlefield --> `Say` does)
That would be nice.

**Comment by Daenyth** [comment] 2015-08-16 03:00
I mean like 2-3 buttons only that you could set to trigger any of your
existing macros

**Comment by woogerboy21** [comment] 2015-08-16 04:59
couldnt this be accomplished using the in-game message macros?

**Comment by ZeldaZach** [comment] 2015-08-16 15:06
@woogerboy21 Nobody really knows how they work, which is the issue

**Comment by Daenyth** [comment] 2015-08-16 16:20
@woogerboy21 yes, that's what they're for. But Zach is right

**Comment by socketubs** [comment] 2015-08-30 23:39
I was exactly looking for an issue about this improvement!
This is a great idea. :+1:

**Comment by ZeldaZach** [comment] 2020-10-23 20:11
Gonna call it a dupe of #267

**Closed by ZeldaZach** 2020-10-23 20:11 UTC
Labels: App - Cockatrice, Suggestion
