### ISSUE TITLE
Feature Request: Hide games by people on my ignore list / whose ignore list I am on

### ISSUE THREAD

**Issue by ashleytrash** [Cockatrice/Cockatrice#3869] opened 2019-11-22 19:10 UTC
When someone is on my ignore list (or vice versa) it still shows their games and that makes no sense. Hide them from the list!

**Comment by tooomm** [comment] 2019-11-23 15:23
Duplicate of https://github.com/Cockatrice/Cockatrice/issues/724

Thanks for reporting and stressing the need for this feature.

**Closed by tooomm** 2019-11-23 15:23 UTC
