### ISSUE TITLE
Add "sort by cost" to the graveyard and library popout windows

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#4013] opened 2020-05-24 00:37 UTC
The graveyard and library (and exile) zone popout windows currently have Sort by Name, Sort by Type, and Pile View checkboxes. I suggest add "Sort by Cost".

**Comment by tooomm** [comment] 2020-05-24 08:36
A custom text search box would also be very good to count cards with cycle, other effects or specific cards more easily.

**Comment by ebbit1q** [comment] 2020-05-24 10:22
don't we have a separate ticket for a search bar already?

**Comment by tooomm** [comment] 2020-05-24 14:17
You are right! https://github.com/Cockatrice/Cockatrice/issues/2993 it is

**Comment by ZeldaZach** [comment] 2020-09-27 20:42
Would be covered by a search bar for sure. Will close as a dupe of #2993

**Closed by ZeldaZach** 2020-09-27 20:42 UTC
Labels: Feature Request

**Comment by tooomm** [comment] 2020-09-27 21:06
Search helps with finding an known card you are looking for super quickly.
But it doesn’t provide you an easy overview of potential cards you might want to pick. E.g. Lurrus companion, snapcaster etc. all care for cmc.
