### ISSUE TITLE
"ok" button

### ISSUE THREAD

**Issue by dsolstad** [Cockatrice/Cockatrice#1749] opened 2016-01-06 12:56 UTC
Instead of writing "k" in the chat after every player casts a spell, it would be more handy and trivial if there was a button or shortcut that would give a sigal to the opponent that the spell resolves.

**Comment by tooomm** [comment] 2016-01-06 13:29
duplicate of #1380 (maybe it should have a different name than `Improvements cockatrice for players`)

**Comment by LethalPigeon7** [comment] 2016-01-07 12:57
This seems like a purely genius Idea I've always desperately needed but never thought of fixing somehow.

**Comment by Daenyth** [comment] 2016-01-07 13:44
You can already do this with a keyboard shorcut, configured in the Messages section of settings

**Comment by Daenyth** [comment] 2016-01-07 13:45
Closing this to keep the discussion to #1380

**Closed by Daenyth** 2016-01-07 13:45 UTC
Labels: Suggestion, UI / UX
