### ISSUE TITLE
Token creation missing from popup menu

### ISSUE THREAD

**Issue by brewsbacker** [Cockatrice/Cockatrice#3327] opened 2018-07-14 08:41 UTC
Client Version: 2.6.0 (2018-06-17)
__________________________________________________________________________________________

 I just updated to this version and now I cannot create a token related to a card by bringing up the shortcut menu for that card. For example, I play History of Benalia. On the old version, I could right click on the card and choose from the menu a command to create the 2/2 Knight token the enchantment creates. Under the new version this command is missing.

**Comment by tooomm** [comment] 2018-07-14 08:59
Please **provide complete information** about your system **from the debug window** as asked for, e.g.

```
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
```

**Comment by ctrlaltca** [comment] 2018-07-14 09:02
I guess this is #3262, fixed by #3307 ?

**Comment by ctrlaltca** [comment] 2018-07-14 09:03
@brewsbacker would you be so kind to try the last beta from here: https://github.com/cockatrice/cockatrice/releases and check if the problem is fixed for you in that version? Thank you

**Comment by tooomm** [comment] 2018-07-14 09:03
Probably, the fix is included in the most recent beta. 👍

**Comment by tooomm** [comment] 2018-07-14 15:11
If the beta isn't fixing it @brewsbacker, feel free to come back to us and reopen this issue.

**Closed by tooomm** 2018-07-14 15:11 UTC

**Comment by tooomm** [comment] 2018-07-16 05:57
Thanks for reporting back! And happy playing 😃
