### ISSUE TITLE
Notes for Buddies

### ISSUE THREAD

**Issue by Narglfrob** [Cockatrice/Cockatrice#4211] opened 2020-12-21 06:42 UTC
I would like to be able to attach notes (a small text field) to Buddies in Cockatrice so I can remember how I know people, which will help foster a sense of community.

**Comment by ebbit1q** [comment] 2020-12-21 12:23
this is a duplicate of https://github.com/Cockatrice/Cockatrice/issues/1957 please comment on the original ticket instead

**Closed by ebbit1q** 2020-12-21 12:23 UTC
Labels: Feature Request
