### ISSUE TITLE
power/toughness

### ISSUE THREAD

**Issue by FrozenSlave** [Cockatrice/Cockatrice#931] opened 2015-04-09 02:39 UTC
While making Zombie tokens i noticed this. if you try to give them a mass power and toughness it makes the first one a 1/1 for some reason.

**Comment by ZeldaZach** [comment] 2015-04-09 02:48
I can't reproduce this. Can you provide step-by-step so I can try again?

**Comment by FrozenSlave** [comment] 2015-04-09 02:52
ok get a bunch of tokens, set them to a p/t then try to mass set them
again. one of them will be a 1/1

**Comment by ZeldaZach** [comment] 2015-04-09 02:54
@FrozenSlave I just tried that w/ 20 tokens and they all are showing as correct. I'm on build 81e4e08. What about you?

**Comment by poixen** [comment] 2015-04-09 07:16
I can confirm. This happens to me all the time.

**Comment by Daenyth** [comment] 2015-04-09 10:17
Weird, I've never seen this. Could it be only happening on windows?

**Comment by tooomm** [comment] 2015-04-09 12:07
Can't reproduce on win with b840159.

I create several tokens, select all, set p/t to 3/3, all are 3/3, deselect, select all, set p/t to 5/5, all are 5/5.
Even tried ctrl+alt+"+" and ctrl+alt+"-".

**Comment by FrozenSlave** [comment] 2015-04-09 16:08
ok i mis interpeted it do not change the numbers directly. use the mouse
and go up 1.  so if they are 2/2s go to "increases power/toughness"  i have
no idea about that very small writing code you gave me.

**Comment by tooomm** [comment] 2015-04-09 16:23
`b840159` is the version of cockatrice I use. We still don't know which version you are using?!
Check `Help` --> `About Cockatrice` inside the app and tell us, please.


>use the mouse and go up 1.

?
<br>
>so if they are 2/2s go to "increases power/toughness"

That's what i do. But, they **all** turn into 3/3s.

**Comment by FrozenSlave** [comment] 2015-04-09 16:26
i told poxien, he knows

**Comment by poixen** [comment] 2015-04-10 11:27
Fixed in #931

**Closed by poixen** 2015-04-10 11:27 UTC

**Comment by FrozenSlave** [comment] 2015-04-12 19:15
poixen, Please for the love of god kill the interface thing. when ever the
client gets over 1000 user it get so laggy its insane, i know its not my
machine as only cock goes slow

**Comment by tooomm** [comment] 2015-04-12 21:27
@FrozenSlave It got fixed yesterday (#945).
There is even an updated download available as well. Give it a try!
http://www.woogerworks.com/files/cockatrice_weeklybuilds/

**Comment by poixen** [comment] 2015-04-12 22:23
@FrozenSlave This is correct. Also, follow my twitter and you will get info like this. I post about all my fixes.

**Comment by FrozenSlave** [comment] 2015-04-12 22:26
i have the fix thankyou, also like i said i do not twit

**Comment by FrozenSlave** [comment] 2015-04-14 22:10
Poxien, can i have some help, i had to reformat my machine and now
cockatrice refuses to work i have reinstalled it 7 times atleast

**Comment by FrozenSlave** [comment] 2015-04-15 00:25
forget i finally got it.

**Comment by ZeldaZach** [comment] 2015-04-15 00:26
@FrozenSlave In the future, please don't bring in non-related issues to a ticket. You can open a new ticket with your issue so we can address it specifically.
