### ISSUE TITLE
OS X: Crashes on removing cards from the deck until no cards of the type being removed are left

### ISSUE THREAD

**Issue by mpalmujoki** [Cockatrice/Cockatrice#1852] opened 2016-03-11 13:26 UTC
<b>OS:</b>
OS X 10.11.3

<b>Cockatrice version:</b>
cbea432 (2016-03-08)

<br>

Sometimes I get crashes when I try to remove instances of a specific card in my deck. I can single out one case where it crashes certainly. Load the deck I supplied, and remove the `Captain's Claws` cards from the deck. It crashes immediately that way.

It seems to be somehow tied to Captain's Claws being the only Articaft type cards in the deck, but I'm not sure. I can get around it by first adding another artifact, then removing the Captain's Claws, and then the artifact I added... So it's a bit fishy.

I also have quite a lot of similar random crashes, such as when typing in the card search box, but I can't single out them as well.

[Thopterzzz.cod.zip](https://github.com/Cockatrice/Cockatrice/files/169155/Thopterzzz.cod.zip)

**Comment by Daenyth** [comment] 2016-03-11 13:58
Does it crash only when going from 1 card to 0 copies? Or does it crash on any removal?

**Comment by Daenyth** [comment] 2016-03-11 13:58
Did you install from a DMG we provided or did you compile it youself? If you compiled it yourself, can you please include the full output from `cmake`?

**Comment by mpalmujoki** [comment] 2016-03-11 13:59
From 1 card to 0. And not always. I updated the description, please check that.

**Comment by mpalmujoki** [comment] 2016-03-11 13:59
DMG you provided.

**Comment by mpalmujoki** [comment] 2016-03-11 14:00
Added the deck example. Please note, I can remove ALL the other cards from the deck, but when I try to remove the Artifact cards, it crashes almost certainly.

**Comment by ZeldaZach** [comment] 2016-09-29 02:26
@mpalmujoki Can you possibly see if this issue is fixed on the latest release of Cockatrice? (https://cockatrice.github.io/)

**Comment by mpalmujoki** [comment] 2016-09-29 10:29
@ZeldaZach The explicit 'remove last artifact from 1 to not listed' -case, which was certain to happen seems to have vanished.

However, while testing, I still noticed that sometimes it still caused a crash. I could not however find a repeatable process that would always lead to a crash.

Personally I've resorted to a VM running Windows... but it'd be nice to see that you support a working Mac version.

**Comment by ctrlaltca** [comment] 2020-03-26 18:57
Closing this issue. A lot of new released made their way since 2016. Thank you for the original report and feel free to reopen if you can still reproduce the bug in the last version.

**Closed by ctrlaltca** 2020-03-26 18:57 UTC
Labels: Defect - Crash, OS - macOS
