### ISSUE TITLE
New set issues

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1861] opened 2016-03-14 19:08 UTC
This may be an expansion on the Token problems as of late but the new builds do not allow the players to make tokens with "unique names" so when trying to test new cards for new sets.......Custom images no longer Work.......WTF. please fix

**Comment by Nightfirecat** [comment] 2016-03-14 20:28
Duplicate of #1768.

**Comment by Daenyth** [comment] 2016-03-14 22:25
It's probably a symptom of the same bug.

**Comment by radioactivehazards** [comment] 2016-03-14 22:31
sure but i wanted to make sure that whoever fixed the first issue knew about this also. in case the fix was different.

**Comment by Daenyth** [comment] 2016-03-14 22:32
Yup, still good to file if you're not sure.

**Closed** 2016-03-30 20:55 UTC
