### ISSUE TITLE
Deckbuilder Card Filtering Error (Missing Cards)

### ISSUE THREAD

**Issue by EDHguy** [Cockatrice/Cockatrice#5155] opened 2024-01-15 21:46 UTC
For at least a year now, I occasionally discover commander-legal cards missing from the card list when filtering by "Format" -> "AND" -> "commander" (and "legacy" as well, it seems)

For example: Raging River is a card legal in both legacy and commander but you may notice that when you apply a filter that restricts the cards displayed to legacy-legal or commander-legal, the card disappears from the card list. I know this is a random and specific card but I have discovered others in the past as well though unfortunately I am not able to find/recall other specific examples.

I don't know anything about the code for Cockatrice but I hope this may be a relatively easy issue to fix. As a big fan of the platform, I would love to see it free of this issue at last 😊

**Comment by ebbit1q** [comment] 2024-11-03 22:23
duplicate of #4783

**Closed by ebbit1q** 2024-11-03 22:23 UTC
Labels: App - Cockatrice
