### ISSUE TITLE
Tuinvale Treefolk as Sorcery

### ISSUE THREAD

**Issue by Pickle-boi** [Cockatrice/Cockatrice#4830] opened 2023-07-18 04:23 UTC
Client Version: 2.8.0 (2021-01-26)
reorganizeCards: rows= 13 cols= 5
reorganizeCards: rows= 13 cols= 5
reorganizeCards: rows= 14 cols= 5
reorganizeCards: rows= 14 cols= 5
reorganizeCards: rows= 14 cols= 5
reorganizeCards: rows= 14 cols= 5
reorganizeCards: rows= 14 cols= 5
reorganizeCards: rows= 15 cols= 5
reorganizeCards: rows= 12 cols= 6
reorganizeCards: rows= 13 cols= 6
reorganizeCards: rows= 13 cols= 6
reorganizeCards: rows= 13 cols= 6
reorganizeCards: rows= 13 cols= 6
reorganizeCards: rows= 13 cols= 6
reorganizeCards: rows= 13 cols= 6
reorganizeCards: rows= 14 cols= 6
reorganizeCards: rows= 14 cols= 6
reorganizeCards: rows= 14 cols= 6
reorganizeCards: rows= 14 cols= 6
reorganizeCards: rows= 14 cols= 6
reorganizeCards: rows= 14 cols= 6
reorganizeCards: rows= 15 cols= 6
reorganizeCards: rows= 15 cols= 6
reorganizeCards: rows= 15 cols= 6
reorganizeCards: rows= 15 cols= 6
reorganizeCards: rows= 15 cols= 6
reorganizeCards: rows= 15 cols= 6
reorganizeCards: rows= 16 cols= 6
reorganizeCards: rows= 16 cols= 6
reorganizeCards: rows= 16 cols= 6
reorganizeCards: rows= 16 cols= 6
reorganizeCards: rows= 16 cols= 6
reorganizeCards: rows= 16 cols= 6
reorganizeCards: rows= 17 cols= 6
reorganizeCards: rows= 14 cols= 7
reorganizeCards: rows= 15 cols= 7
reorganizeCards: rows= 15 cols= 7
reorganizeCards: rows= 15 cols= 7
PictureLoader: [card:  "Nymris, Oona's Trickster"  set:  "CMR" ]: Trying to load picture
PictureLoader: [card:  "Nymris, Oona's Trickster"  set:  "CMR" ]: Picture found on disk.
reorganizeCards: rows= 15 cols= 7
PictureLoader: [card:  "Rin and Seri, Inseparable"  set:  "M21" ]: Trying to load picture
PictureLoader: [card:  "Rin and Seri, Inseparable"  set:  "M21" ]: Picture found on disk.
ZoneViewZone destructor
CardZone destructor:  "deck"
PictureLoader: [card:  "14"  set:  "" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "14"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "14"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "14"  set:  "" ]: Trying to load picture
PictureLoader: [card:  "14"  set:  "" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Feywild Visitor"  set:  "CLB" ]: following redirect: "https://cards.scryfall.io/large/front/8/8/88e833a9-d82f-4942-a488-67d9c02817db.jpg?1674135530"
PictureLoader: [card:  "Feywild Visitor"  set:  "CLB" ]: Image successfully downloaded from  "https://cards.scryfall.io/large/front/8/8/88e833a9-d82f-4942-a488-67d9c02817db.jpg?1674135530"
PictureLoader: [card:  "14"  set:  "" ]: Trying to download picture from url: "https://gatherer.wizards.com/Handlers/Image.ashx?name=14&type=card"
PictureLoader: [card:  "14"  set:  "" ]:Picture downloaded, but blacklisted, will consider it as not found
PictureLoader: [card:  "14"  set:  "" ]:  Picture NOT found, download failed, no more url combinations to try: BAILING OUT
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: [card:  "Plains"  set:  "PCTB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Plains"  set:  "PCTB" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Plains"  set:  "PCTB" ]: Trying to load picture
PictureLoader: [card:  "Plains"  set:  "PCTB" ]: Picture found on disk.
PictureLoader: [card:  "Myriad Landscape"  set:  "MOC" ]: Trying to load picture
PictureLoader: [card:  "Myriad Landscape"  set:  "MOC" ]: Picture found on disk.
ArrowItem constructor: startItem= QGraphicsItem(0x16112f4d2a0, parent=0x16133f06f10, pos=5,152, z=2e+09, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem constructor: startItem= QGraphicsItem(0x16112f4d2a0, parent=0x16133f06f10, pos=5,152, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem constructor: startItem= QGraphicsItem(0x1613d007610, parent=0x1613420f380, pos=20,10, z=1.12021e+07, flags=(ItemIsSelectable))
ArrowItem destructor
PictureLoader: [card:  "Shields of Velis Vel"  set:  "LRW" ]: Trying to load picture
PictureLoader: [card:  "Shields of Velis Vel"  set:  "LRW" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Shields of Velis Vel"  set:  "LRW" ]: Trying to download picture from url: "https://api.scryfall.com/cards/f550f44f-8b8f-4c1d-a583-9fd986d3061c?format=image&face=front"
PictureLoader: [card:  "Shields of Velis Vel"  set:  "LRW" ]: following redirect: "https://cards.scryfall.io/large/front/f/5/f550f44f-8b8f-4c1d-a583-9fd986d3061c.jpg?1562374684"
PictureLoader: [card:  "Shields of Velis Vel"  set:  "LRW" ]: Image successfully downloaded from  "https://cards.scryfall.io/large/front/f/5/f550f44f-8b8f-4c1d-a583-9fd986d3061c.jpg?1562374684"
ArrowItem constructor: startItem= QGraphicsItem(0x16129565720, parent=0x1613420e840, pos=20,274, z=2e+09, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem constructor: startItem= QGraphicsItem(0x16129565720, parent=0x1613420e840, pos=20,274, z=3.76021e+07, flags=(ItemIsSelectable))
ArrowItem constructor: startItem= QGraphicsItem(0x16129565720, parent=0x1613420e840, pos=20,274, z=3.76021e+07, flags=(ItemIsSelectable))
Player destructor: "Jaegar420"
GameScene::removePlayer name= "Jaegar420"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
ArrowItem destructor
ArrowItem destructor
Player destructor: "Wildcat0017"
GameScene::removePlayer name= "Wildcat0017"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Player destructor: "Pickle_boi"
GameScene::removePlayer name= "Pickle_boi"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Player destructor: "WobblySr"
GameScene::removePlayer name= "WobblySr"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
PictureLoader: cache fail for "_trice_card_back_282371"
QWindowsWindow::setGeometry: Unable to set geometry 1920x1103+0+34 (frame: 1942x1159-11-11) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1094+0+34 (frame: 1942x1150-11-11) margins: 11, 45, 11, 11 minimum size: 908x1103 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=930,1159 maxtrack=0,0)
GameScene::addPlayer name= "Pharsalus"
GameScene::addPlayer name= "Pickle_boi"
PictureLoader: cache fail for "_trice_card_back_274497"
Loaded from "C:/Games/CockatricePortable/data/decks/Commander/Paper Decks/Vorinclex (Green Proliferate).cod" - true
Deck was loaded - true
**System Information:**

_______________________________________________________________________________________

"Tuinvale Treefolk//Oaken Boon" is showing up as a sorcery rather than a creature
![image](https://github.com/Cockatrice/Cockatrice/assets/118238362/64ee03f2-0c96-49a9-ba60-cd8379a1fb15)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment] 2023-07-18 13:32
duplicate of https://github.com/Cockatrice/Cockatrice/issues/4241
fixed in  #4244

**Closed by ebbit1q** 2023-07-18 13:32 UTC
Labels: Bug
