### ISSUE TITLE
Keyboard Shortcuts (Hotkeys)

### ISSUE THREAD

**Issue by dwarfy20** [Cockatrice/Cockatrice#1513] opened 2015-09-13 09:42 UTC
Hi!

After installing the newest client, I was unhappy to see that Ctrl + + does not work anymore. Alt + + is fine, just power doesn't work, so Ctrl Alt + is not functional anymore, too.

Ctrl ++ is switching my board up, for example if I have a 4 player game, the board at the bottom of the screen is not my own anymore, because it has gone one row up. 

Please tell me, how in the world can I make the program funcional again? The customize keyboard page didn't do anything for me, because it doesn't say where I can make these changes, also it seems very hard to find an explanation how to change your shortcuts.

**Comment by Nightfirecat** [comment] 2015-09-13 10:01
Duplicate of #1493?
Hopefully somebody (or some people) are testing #1501 to fix this in a future build, since this seems to be causing grief for a good number of users.

**Comment by ctrlaltca** [comment] 2015-09-14 13:04
Yep, dup #1493. We are working on solving this.

**Closed by ctrlaltca** 2015-09-14 13:04 UTC
Labels: Troubleshooting
