### ISSUE TITLE
Player created mass tokens to crash client for all players

### ISSUE THREAD

**Issue by samgc3** [Cockatrice/Cockatrice#825] opened 2015-03-14 02:16 UTC
I was spectating a game when this happened. Not sure what provoked it but the player apparently started creating copies of his lands until the board expanded so much that the client crashed for everyone.

![image](https://cloud.githubusercontent.com/assets/11469130/6649905/078fe9e0-c9c6-11e4-8f5f-28298c89ec19.png)

**Comment by Psithief** [comment] 2015-03-14 05:47
Duplicate of #753

**Comment by woogerboy21** [comment] 2015-03-14 13:11
Yeah there has been some idea's on how to fix this issue.  Basically the player is running users out of resources by creating the endless number of tokens. If you happen to remember the users name could you please use the contact us link on woogerworks site so that we can investigate the users behavior?

**Comment by woogerboy21** [comment] 2015-03-14 13:13
Also if you happen to remember the time frame and game number that would be helpful but we could probably track that information down.

**Comment by ctrlaltca** [comment] 2015-03-14 13:21
@woogerboy21 
Game: 618086 
Player: Rokuro

**Comment by woogerboy21** [comment] 2015-03-14 13:30
Ah yes it is in the screenshot.  Sorry overlooked that.  Im getting old, eyes arent what they used to be :(

**Comment by tooomm** [comment] 2015-03-14 13:53
So it's not just tokens, it's cards/items in general.
Ctrl+G (create another token) and Ctrl+J (clone selected card) are problematic, since both allow to create a huge amount of new items in a short time frame.

**Comment by ZeldaZach** [comment] 2015-03-14 18:19
Duplicate of #753

**Closed by ZeldaZach** 2015-03-14 18:19 UTC
Labels: Cockatrice, Crash, Defect, Gameplay Problem
