### ISSUE TITLE
Ability to add counters to cards in exile

### ISSUE THREAD

**Issue by HorrorSpirit** [Cockatrice/Cockatrice#4425] opened 2021-09-25 00:38 UTC
**Description of New Feature**
For cards and abilities that exile cards and require that you keep track of what they exiled, it would be nice to be able to place different colored counters on exiled cards. Nothing too fancy, just extending the ability to place counters on cards in play to cards in exile.

**Comment by ebbit1q** [comment] 2021-09-25 08:14
for exiled cards that are still relevant for play I recommend having them stay visible on the battlefield in order to not forget about them anyway.

This is a duplicate of https://github.com/Cockatrice/Cockatrice/issues/3820 related to https://github.com/Cockatrice/Cockatrice/issues/4404

**Closed by ebbit1q** 2021-09-25 08:14 UTC
Labels: Feature Request
