### ISSUE TITLE
Stacks, Command zones

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#100] opened 2014-06-21 14:17 UTC
Have a shared stack for everyone, spells actually... stacking on it. The personal stacks have one use that im avare of and that is command zones. Removing them would beg for an alternate command zone, ideally something similar to what you see when checking your sideboard in-game, but visible to all players(and minimizable).

PS: #100, woot?

**Comment by Daenyth** [comment] 2015-12-29 20:02
This is a reasonable change but I think it's going to have to wait until we've overhauled the entire zone system.

**Comment by Fenrirthviti** [comment] 2020-11-24 09:19
This should probably be two separate issues given the complexity of either one. 

Has there been any further public discussion on this in the past 5 years? I have quite a few thoughts on this, but would like to avoid repeating if at all possible. I'm still going through open issues from old->new so it's possible there is something I haven't seen yet. I've seen a lot of comments on keeping Cockatrice game-agnostic, but I am not sure if that attitude is still prevalent or necessary. Adding some decent QOL features for specific game mechanics (such as the command zone and the stack) could go a long way.

**Comment by ebbit1q** [comment] 2020-11-24 10:48
duplicate of #1740

**Closed by ebbit1q** 2020-11-24 10:48 UTC
Labels: Feature Request, Medium Priority, Roadmap, Suggestion
